import { lib, game, ui, get, ai, _status } from "noname";

const characters = {
    mcdh_AA001: {
        sex: "female",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_AA00101", "mcdh_AA00102"],
        trashBin: ["ext:梦澈涤花/image/character/AA001.jpg"],
        dieAudios: [],
    },
    mcdh_AA002: {
        sex: "female",
        hp: 5,
        maxHp: 6,
        group: "mcdh_ark",
        skills: ["mcdh_AA00201", "mcdh_AA00202"],
        trashBin: ["ext:梦澈涤花/image/character/AA002.jpg"],
        dieAudios: [],
    },
    mcdh_AA003: {
        sex: "female",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_AA00301", "mcdh_AA00302"],
        trashBin: ["ext:梦澈涤花/image/character/AA003.jpg"],
        dieAudios: [],
    },
    mcdh_AA004: {
        sex: "female",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_AA00401", "mcdh_AA00402"],
        trashBin: ["mcdhCharge:2/3", "ext:梦澈涤花/image/character/AA004.jpg"],
        dieAudios: [],
    },
    mcdh_BI001: {
        sex: "male",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_BI00101", "mcdh_BI00102", "mcdh_BI00103"],
        trashBin: ["mcdhCharge:2/5", "ext:梦澈涤花/image/character/BI001.jpg"],
        dieAudios: [],
    },
    mcdh_BI002: {
        sex: "female",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_BI00201", "mcdh_BI00202"],
        trashBin: ["mcdhCharge:3/3", "ext:梦澈涤花/image/character/BI002.jpg"],
        dieAudios: [],
    },
    mcdh_BI003: {
        sex: "female",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_BI00301", "mcdh_BI00302"],
        trashBin: ["mcdhCharge:2/3", "ext:梦澈涤花/image/character/BI003.jpg"],
        dieAudios: [],
    },
    mcdh_BI004: {
        sex: "male",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_BI00401", "mcdh_BI00402"],
        trashBin: ["mcdhCharge:2/3", "ext:梦澈涤花/image/character/BI004.jpg"],
        dieAudios: [],
    },
    mcdh_BI005: {
        sex: "male",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_BI00501", "mcdh_BI00502"],
        trashBin: ["ext:梦澈涤花/image/character/BI005.jpg"],
        dieAudios: [],
    },
    mcdh_BI006: {
        sex: "male",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_BI00601", "mcdh_BI00602"],
        trashBin: ["mcdhCharge:0/2", "ext:梦澈涤花/image/character/BI006.jpg"],
        dieAudios: [],
    },
    mcdh_BI007: {
        sex: "female",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_BI00701", "mcdh_BI00702"],
        trashBin: ["ext:梦澈涤花/image/character/BI007.jpg"],
        dieAudios: [],
    },
    mcdh_BI008: {
        sex: "female",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_BI00801", "mcdh_BI00802"],
        trashBin: ["ext:梦澈涤花/image/character/BI008.jpg"],
        dieAudios: [],
    },
    mcdh_BI009: {
        sex: "female",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_BI00901", "mcdh_BI00902"],
        trashBin: ["mcdhCharge:1/2", "ext:梦澈涤花/image/character/BI009.jpg"],
        dieAudios: [],
    },
    mcdh_BI010: {
        sex: "female",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_BI01001", "mcdh_BI01002"],
        trashBin: ["ext:梦澈涤花/image/character/BI010.jpg"],
        dieAudios: [],
    },
    mcdh_BI011: {
        sex: "female",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_BI01101", "mcdh_BI01102"],
        trashBin: ["ext:梦澈涤花/image/character/BI011.jpg"],
        dieAudios: [],
    },
    mcdh_BI012: {
        sex: "male",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_BI01201", "mcdh_BI01202"],
        trashBin: ["ext:梦澈涤花/image/character/BI012.jpg"],
        dieAudios: [],
    },
    mcdh_BI013: {
        sex: "male",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_BI01301", "mcdh_BI01302"],
        trashBin: ["ext:梦澈涤花/image/character/BI013.jpg"],
        dieAudios: [],
    },
    mcdh_BI014: {
        sex: "female",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_BI01401", "mcdh_BI01402"],
        trashBin: ["ext:梦澈涤花/image/character/BI014.jpg"],
        dieAudios: [],
    },
    mcdh_BI015: {
        sex: "male",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_BI01501", "mcdh_BI01502"],
        trashBin: ["ext:梦澈涤花/image/character/BI015.jpg"],
        dieAudios: [],
    },
    mcdh_BI016: {
        sex: "female",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_BI01601", "mcdh_BI01602"],
        trashBin: ["ext:梦澈涤花/image/character/BI016.jpg"],
        dieAudios: [],
    },
    mcdh_BI017: {
        sex: "male",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_BI01701", "mcdh_BI01702"],
        trashBin: ["ext:梦澈涤花/image/character/BI017.jpg"],
        dieAudios: [],
    },
    mcdh_BI018: {
        sex: "male",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_BI01801", "mcdh_BI01802"],
        trashBin: ["ext:梦澈涤花/image/character/BI018.jpg"],
        dieAudios: [],
    },
    mcdh_BI019: {
        sex: "male",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_BI01901", "mcdh_BI01902"],
        trashBin: ["ext:梦澈涤花/image/character/BI019.jpg"],
        dieAudios: [],
    },
    mcdh_CF001: {
        sex: "female",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_CF00101", "mcdh_CF00102"],
        trashBin: ["mcdhCharge:1/2", "ext:梦澈涤花/image/character/CF001.jpg"],
        dieAudios: [],
    },
    mcdh_CF002: {
        sex: "male",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_CF00201", "mcdh_CF00202"],
        trashBin: ["mcdhCharge:0/3", "ext:梦澈涤花/image/character/CF002.jpg"],
        dieAudios: [],
    },
    mcdh_CF003: {
        sex: "double",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_CF00301", "mcdh_CF00302"],
        trashBin: ["ext:梦澈涤花/image/character/CF003.jpg"],
        dieAudios: [],
    },
    mcdh_CF004: {
        sex: "male",
        hp: 3,
        maxHp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_CF00401", "mcdh_CF00402"],
        trashBin: ["ext:梦澈涤花/image/character/CF004.jpg"],
        dieAudios: [],
    },
    mcdh_CF005: {
        sex: "male",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_CF00501", "mcdh_CF00502"],
        trashBin: ["ext:梦澈涤花/image/character/CF005.jpg"],
        dieAudios: [],
    },
    mcdh_CF006: {
        sex: "male",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_CF00601", "mcdh_CF00602"],
        trashBin: ["ext:梦澈涤花/image/character/CF006.jpg"],
        dieAudios: [],
    },
    mcdh_CF007: {
        sex: "male",
        hp: 6,
        group: "mcdh_ark",
        skills: ["mcdh_CF00701", "mcdh_CF00702"],
        trashBin: ["ext:梦澈涤花/image/character/CF007.jpg"],
        dieAudios: [],
    },
    mcdh_CV001: {
        sex: "female",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_CV00101", "mcdh_CV00102"],
        trashBin: ["mcdhCharge:1/3", "ext:梦澈涤花/image/character/CV001.jpg"],
        dieAudios: [],
    },
    mcdh_CV002: {
        sex: "female",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_CV00201"],
        trashBin: ["ext:梦澈涤花/image/character/CV002.jpg"],
        dieAudios: [],
    },
    mcdh_CV003: {
        sex: "male",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_CV00301", "mcdh_CV00302"],
        trashBin: ["mcdhAmmo:2/4", "ext:梦澈涤花/image/character/CV003.jpg"],
        dieAudios: [],
    },
    mcdh_CV004: {
        sex: "male",
        hp: 5,
        maxHp: 6,
        group: "mcdh_ark",
        skills: ["mcdh_CV00401"],
        trashBin: ["mcdhCharge:1/3", "ext:梦澈涤花/image/character/CV004.jpg"],
        dieAudios: [],
    },
    mcdh_CV005: {
        sex: "female",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_CV00501", "mcdh_CV00502"],
        trashBin: ["ext:梦澈涤花/image/character/CV005.jpg"],
        dieAudios: [],
    },
    mcdh_CV006: {
        sex: "male",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_CV00601", "mcdh_CV00602"],
        trashBin: ["mcdhCharge:1/3", "ext:梦澈涤花/image/character/CV006.jpg"],
        dieAudios: [],
    },
    mcdh_CW003: {
        sex: "male",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_CW00301", "mcdh_CW00302"],
        trashBin: ["ext:梦澈涤花/image/character/CW003.jpg"],
        dieAudios: [],
    },
    mcdh_CW006: {
        sex: "female",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_CW00601"],
        trashBin: ["ext:梦澈涤花/image/character/CW006.jpg"],
        dieAudios: [],
    },
    mcdh_DV002: {
        sex: "male",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_DV00201", "mcdh_DV00202"],
        trashBin: ["ext:梦澈涤花/image/character/DV002.jpg"],
        dieAudios: [],
    },
    mcdh_GA002: {
        sex: "female",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_GA00201", "mcdh_GA00202"],
        trashBin: ["mcdhCharge:2/2", "ext:梦澈涤花/image/character/GA002.jpg"],
        dieAudios: [],
    },
    mcdh_GA003: {
        sex: "male",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_GA00301", "mcdh_GA00302"],
        trashBin: ["mcdhAmmo:1/3", "ext:梦澈涤花/image/character/GA003.jpg"],
        dieAudios: [],
    },
    mcdh_GA006: {
        sex: "female",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_GA00601", "mcdh_GA00602"],
        trashBin: ["ext:梦澈涤花/image/character/GA006.jpg"],
        dieAudios: [],
    },
    mcdh_GA007: {
        sex: "male",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_GA00701", "mcdh_GA00702"],
        trashBin: ["mcdhAmmo:5/5", "ext:梦澈涤花/image/character/GA007.jpg"],
        dieAudios: [],
    },
    mcdh_GA008: {
        sex: "male",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_GA00801"],
        trashBin: ["ext:梦澈涤花/image/character/GA008.jpg"],
        dieAudios: [],
    },
    mcdh_GA009: {
        sex: "female",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_GA00901", "mcdh_GA00902"],
        trashBin: ["mcdhCharge:2/3", "ext:梦澈涤花/image/character/GA009.jpg"],
        dieAudios: [],
    },
    mcdh_GA010: {
        sex: "male",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_GA01001", "mcdh_GA01002"],
        trashBin: ["ext:梦澈涤花/image/character/GA010.jpg"],
        dieAudios: [],
    },
    mcdh_IS001: {
        sex: "female",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_IS00101", "mcdh_IS00102"],
        trashBin: ["ext:梦澈涤花/image/character/IS001.jpg"],
        dieAudios: [],
    },
    mcdh_IS004: {
        sex: "female",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_IS00401", "mcdh_IS00402"],
        trashBin: ["ext:梦澈涤花/image/character/IS004.jpg"],
        dieAudios: [],
    },
    mcdh_IS010: {
        sex: "male",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_IS01001", "mcdh_IS01002"],
        trashBin: ["ext:梦澈涤花/image/character/IS010.jpg"],
        dieAudios: [],
    },
    mcdh_IW002: {
        sex: "female",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_IW00201", "mcdh_IW00202"],
        trashBin: ["ext:梦澈涤花/image/character/IW002.jpg"],
        dieAudios: [],
    },
    mcdh_LDA002: {
        sex: "male",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_LDA00201", "mcdh_LDA00202"],
        trashBin: ["ext:梦澈涤花/image/character/LDA002.jpg"],
        dieAudios: [],
    },
    mcdh_LDA003: {
        sex: "female",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_LDA00301", "mcdh_LDA00302"],
        trashBin: ["ext:梦澈涤花/image/character/LDA003.jpg"],
        dieAudios: [],
    },
    mcdh_MB001: {
        sex: "male",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_MB00101", "mcdh_MB00102"],
        trashBin: ["ext:梦澈涤花/image/character/MB001.jpg"],
        dieAudios: [],
    },
    mcdh_MB002: {
        sex: "female",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_MB00201", "mcdh_MB00202"],
        trashBin: ["ext:梦澈涤花/image/character/MB002.jpg"],
        dieAudios: [],
    },
    mcdh_MB004: {
        sex: "female",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_MB00401", "mcdh_MB00402"],
        trashBin: ["mcdhCharge:1/4", "ext:梦澈涤花/image/character/MB004.jpg"],
        dieAudios: [],
    },
    mcdh_MB005: {
        sex: "female",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_MB00501", "mcdh_MB00502"],
        trashBin: ["ext:梦澈涤花/image/character/MB005.jpg"],
        dieAudios: [],
    },
    mcdh_MIS2010: {
        sex: "female",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_MIS201001", "mcdh_MIS201002"],
        trashBin: ["mcdhCharge:2/3", "ext:梦澈涤花/image/character/MIS2014.jpg"],
        dieAudios: [],
    },
    mcdh_MIS2013: {
        sex: "female",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_MIS201301", "mcdh_MIS201302"],
        trashBin: ["ext:梦澈涤花/image/character/MIS2013.jpg"],
        dieAudios: [],
    },
    mcdh_MIS2014: {
        sex: "female",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_MIS201401", "mcdh_MIS201402"],
        trashBin: ["mcdhCharge:2/3", "ext:梦澈涤花/image/character/MIS2014.jpg"],
        dieAudios: [],
    },
    mcdh_MIS2016: {
        sex: "female",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_MIS201601", "mcdh_MIS201602"],
        trashBin: ["ext:梦澈涤花/image/character/MIS2016.jpg"],
        dieAudios: [],
    },
    mcdh_MISO008: {
        sex: "female",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_MISO00801", "mcdh_MISO00802"],
        trashBin: ["ext:梦澈涤花/image/character/MISO008.jpg"],
        dieAudios: [],
    },
    mcdh_MISO009: {
        sex: "female",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_MISO00901", "mcdh_MISO00902"],
        trashBin: ["mcdhCharge:2/4", "ext:梦澈涤花/image/character/MISO009.jpg"],
        dieAudios: [],
    },
    mcdh_MISO013: {
        sex: "female",
        hp: 5,
        group: "mcdh_ark",
        skills: ["mcdh_MISO01301", "mcdh_MISO01302", "mcdh_MISO01303"],
        trashBin: ["ext:梦澈涤花/image/character/MISO013.jpg"],
        dieAudios: [],
    },
    mcdh_NL003: {
        sex: "female",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_NL00301"],
        trashBin: ["mcdhCharge:1/3", "ext:梦澈涤花/image/character/NL003.jpg"],
        dieAudios: [],
    },
    mcdh_NL008: {
        sex: "male",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_NL00801", "mcdh_NL00802"],
        trashBin: ["ext:梦澈涤花/image/character/NL008.jpg"],
        dieAudios: [],
    },
    mcdh_PL002: {
        sex: "female",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_PL00201", "mcdh_PL00202"],
        trashBin: ["mcdhCharge:3/3", "ext:梦澈涤花/image/character/PL002.jpg"],
        dieAudios: [],
    },
    mcdh_PL003: {
        sex: "female",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_PL00301", "mcdh_PL00302"],
        trashBin: ["mcdhAmmo:1/5", "ext:梦澈涤花/image/character/PL003.jpg"],
        dieAudios: [],
    },
    mcdh_PS001: {
        sex: "female",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_PS00101", "mcdh_PS00102"],
        trashBin: ["ext:梦澈涤花/image/character/PS001.jpg"],
        dieAudios: [],
    },
    mcdh_PS003: {
        sex: "female",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_PS00301", "mcdh_PS00302", "mcdh_hongsonglin"],
        trashBin: ["ext:梦澈涤花/image/character/PS003.jpg"],
        dieAudios: [],
    },
    mcdh_PS004: {
        sex: "female",
        hp: 3,
        maxHp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_PS00401", "mcdh_hongsonglin"],
        trashBin: ["ext:梦澈涤花/image/character/PS004.jpg"],
        dieAudios: [],
    },
    mcdh_PS005: {
        sex: "female",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_PS00501", "mcdh_hongsonglin"],
        trashBin: ["ext:梦澈涤花/image/character/PS005.jpg"],
        dieAudios: [],
    },
    mcdh_RH004: {
        sex: "female",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_RH00401", "mcdh_RH00402"],
        trashBin: ["mcdhCharge:1/2", "ext:梦澈涤花/image/character/RH004.jpg"],
        dieAudios: [],
    },
    mcdh_RH014: {
        sex: "female",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_RH01401"],
        trashBin: ["ext:梦澈涤花/image/character/RH014.jpg"],
        dieAudios: [],
    },
    mcdh_RH016: {
        sex: "female",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_RH01601", "mcdh_RH01602"],
        trashBin: ["ext:梦澈涤花/image/character/RH016.jpg"],
        dieAudios: [],
    },
    mcdh_RH018: {
        sex: "female",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_RH01801", "mcdh_RH01802"],
        trashBin: ["ext:梦澈涤花/image/character/RH018.jpg"],
        dieAudios: [],
    },
    mcdh_RHA4002: {
        sex: "male",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_RHA400201", "mcdh_RHA400202"],
        trashBin: ["ext:梦澈涤花/image/character/RHA4002.jpg"],
        dieAudios: [],
    },
    mcdh_RHAF003: {
        sex: "female",
        hp: 2,
        maxHp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_RHAF00301", "mcdh_RHAF00302", "mcdh_RHAF00303"],
        trashBin: ["ext:梦澈涤花/image/character/RHAF003.jpg"],
        dieAudios: [],
    },
    mcdh_RHAF004: {
        sex: "male",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_RHAF00401", "mcdh_RHAF00402"],
        trashBin: ["ext:梦澈涤花/image/character/RHAF004.jpg"],
        dieAudios: [],
    },
    mcdh_RHHE001: {
        sex: "female",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_RHHE00101", "mcdh_RHHE00102"],
        trashBin: ["ext:梦澈涤花/image/character/RHHE001.jpg"],
        dieAudios: [],
    },
    mcdh_RHHE002: {
        sex: "female",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_RHHE00201", "mcdh_RHHE00202"],
        trashBin: ["mcdhCharge:3/3", "ext:梦澈涤花/image/character/RHHE002.jpg"],
        dieAudios: [],
    },
    mcdh_RHHE003: {
        sex: "female",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_RHHE00301"],
        trashBin: ["ext:梦澈涤花/image/character/RHHE003.jpg"],
        dieAudios: [],
    },
    mcdh_RHHE004: {
        sex: "female",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_RHHE00401", "mcdh_RHHE00402"],
        trashBin: ["ext:梦澈涤花/image/character/RHHE004.jpg"],
        dieAudios: [],
    },
    mcdh_RHHE005: {
        sex: "female",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_RHHE00501", "mcdh_RHHE00502"],
        trashBin: ["ext:梦澈涤花/image/character/RHHE005.jpg"],
        dieAudios: [],
    },
    mcdh_RHHE006: {
        sex: "female",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_RHHE00601", "mcdh_RHHE00602"],
        trashBin: ["ext:梦澈涤花/image/character/RHHE006.jpg"],
        dieAudios: [],
    },
    mcdh_RHHE007: {
        sex: "female",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_RHHE00701", "mcdh_RHHE00702"],
        trashBin: ["ext:梦澈涤花/image/character/RHHE007.jpg"],
        dieAudios: [],
    },
    mcdh_RHHE008: {
        sex: "female",
        hp: 1,
        maxHp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_RHHE00801", "mcdh_RHHE00802"],
        trashBin: ["ext:梦澈涤花/image/character/RHHE008.jpg"],
        dieAudios: [],
    },
    mcdh_RL003: {
        sex: "female",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_RL00301", "mcdh_RL00302"],
        trashBin: ["ext:梦澈涤花/image/character/RL003.jpg"],
        dieAudios: [],
    },
    mcdh_RL008: {
        sex: "male",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_RL00801", "mcdh_RL00802"],
        trashBin: ["ext:梦澈涤花/image/character/RL008.jpg"],
        dieAudios: [],
    },
    mcdh_RM001: {
        sex: "female",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_RM00101"],
        trashBin: ["ext:梦澈涤花/image/character/RM001.jpg"],
        dieAudios: [],
    },
    mcdh_RM002: {
        sex: "female",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_RM00201", "mcdh_RM00202"],
        trashBin: ["mcdhCharge:2/3", "ext:梦澈涤花/image/character/RM002.jpg"],
        dieAudios: [],
    },
    mcdh_RM003: {
        sex: "male",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_RM00301"],
        trashBin: ["mcdhCharge:1/1", "ext:梦澈涤花/image/character/RM003.jpg"],
        dieAudios: [],
    },
    mcdh_RM004: {
        sex: "male",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_RM00401", "mcdh_RM00402"],
        trashBin: ["ext:梦澈涤花/image/character/RM004.jpg"],
        dieAudios: [],
    },
    mcdh_RM005: {
        sex: "male",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_RM00501", "mcdh_RM00502"],
        trashBin: ["ext:梦澈涤花/image/character/RM005.jpg"],
        dieAudios: [],
    },
    mcdh_RM006: {
        sex: "female",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_RM00601", "mcdh_RM00602"],
        trashBin: ["zhu", "ext:梦澈涤花/image/character/RM006.jpg"],
        dieAudios: [],
    },
    mcdh_RM007: {
        sex: "female",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_RM00701", "mcdh_RM00702"],
        trashBin: ["ext:梦澈涤花/image/character/RM007.jpg"],
        dieAudios: [],
    },
    mcdh_RM008: {
        sex: "double",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_RM00801", "mcdh_RM00802"],
        trashBin: ["ext:梦澈涤花/image/character/RM008.jpg"],
        dieAudios: [],
    },
    mcdh_RM009: {
        sex: "female",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_RM00901", "mcdh_RM00902"],
        trashBin: ["mcdhCharge:1/3", "ext:梦澈涤花/image/character/RM009.jpg"],
        dieAudios: [],
    },
    mcdh_RM010: {
        sex: "female",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_RM01001", "mcdh_RM01002"],
        trashBin: ["ext:梦澈涤花/image/character/RM010.jpg"],
        dieAudios: [],
    },
    mcdh_RM011: {
        sex: "male",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_RM01101", "mcdh_RM01102"],
        trashBin: ["ext:梦澈涤花/image/character/RM011.jpg"],
        dieAudios: [],
    },
    mcdh_SN001: {
        sex: "female",
        hp: 2,
        group: "mcdh_ark",
        skills: ["mcdh_SN00101", "mcdh_SN00102"],
        trashBin: ["ext:梦澈涤花/image/character/SN001.jpg"],
        dieAudios: [],
    },
    mcdh_SN005: {
        sex: "female",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_SN00501", "mcdh_SN00502", "mcdh_SN00503"],
        trashBin: ["ext:梦澈涤花/image/character/SN005.jpg"],
        dieAudios: [],
    },
    mcdh_SN008: {
        sex: "male",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_SN00801", "mcdh_SN00802"],
        trashBin: ["ext:梦澈涤花/image/character/SN008.jpg"],
        dieAudios: [],
    },
    mcdh_SN015: {
        sex: "male",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_SN01501", "mcdh_SN01502"],
        trashBin: ["ext:梦澈涤花/image/character/SN015.jpg"],
        dieAudios: [],
    },
    mcdh_SN016: {
        sex: "female",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_SN01601", "mcdh_SN01602"],
        trashBin: ["ext:梦澈涤花/image/character/SN016.jpg"],
        dieAudios: [],
    },
    mcdh_SW002: {
        sex: "female",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_SW00201", "mcdh_SW00202"],
        trashBin: ["ext:梦澈涤花/image/character/SW002.jpg"],
        dieAudios: [],
    },
    mcdh_SW004: {
        sex: "female",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_SW00401"],
        trashBin: ["ext:梦澈涤花/image/character/SW004.jpg"],
        dieAudios: [],
    },
    mcdh_WB001: {
        sex: "female",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_WB00101", "mcdh_WB00102"],
        trashBin: ["mcdhCharge:0/3", "ext:梦澈涤花/image/character/WB001.jpg"],
        dieAudios: [],
    },
    mcdh_WB002: {
        sex: "female",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_WB00201", "mcdh_WB00202"],
        trashBin: ["ext:梦澈涤花/image/character/WB002.jpg"],
        dieAudios: [],
    },
    mcdh_WB003: {
        sex: "male",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_WB00301", "mcdh_WB00302"],
        trashBin: ["ext:梦澈涤花/image/character/WB003.jpg"],
        dieAudios: [],
    },
    mcdh_WB004: {
        sex: "male",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_WB00401", "mcdh_WB00402"],
        trashBin: ["ext:梦澈涤花/image/character/WB004.jpg"],
        dieAudios: [],
    },
    mcdh_WB005: {
        sex: "male",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_WB00501", "mcdh_WB00502"],
        trashBin: ["ext:梦澈涤花/image/character/WB005.jpg"],
        dieAudios: [],
    },
    mcdh_WB006: {
        sex: "female",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_WR00601", "mcdh_WR00602"],
        trashBin: ["ext:梦澈涤花/image/character/WB006.jpg"],
        dieAudios: [],
    },
    mcdh_WR001: {
        sex: "female",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_WR00101"],
        trashBin: ["ext:梦澈涤花/image/character/WR001.jpg"],
        dieAudios: [],
    },
    mcdh_WR002: {
        sex: "male",
        hp: 3,
        maxHp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_WR00201", "mcdh_WR00202"],
        trashBin: ["ext:梦澈涤花/image/character/WR002.jpg"],
        dieAudios: [],
    },
    mcdh_WR003: {
        sex: "female",
        hp: 4,
        group: "mcdh_ark",
        skills: ["mcdh_WR00301", "mcdh_WR00302"],
        trashBin: ["ext:梦澈涤花/image/character/WR003.jpg"],
        dieAudios: [],
    },
    mcdh_WR004: {
        sex: "female",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_WR00402", "mcdh_WR00401"],
        trashBin: ["ext:梦澈涤花/image/character/WR004.jpg"],
        dieAudios: [],
    },
    mcdh_WR005: {
        sex: "male",
        hp: 3,
        group: "mcdh_ark",
        skills: ["mcdh_WR00501", "mcdh_WR00502"],
        trashBin: ["mcdhCharge:0/4", "ext:梦澈涤花/image/character/WR005.jpg"],
        dieAudios: [],
    }
}

for (let i in characters) {
    characters[i].dieAudios.push(`ext:梦澈涤花/audio/die/${i}.mp3`);
}

export default characters;
