/** @type { importCharacterConfig["character"] } */
const character = {

	/*hun_lishimin: ["male", "GXS_hun", 3, ["hun_zhenguan", "hun_tiance", "hun_liujun", "hun_difan"], []],
	hun_hanxin: ["male", "GXS_hun", 3, ["hun_jiangbing", "hun_andu", "hun_shimian", "hun_beishui"], []],
	hx_tanyunxian: ["female", "GXS_min", 3, ["hx_nvyi", "hx_renxin"], ["die:hx_tanyunxian.mp3"]],
	hx_changyuchun: ["male", "GXS_chen", 3, ["hx_cuifeng", "hx_xianjian", "hx_kaiping"], []],
	sp_yingzheng: ["male", "GXS_jun", "3/4", ["sp_bingtun"], []],
	sp_lishimin: ["male", "GXS_chen", "3/4", ["sp_pozhen"], []],
	sp_zhuchongba: ["male", "GXS_min", "3/4", ["sp_lizhi"], []],
	sp_zhaokuangyin: ["male", "GXS_chen", "3/4", ["sp_qianju", "sp_xunlong"], []],
	sp_zhudi: ["male", "GXS_chen", "3/4", ["sp_mingwu"], []],
	hx_gaochanggong: ["male", "GXS_chen", 4, ["hx_shuaiwei", "hx_ruzhen"], []],
	hx_hulvguang: ["male", "GXS_chen", 4, ["hx_shesheng", "hx_luodiao", "hx_luodiaom"], []],
	hx_liutaozhi: ["male", "GXS_chen", 4, ["hx_lasha", "hx_zhanwang"], []],
	hx_liubei: ["male", "GXS_jun", 3, ["hx_jieyi", "hx_rende", "hx_yinu"], []],
	hun_guanyu: ["male", "GXS_hun", 4, ["hun_wuhun", "hun_xiansheng"], []],
	hx_zhangfei: ["male", "GXS_chen", 4, ["hx_xiongmeng"], []],
	hx_jiangwei: ["male", "GXS_chen", 4, ["hx_yancun", "hx_yifajiang"], []],
	hx_sunce: ["male", "GXS_chen", 4, ["hx_zhizheng"], []],
	hx_sunquan: ["male", "GXS_jun", 4, ["hx_zhihengs"], []],
	hx_gaohuan: ["male", "GXS_jun", 4, ["hx_xushi"], []],
	hun_weixiaokuan: ["male", "GXS_hun", "3/3/1", ["hun_qicaiyidu", "hun_qiaozhan", "hun_"], []],
	hun_yangjian: ["male", "GXS_hun", 4, ["hun_ditusui", "hun_gengyi"], []],
	hx_duguqieluo: ["female", "GXS_chen", 3, ["hx_quanyu", "hx_"], []],
	hun_gaojiong: ["male", "GXS_hun", 4, ["hun_wenwu"], []],
	hx_hanqinhu: ["male", "GXS_chen", 4, ["hx_doujiang", "hx_fenfa"], []],
	hx_shiwansui: ["male", "GXS_chen", 4, ["hx_yingbian", "hx_chizhan"], []],
	hx_heruobi: ["male", "GXS_chen", 4, ["hx_pingjiang"], []],
	hx_xiaomeiniang: ["female", "GXS_chen", 3, ["hx_roujiao", "hx_fuping"], []],
	hx_zhangsunsheng: ["male", "GXS_chen", 4, ["hx_yjsd", "hx_"], []],
	hx_yuwenfang: ["female", "GXS_chen", 3, ["hx_fuguo", "hx_yihen"], []],
	hx_zhairang: ["male", "GXS_min", 4, ["hx_kaicangjipin", "hx_"], []],
	hun_lijing: ["male", "GXS_hun", 4, ["hun_junjing", "hun_qizheng"], []],
	hx_liyuanba: ["male", "GXS_chen", 4, ["hx_shenliba"], []],
	hx_yuchigong: ["male", "GXS_chen", 4, ["hx_menshen", "hx_"], []],
	hun_sudingfang: ["male", "GXS_hun", 4, ["hun_slxz", "hun_fuping"], []],
	hx_wangxuance: ["male", "GXS_chen", 4, ["hx_jspj"], []],
	hun_libai: ["male", "GXS_hun", 3, ["hun_chaotuo", "hun_zhexian"], []],
	hun_guoziyi: ["male", "GXS_hun", 4, ["hun_kanluan", "hun_zaizao"], []],
	hx_lishangyin: ["male", "GXS_min", 4, ["hx_juanyong"], []],
	hx_zhangxun: ["male", "GXS_chen", 4, ["hx_kunshou", "jintangx"], []],
	hx_hairui: ["male", "GXS_chen", 3, ["hx_sutan", "hx_sijian"], []],
	hx_fansui: ["male", "GXS_chen", 4, ["hx_yuanjiao", "hx_jingong"], []],
	hun_changyuchun: ["male", "GXS_hun", 4, ["hun_cfxj", "hun_jianyuan", "hun_shenwei"], []],
	hx_liwenzhong: ["male", "GXS_chen", "1/3", ["hx_wujing", "hx_chuoli", "hx_juejingj"], []],
	hx_zhuwenzheng: ["male", "GXS_chen", 4, ["hx_jintang"], []],
	hx_qijiguang: ["male", "GXS_chen", 3, ["hx_jixiao", "hx_lianbing"], []],
	hun_qijiguang: ["male", "GXS_hun", 3, ["hun_liezhen", "hun_guanghan", "hun_zhenhai", "hun_lianbing"], []],
    hun_yingji: ["male", "GXS_hun", "3/4/1", ["hun_tunmie", "hun_xiangye"], []],
	hun_liuyu: ["male", "GXS_hun", 4, ["hun_", "hun_queyue", "hun_"], []],
	hx_liumuzhi: ["male", "GXS_chen", 4, ["hx_tongchou"], []],
	hx_fengtaihou: ["female", "GXS_jun", 3, ["hx_genghua", "hx_juntian"], []],
	hx_panjinlian: ["female", "GXS_min", 3, ["hx_dufu", "hx_yinluan"], []],
	hx_liuchuyu: ["female", "GXS_chen", 3, ["hx_zonghuan", "hx_yihuo"], []],
	hx_zhaofeiyan: ["female", "GXS_chen", 4, ["hx_yubu"], []],
	hx_zhaohede: ["female", "GXS_chen", 3, ["hx_sheshi", "hx_gongmu"], []],
	hx_gexiaoe: ["female", "GXS_chen", 4, ["hx_yaotao"], []],
	mo_erzhurong: ["male", "devil", 4, ["mo_qiongbao", "mo_zhenyu"], []],
	hx_tandaoji: ["male", "GXS_chen", "3/4", ["hx_jice", "hx_yibing"], []],
	hx_chenqingzhi: ["male", "GXS_chen", 3, ["hx_changqu", "hx_zhishen"], []],
	hx_lulingxuan: ["female", "GXS_chen", 3, ["hx_qumei", "hx_jianqiao"], []],
	hx_yuanchonghuan: ["male", "GXS_chen", 3, ["hx_zhenliao", "hx_shijin"], []],
	hx_nuerhachi: ["male", "GXS_jun", 4, ["hx_chuangqi", "hx_luyeqing"], []],
	hun_xuanye: ["male", "GXS_hun", "3/4", ["hun_pingfan", "hun_qiangang", "hun_nanxun"], []],
	hx_hongchengchou: ["male", "GXS_chen", 4, ["hx_chouyin", "hx_fanfuqing"], []],
	hun_hongli: ["male", "GXS_hun", 4, ["hun_shiquanqing", "hun_wenziyu"], []],
	hx_fukangan: ["male", "GXS_chen", 4, ["hx_jiayong", "hx_gongjian"], []],
	hx_cixi: ["female", "GXS_jun", 4, ["hx_xuanzhan", "hx_jiyuy"], []],
	hx_songyu: ["male", "GXS_chen", 3, ["hx_cibian", "hx_beiqiu"], []],
	hun_sudongpo: ["male", "GXS_hun", "3/4", ["hun_dfb", "hun_quancai"], []],
	hun_liqingzhao: ["female", "GXS_hun", 4, ["hun_qingli", "hun_dushu"], []],
	hx_zhushuzhen: ["female", "GXS_min", 3, ["hx_qingwan", "hx_duanchang"], []],
	hx_liurushi: ["female", "GXS_min", 3, ["hx_jiangyun"], []],
	hx_chenping: ["male", "GXS_chen", 4, ["hx_liuqi", "hx_zuolong"], []],
	hx_sanghongyang: ["male", "GXS_chen", 4, ["hx_licai"], []],
	hx_wangzhaojun: ["female", "GXS_chen", 3, ["hx_heqin", "hx_luoyan", "hx_luoyanm"], []],
	hun_lvzhi: ["female", "GXS_hun", 3, ["hun_yuyou", "hun_jianqie", "hun_zhensha"], []],
	hx_dengsui: ["female", "GXS_jun", 4, ["hx_nvjun", "hx_hexi"], []],
	hun_liuxiu: ["male", "GXS_hun", 3, ["hun_yanyun", "hun_gwzx", "hun_xingyun"], []],
	hx_yinlihua: ["female", "GXS_chen", 4, ["hx_qiande", "hx_guanglie"], []],
	hx_wangmang: ["male", "GXS_jun", 4, ["hx_qiangong", "sanjiu_hongli", "hx_tggz"], []],
	hx_mayuan: ["male", "GXS_chen", 4, ["hx_fubo", "hx_rongma"], []],
	hx_diwulun: ["male", "GXS_chen", 4, ["hx_shanzheng", "hx_qiaozhi"], []],
	hx_banchao: ["male", "GXS_chen", 4, ["hx_toubicongrong"], []],
	hx_mengguang: ["female", "GXS_min", 4, ["hx_yugong", "hx_juanqimei"], []],
	hx_zhangheng: ["male", "GXS_chen", 4, ["hx_didong", "hx_huntian"], []],
	hun_wangmeng: ["male", "GXS_hun", 3, ["hun_yunlue", "hun_wangzuo", "hun_jindao"], []],
	hun_murongke: ["male", "GXS_hun", "3/4", ["hun_xuhuai", "hun_yiai"], []],
	hun_murongchui: ["male", "GXS_hun", "3/4", ["hun_quanzhi", "hun_fuyan"], []],
	hx_xiean: ["male", "GXS_chen", 4, ["hx_dszaiqi", "hx_qingdan"], []],
	hun_tuobatao: ["male", "GXS_hun", 3, ["hun_weifu", "hun_ytwl", "hun_baojie"], []],
	hun_cuihao: ["male", "GXS_hun", 3, ["hun_jltr", "hun_yuanlue"], []],
	hun_zhangbin: ["male", "GXS_hun", 3, ["hun_jwxf", "hun_dingce"], []],
	hun_zhudi: ["male", "GXS_hun", 3, ["hun_shanzhan", "hun_jingnan", "hun_yongle"], []],
	hx_zhuyunwen: ["male", "GXS_jun", 4, ["hx_xuefanzhu"], []],
	hx_wangwenqing: ["male", "GXS_min", 4, ["hx_leijing"], []],
	hx_xiayuanji: ["male", "GXS_chen", 4, ["hx_lilicai", "hx_cheru"], []],
	hx_zhuqizhen: ["male", "GXS_jun", 3, ["hx_beishou", "hx_fubibao"], []],
	hx_yuqian: ["male", "GXS_chen", 3, ["hx_tiku", "hx_"], []],
	hx_zhangsanfeng: ["male", "GXS_min", 4, ["hx_wudang", "hx_taiji"], []],
	hun_wangyangming: ["male", "GXS_hun", 3, ["hun_zhengxin", "hun_wudao", "hun_gongxin"], []],
	hx_qiuying: ["male", "GXS_min", 4, ["hx_linmo"], []],
	hx_xuerengui: ["male", "GXS_chen", 4, ["hx_sanjian", "hx_zhongyong"], []],
	hx_fanlihua: ["female", "GXS_chen", 4, ["hx_weining"], []],
	hun_libi: ["male", "GXS_hun", 4, ["hun_quanyu", "hx_baiyi", "hx_fangyuan"], []],
	hx_linlingsu: ["male", "GXS_min", 4, ["hx_yilei", "hx_huozhong"], []],
	hx_wanzhener: ["female", "GXS_chen", 3, ["hx_xiangshou", "hx_duchong"], []],
	hx_sangchong: ["male", "GXS_min", 3, ["hx_nvzhuang", "hx_"], []],
	hx_qieyinyue: ["female", "GXS_chen", 3, ["hx_candu", "hx_"], []],
	hx_ruji: ["female", "GXS_chen", 3, ["hx_qiefu", "hx_baoen"], []],
	hun_yingzheng: ["male", "GXS_hun", "3/4", ["hun_tongyu", "hun_tianming", "hun_jiquan"], []],
	hx_lisi: ["male", "GXS_chen", 4, ["hx_mingfa", "hx_quanshe"], []],
	hx_huhai: ["male", "GXS_jun", 4, ["hx_quede"], []],
	mo_zhaogao: ["male", "devil", 4, ["mo_zhiluweima"], []],
	hun_baiqi: ["male", "GXS_hun", "3/4", ["hun_jianmie", "hun_shashen", "hun_donghe", "hun_donghe1"], []],
	hun_limu: ["male", "GXS_hun", 4, ["hun_qichen", "hun_yuyu"], []],
	hun_wangjian: ["male", "GXS_hun", 4, ["hun_jianmiew", "hun_lianpow"], []],
	hun_lianpo: ["male", "GXS_hun", 4, ["jd_xianmie", "hun_yuwu"], []],
	hun_tiemuzhen: ["male", "GXS_hun", 4, ["hun_zhanshen", "hun_tianjiao", "hun_canglang"], []],
	hx_tuolei: ["male", "GXS_jun", 4, ["hx_fengxi", "hx_zhengge"], []],
	hun_hubilie: ["male", "GXS_hun", 5, ["hun_qishe", "hun_duwu", "hun_xuechan"], []],
	mo_zyz: ["male", "devil", 3, ["mo_zyz_gzq", "mo_zyz_gjl"], []],
	hun_zhangjuzheng: ["male", "GXS_hun", 3, ["zhangjuzheng_gx", "zhangjuzheng_sz"], []],
	hx_suqinzhangyi: ["male", "GXS_chen", 3, ["hx_zongheng", "hx_waijiao"], []],
	hun_xuda: ["male", "GXS_hun", 4, ["hun_quzhu", "hun_wuning"], []],
	hun_zhuyuanzhang: ["male", "GXS_hun", 3, ["hun_qiming", "hun_tianzong", "hun_buyi"], []],
	hx_guoxing: ["male", "GXS_chen", 4, ["hx_jiehuo"], []],
	hx_liubowen: ["male", "GXS_chen", 4, ["hx_weiwo", "hx_shensuan"], []],
	hx_shenwansan: ["male", "GXS_min", 3, ["hx_jubao", "hx_duiyi"], []],
	hx_wangzhi: ["male", "GXS_min", 3, ["hx_fenghang", "hx_"], []],
	hx_luoguanzhong: ["male", "GXS_min", 4, ["hx_shuhan", "hx_yanyi"], []],
	hx_yanshi: ["male", "GXS_min", 4, ["hx_shenji", "hx_bailian", "hx_qianjibian"], []],
	hx_tuohuantiemuer: ["male", "GXS_jun", 3, ["hx_zhenjue", "hx_shunbi"], []],
	hx_zhuwen: ["male", "GXS_jun", 4, ["hx_weiya", "hx_fcdx"], []],
	hx_mingyuzhen: ["male", "GXS_jun", 3, ["hx_miaoshi", "hx_shenshi"], []],
	hx_wangyanzhang: ["male", "GXS_chen", 3, ["hx_qiangshen", "hx_chitu", "hx_xiaozhan"], []],
	hx_gaosiji: ["male", "GXS_chen", 4, ["hx_yinchi"], []],
	hx_yangxingmi: ["male", "GXS_jun", 3, ["hx_huimou", "hx_binghuo"], []],
	hx_licunxiao: ["male", "GXS_chen", 4, ["hx_xiaoyong"], []],
	hx_huangdaopo: ["female", "GXS_min", 4, ["hx_qiehua", "hx_cuosha"], []],
	hx_jiajing: ["male", "GXS_jun", 2, ["hx_xuanxiu", "hx_anyu"], []],
	hx_yanshifan: ["male", "GXS_chen", 4, ["hx_nongquan"], []],
	hx_lubing: ["male", "GXS_chen", 3, ["hx_yexing", "hx_jinyi"], []],
	hx_gehong: ["male", "GXS_min", "4/5", ["hx_liandan", "hx_chongxu"], []],
	hun_huangdi: ["male", "GXS_hun", 4, ["hun_tianyan", "hun_diji", "hun_renqi"], []],
	hx_suirenshi: ["male", "GXS_jun", 4, ["hx_xinhuozu"], []],
	hx_sizhu: ["male", "GXS_jun", 4, ["hx_chuangjia"], []],
	hun_dayuxia: ["male", "GXS_hun", 4, ["hun_shuchuan", "hun_dingxu"], []],
	hun_chengtang: ["male", "GXS_hun", 4, ["hun_xuanshou", "hun_renzhan"], []],
	hun_yiyin: ["male", "GXS_hun", 4, ["hun_geren", "hun_dishiyi", "hun_zaowang"], []],
	hx_fuhao: ["female", "GXS_chen", 4, ["hx_xuanfeng"], []],
	hx_daji: ["female", "GXS_chen", 3, ["hx_huozhu", "hx_huoyinm"], []],
	hun_jichang: ["male", "GXS_hun", 4, ["hx_shengde", "hx_lixian", "hx_xianzhi"], []],
	hun_jifa: ["male", "GXS_hun", 3, ["hun_fazhou", "hun_fenfeng", "hun_dingzhi"], []],
	hun_jiangziya: ["male", "GXS_hun", 4, ["hun_taolue", "hun_kuitian", "hun_fengshen"], []],
	hx_zhouyouwang: ["male", "GXS_jun", 3, ["hx_fengluan", "hx_fenghuo"], []],	
	hx_jiezhou: ["male", "GXS_jun", 4, ["hx_jiuchi", "hx_wudao", "hx_houlian"], []],
	hx_bigan: ["male", "GXS_chen", 4, ["hx_zuojun", "hx_zhonglie"], []],
	hx_gongzhiqi: ["male", "GXS_chen", 4, ["hx_mingjian", "hx_lianju", "hx_lianju_lost"], []],
	hx_dubo: ["male", "GXS_chen", 3, ["hx_hunsuo"], []],
	hx_chuzhuangwang: ["male", "GXS_jun", 4, ["hun_yimingjingren", "hun_wendingzhongyuan"], []],
	hx_fansheng: ["female", "GXS_chen", 3, ["hx_jianlie", "hx_jinxian"], []],
	hun_guanzhong: ["male", "GXS_hun", 4, ["hun_zunrang", "hun_kuanghe", "hun_"], []],
	hx_baoshuya: ["male", "GXS_chen", 4, ["hx_chaluan", "hx_jianxian"], []],
	hun_laozi: ["male", "GXS_hun", 4, ["hun_dao", "hun_liuguang", "hun_daoyinyang"], []],
	hun_kongzi: ["male", "GXS_hun", 4, ["hun_cjws", "hun_shengxun"], []],
	hun_zhuangzi: ["male", "GXS_hun", 4, ["hun_mengdie", "hun_", "hun_"], []],
	hun_mozi: ["male", "GXS_hun", 3, ["hun_feigongmo", "hun_jianai"], []],
	hx_luban: ["male", "GXS_min", 3, ["hx_jibianlb", "hx_shugong", "hx_shengong", "hx_shengonglb"], []],
	hx_duanmuci: ["male", "GXS_min", 4, ["hx_lianhuandm"], []],
	hx_ouyezi: ["male", "GXS_min", 4, ["hx_zhujian", "hx_cuihuo", "hx_jianzhong", "hx_jiandun"], []],
	hun_guiguzi: ["male", "GXS_hun", 4, ["hun_baihe", "hun_zongheng", "hun_dongguan"], []],
	hx_zhengxiu: ["female", "GXS_chen", 4, ["hx_mihuo", "hx_yxgc"], []],
	hx_xiaji: ["female", "GXS_chen", 4, ["hx_caibu"], []],
	hx_fengxiaolian: ["female", "GXS_chen", 3, ["hx_yutihengchen", "hx_bingjiyugu", "hx_chenniaihe", "hx_yutihengcheny"], []],
	hx_panyunu: ["female", "GXS_chen", 3, ["hx_shenglian"], []],
	hun_fanli: ["male", "GXS_hun", 4, ["hun_shangdao", "hun_chaoran"], []],
	hx_goujian: ["male", "GXS_jun", 4, ["hx_wxcd", "hx_yjtw"], []],
	hx_tiandan: ["male", "GXS_chen", 4, ["hx_huozhen", "hx_linwei"], []],
	hx_zhaogou: ["male", "GXS_jun", 4, ["hx_pianan"], []],
	hx_wanyanzongwang: ["male", "GXS_chen", 3, ["hx_jichijin", "hx_ruifeng", "hx_lianshi"], []],
	hx_wanyanliang: ["male", "GXS_jun", 4, ["hx_lifajin"], []],
	hun_yuefei: ["male", "GXS_hun", 4, ["hun_wumu", "hun_nufa"], []],
	hun_menggong: ["male", "GXS_hun", 4, ["hun_fanlim", "hun_jishi"], []],
	hx_diqing: ["male", "GXS_chen", 4, ["hx_yannie", "hx_zhuansuo"], []],
	hx_shaoyong: ["male", "GXS_min", 3, ["hx_meiyi", "hx_xianggua"], []],
	hx_yuyunwen: ["male", "GXS_chen", 4, ["hx_qijue", "hx_wanlan"], []],
	hx_yangzaixing: ["male", "GXS_chen", 4, ["hx_xuezhan"], []],
	hx_lianghongyu: ["female", "GXS_chen", 4, ["hx_nvhao", "hx_guwu"], []],
	hx_zhuxi: ["male", "GXS_chen", 4, ["hun_clmy", "hx_liqi"], []],
	hx_zhendexiu: ["male", "GXS_chen", 4, ["hx_zhengxue", "hx_liyi"], []],
	hx_wentianxiang: ["male", "GXS_chen", 4, ["hx_danxin", "hx_"], []],
	hx_wusong: ["male", "GXS_min", 4, ["hx_zuijiu"], []],
	hx_qinjiushao: ["male", "GXS_chen", 4, ["hx_jiuzhang"], []],
	hx_liye: ["male", "GXS_min", 4, ["hx_tianyuan"], []],
	hx_yanghui: ["male", "GXS_chen", 4, ["hx_sanjiao"], []],
	hx_maxiuying: ["female", "GXS_chen", 3, ["hx_quanjie", "hx_cide"], []],
	hx_bisheng: ["male", "GXS_min", 4, ["hx_huoyin", "hx_faming"], []],
	hx_xumiaoyun: ["female", "GXS_chen", 3, ["hx_zhenjing", "hx_hdjz"], []],
	hun_miyue: ["female", "GXS_hun", 4, ["hun_yousha", "hun_quanyi", "hun_huangting"], []],
	hun_shangyang: ["male", "GXS_hun", 3, ["hun_biange", "hun_fuguo", "hun_faling"], []],
	hx_zhaozhen: ["male", "GXS_jun", 4, ["hx_renzong", "hx_renshu", "hx_"], []],
	hun_fanzhongyan: ["male", "GXS_hun", "3/5", ["hun_xinzheng", "hun_kudu", "hun_youle"], []],
	hx_wanganshi: ["male", "GXS_chen", 4, ["hx_xinfa"], []],
	hun_baozheng: ["male", "GXS_hun", 3, ["hun_mingcha", "hun_qingzheng", "hun_shenduan"], []],
	hx_songci: ["male", "GXS_chen", 4, ["hx_quzheng", "hx_quzhengsc"], []],
	hun_bianque: ["male", "GXS_hun", "1/1", ["hun_wangse", "hun_"], []],
	hx_bianque: ["male", "GXS_min", 4, ["hx_bamai", "hx_jishi"], []],
	hx_yishuo: ["female", "GXS_chen", 3, ["hx_zhenjiu", "hx_xuanhujishi", "hx_caiyao"], []],
	hx_baogu: ["female", "GXS_min", 3, ["hx_xingyi", "hx_"], []],
	hx_zhangxiaoniangzi: ["female", "GXS_min", 3, ["hx_zhiyu", "hx_yifang"], []],
	hx_wanmizhai: ["male", "GXS_min", 4, ["hx_xushi", "hx_huisheng"], []],
	hun_sunbin: ["male", "GXS_hun", 4, ["hun_fuji", "hx_yinshi"], []],
	hun_wuqi: ["male", "GXS_hun", 3, ["hun_baizhanwu", "hun_baizhan", "hun_xiuzheng", "hun_yidao"], []],
	hun_sunwu: ["male", "GXS_hun", 3, ["hun_guidao", "hun_bingsheng", "hun_"], []],
	hx_wuzixu: ["male", "GXS_chen", 4, ["hx_haolie", "hx_fuchou", "hx_bianshi"], []],
	hx_tianrangju: ["male", "GXS_chen", 4, ["hx_fuzhong", "hx_weidi"], []],
	hx_yxsr: ["male", "GXS_chen", 4, ["hx_", "", "hx_moran", "hx_"], []],
	shen_wenzhong: ["male", "shen", 3, ["shen_wulei", "shen_leihu", "shen_yinglei"], []],
	hx_daiding: ["male", "GXS_min", 4, ["XS_danli", "魂穿", "xiubo", "Europa_shenyou", "x_xuezu", "reacgn_niegaoshentie"], []],
	hx_liuyan: ["male", "GXS_chen", 4, ["hx_yangmin", "hx_maoqian"], []],
	hx_jingke: ["male", "GXS_min", 4, ["hx_tuqiongbixian"], []],
	hx_niezheng: ["male", "GXS_min", 3, ["hx_bhgr"], []],
	hx_nieyinniang: ["female", "GXS_min", 3, ["hx_tuci", "hx_yingxi", "hx_zhuixi"], []],
	hx_chunyutiying: ["female", "GXS_min", 4, ["hx_xiaoxing"], []],
	hx_xiedaoyun: ["female", "GXS_min", "3/4", ["hx_yongxu", "hx_bianxuan"], []],
	hx_sxfr: ["female", "GXS_chen", 4, ["hx_pingjing"], []],
	hx_wsfr: ["female", "GXS_chen", 4, ["hx_pingzhi"], []],
	hx_diaochan: ["female", "GXS_min", 3, ["hx_biyue", "hx_meixin"], []],
	hx_lilongji: ["male", "GXS_jun", 3, ["hx_kaiyuantang", "hx_yanjitang"], []],
	hx_yangyuhuan: ["female", "GXS_chen", 3, ["hx_xiuhua", "hx_huaqing"], []],
	hx_guoguofuren: ["female", "GXS_chen", 3, ["hx_xionghu", "hx_yishim"], []],
	hx_gaoyanggongzhu: ["female", "GXS_chen", 4, ["hx_jiaojin", "hx_qige"], []],
	hx_panan: ["male", "GXS_min", 4, ["hx_tanlang", "hx_zgyc"], []],
	hx_weijie: ["male", "GXS_min", 4, ["hx_xiuyi"], []],
	hun_wuzetian: ["female", "GXS_hun", 4, ["hun_zzhy", "hun_fycg", "hun_ndwl"], []],
	hx_xuyougong: ["male", "GXS_chen", 4, ["hx_zhizhengxu"], []],
	hx_liurengui: ["male", "GXS_chen", 3, ["hx_jinchao", "hx_yanchi", "hx_suojiang"], []],
	hx_zhouxing: ["male", "GXS_chen", 3, ["hx_hengshi", "hx_yangji"], []],
	hx_xuetao: ["female", "GXS_min", 4, ["hx_huanhua", "hx_shijian"], []],
	hx_huineng: ["male", "GXS_min", 4, ["hx_wuchen", "hx_dunwu", "hx_bore"], []],
	mo_houjing: ["male", "devil", 3, ["mo_xiongluan", "mo_"], []],
	mo_anlushan: ["male", "devil", 3, ["mo_jiaoxia", "mo_fnlc"], []],
	hx_fengdao: ["male", "GXS_chen", 4, ["hx_kurong", "hx_shiyun"], []],
	hun_guorong: ["male", "GXS_hun", 3, ["hun_yingfa", "hun_tuzhi"], []],
	hun_zhaokuangyin: ["male", "GXS_hun", 4, ["hun_shiquan", "hun_changquan", "hun_hpjs", "hun_hhpjs"], []],
	hx_zhaoguangyi: ["male", "GXS_jun", 3, ["hx_yiwu", "hx_"], []],
	hun_xiaochuo: ["female", "GXS_hun", 3, ["hun_yanhui", "hun_chanmeng"], []],
	hx_liyu: ["male", "GXS_jun", 3, ["hx_luohua", "hx_"], []],
	hun_zhaopu: ["male", "GXS_hun", 4, ["hun_tuce", "hun_"], []],
	hx_caobin: ["male", "GXS_chen", 4, ["hx_zhizhan"], []],
	hx_zhaomengfu: ["male", "GXS_chen", 4, ["hx_lintie"], []],
	hx_yelvhongji: ["male", "GXS_jun", 4, ["hx_zhize"], []],
	hx_yanzhaowang: ["male", "GXS_jun", 4, ["hx_zhaoxian", "hx_"], []],
	hx_juxin: ["male", "GXS_chen", 4, ["hx_biantu"], []],
	hx_zhouyafu: ["male", "GXS_chen", 4, ["hx_shujunzhou"], []],
	hun_liuche: ["male", "GXS_hun", 3, ["hun_xionglve", "hun_kaituo", "hun_hanhun"], []],
	hun_liubang: ["male", "GXS_hun", 4, ["hun_yuhun", "hun_quanlve", "hun_hanfeng"], []],
	hun_xiangyu: ["male", "GXS_hun", 4, ["hun_ywcz", "hun_poshi", "hun_bawang"], []],
	hx_yuji: ["female", "GXS_chen", 4, ["hx_beige", "hx_"], []],
	hun_zhangliang: ["male", "GXS_hun", 4, ["hun_yunchou", "hun_zuoce", "hun_mousheng"], []],
	hun_xiaohe: ["male", "GXS_hun", 4, ["hun_yuefa", "hun_yuefaa", "hun_zhenfu"], []],
	hx_fankuai: ["male", "GXS_chen", 4, ["hx_jiujia"], []],
	hx_liyiji: ["male", "GXS_chen", 4, ["hx_kuangbian"], []],
	hx_chaocuo: ["male", "GXS_chen", 4, ["hx_qiaoke"], []],
	hx_dongfangshuo: ["male", "GXS_chen", 3, ["hx_caibian", "hx_huaji"], []],
	hun_huoqubing: ["male", "GXS_hun", 3, ["hun_quchi", "hun_quchim", "hun_shanji", "hun_juemu"], []],
	hun_huoguang: ["male", "GXS_hun", 4, ["hun_duquan", "hun_zuohan", "hun_feili"], []],
	hx_zhaochongguo: ["male", "GXS_chen", 4, ["hx_tuntian"], []],
	hx_liangji: ["male", "GXS_chen", "3/4", ["hx_bahu", "hx_weibing"], []],
	hx_weirui: ["male", "GXS_chen", "3/4", ["hx_zhitui", "hx_jili"], []],
	shen_mzsj: ["male", "shen", 4, ["shen_tianyi"], []],
	shen_jbsj: ["male", "shen", 4, ["shen_sulei"], []],
	shen_lgsj: ["female", "shen", 4, ["shen_yinghuo", "shen_lihuo"], []],
	shen_zmsj: ["male", "shen", 4, ["shen_xuanming"], []],
	shen_tangsanzang: ["male", "shen", 4, ["shen_", "shen_xinjing"], []],
	shen_zhubajie: ["male", "shen", 4, ["shen_jingtan"], []],
	shen_nezha: ["male", "shen", 4, ["hx_", "hx_", "shen_chongsu"], []],
	shen_huozhurong: ["male", "shen", 3, ["shen_huozheng", "shen_"], []],
	shen_zhongkui: ["male", "shen", 3, ["shen_panguan", "shen_"], []],
	hun_sunzhongshan: ["male", "GXS_hun", 4, ["hun_sanmin", "hun_geming", "hun_gonghe"], []],
	hun_maozedong: ["male", "GXS_hun", "4/5", ["hun_daoshi", "hun_gongchan", "hun_hongxing", "hun_xinghuo"], []],
	hun_zhude: ["male", "GXS_hun", 4, ["hun_junhun"], []],
	hx_liue: ["female", "GXS_jun", "3/4", ["hx_linchao", "hx_mingsu"], []],
	hun_yaoguangxiao: ["male", "GXS_hun", "3/4", ["hun_an", "hun_bian"], []],
	hx_yaoguangxiao: ["male", "GXS_chen", 4, ["hx_taoxu"], []],
	hun_liguangbi: ["male", "GXS_hun", "3/4", ["hx_zhijun", "hx_choulue"], []],
	hx_xieziran: ["female", "GXS_min", 4, ["hx_bigu", "hx_feisheng"], []],
	hun_caocao: ["male", "GXS_hun", "3/4", ["hun_jianxiong", "hun_xieling"], []],
	hx_caozhi: ["male", "GXS_chen", 3, ["hx_luoyingcao", "hx_jiushicao", "hx_shenghua"], []],
	hx_caoren: ["male", "GXS_chen", 4, ["hx_jushou"], []],
	hx_guojia: ["male", "GXS_chen", 3, ["hx_dinglue"], []],
	hun_zhouyu: ["male", "GXS_hun", 4, ["hun_chiyan", "hun_juemou"], []],
	hx_daxiaoqiao: ["female", "GXS_min", 3, ["hx_liuliqiao", "hx_guoseqiao"], []],
	hun_luxun: ["male", "GXS_hun", 4, ["hun_hsly", "hun_"], []],
	hx_taoyuanming: ["male", "GXS_min", "3/4", ["hx_yinyi", "hx_yinyim"], []],
	hx_zhuyingtai: ["female", "GXS_min", 3, ["hx_huadie", "hx_tongchuang"], []],
	hun_simayi: ["male", "GXS_hun", "3/4", ["hun_xuanxiao", "hun_yinxiong"], []],
	hx_jiananfeng: ["female", "GXS_jun", 3, ["ffhunjuegai", "ffduiyuangai"], []],
	hx_shikuang: ["male", "GXS_chen", 4, ["hx_yuebu"], []],
	hx_boya: ["male", "GXS_min", 3, ["hx_gaoshan", "hx_liushui", "hx_zhiyin"], []],
	hx_suzhipo: ["female", "GXS_min", 3, ["hx_cidiao", "hx_dansheng"], []],
	hx_zhuzaiyu: ["male", "GXS_chen", 4, ["hx_cigui", "hx_yuelv"], []],
	hx_zhujinzhen: ["male", "GXS_min", 4, ["hx_jumi", "hx_simiao"], []],
	hun_fangdu: ["male", "GXS_hun", 4, ["hun_mouhua", "hun_jueduan"], []],
	hun_yaosong: ["male", "GXS_hun", 4, ["hun_yingbian", "hun_shouzheng"], []],
	sj_niudun: ["male", "GXS_min", 4, ["sj_dinglv", "sj_yinli"], []],
	sj_zhende: ["female", "GXS_chen", 3, ["sj_shengjie", "sj_qishi"], []],
	sj_nandinggeer: ["female", "GXS_min", 4, ["sj_huli", "sj_tianshi"], []],
	sj_lishunchen: ["male", "GXS_chen", 4, ["sj_xunlan"], []],
	sj_jiafeiji: ["female", "GXS_min", 3, ["sj_shouren", "sj_langqie"], []],
    sj_jinzhengen: ["male", "GXS_jun", 4, ["sj_enqing"], []],
	mo_lilinfu: ["male", "devil", 3, ["mo_paiyili", "mo_koumifujian", "mo_tangdangfu"], []],*/
	
	
	//英雄杀【基础篇】
	
	yxs_lishimin: ["male", "GXS_jun", 4, ["yxs_kongju"], []],
	yxs_liubang: ["male", "GXS_jun", 4, ["yxs_yuren"], []],
	yxs_tiemuzhen: ["male", "GXS_jun", 4, ["yxs_qishe", "yxs_qianglue"], []],
	yxs_baosi: ["female", "GXS_chen", 3, ["yxs_zhiyu", "yxs_fenghuo"], []],
	yxs_caocao: ["male", "GXS_jun", 4, ["yxs_jianxiong"], []],
	yxs_chensheng: ["male", "GXS_jun", 4, ["yxs_qiyi"], []],
	yxs_chenyuanyuan: ["female", "GXS_min", 3, ["yxs_hongyan", "yxs_chuchu"], []],
	yxs_bianque: ["male", "GXS_min", 3, ["yxs_liaoshang", "yxs_huichun"], []],
	yxs_goujian: ["male", "GXS_jun", 3, ["yxs_yinren", "yxs_tuqiang"], []],
	yxs_hanxin: ["male", "GXS_chen", 3, ["yxs_bingxian", "yxs_gongxin"], []],
	yxs_guanyu: ["male", "GXS_chen", 4, ["yxs_budao", "yxs_danqi"], []],
	yxs_lishishi: ["female", "GXS_min", 3, ["yxs_manwu", "yxs_hongzhuang"], []],
	yxs_huamulan: ["female", "GXS_chen", 3, ["yxs_mili", "yxs_yizhuang"], []],
	yxs_luzhishen: ["male", "GXS_min", 4, ["yxs_dili", "yxs_kuangchan"], []],
	yxs_likui: ["male", "GXS_min", 4, ["yxs_fuchou"], []],
	yxs_liubowen: ["male", "GXS_chen", 3, ["yxs_zhanbu", "yxs_guiyin"], []],
	yxs_murong: ["female", "GXS_jun", 4, ["yxs_diehun"], []],
	yxs_qinqiong: ["male", "GXS_chen", 4, ["yxs_menshen", "yxs_fanji"], []],
	yxs_shangyang: ["male", "GXS_chen", 3, ["yxs_bianfa", "yxs_fajia"], []],
	yxs_shiqian: ["male", "GXS_min", 3, ["yxs_shentou", "yxs_feizei", "yxs_qingmin"], []],
	yxs_renhuanzhi: ["male", "GXS_min", 4, ["yxs_xiadan"], []],
	yxs_songjiang: ["male", "GXS_min", 4, ["yxs_shucai"], []],
	yxs_wusong: ["male", "GXS_min", 4, ["yxs_zuijiu"], []],
	yxs_tantaiming: ["male", "GXS_chen", 4, ["yxs_aojian"], []],
	yxs_wuzetian: ["female", "GXS_jun", 4, ["yxs_nvquan", "yxs_qiandu"], []],
	yxs_xiangyu: ["male", "GXS_jun", 4, ["yxs_bawang"], []],
	yxs_yangyanzhao: ["male", "GXS_chen", 4, ["yxs_tianlang"], []],
	yxs_wuzetian: ["female", "GXS_jun", 4, ["yxs_nvquan", "yxs_qiandu"], []],
	yxs_xishi: ["female", "GXS_min", 3, ["yxs_meihuo", "yxs_chenyu"], []],
	yxs_yingzheng: ["male", "GXS_jun", 4, ["yxs_jiquan"], []],
	yxs_yuji: ["female", "GXS_chen", 3, ["yxs_sheshen", "yxs_juebie"], []],
	yxs_zhaofeiyan: ["female", "GXS_chen", 3, ["yxs_yubu", "yxs_qingying"], []],
	yxs_yuefei: ["male", "GXS_chen", 4, ["yxs_wumu"], []],
	yxs_zhaokuangyin: ["male", "GXS_jun", 4, ["yxs_shiquan"], []],
	
		//英雄杀【青龙之章】
		
	yxs_zhugeliang: ["male", "GXS_chen", 3, ["yxs_miaoji", "yxs_dongcha"], []],
	yxs_zhuyuanzhang: ["male", "GXS_jun", 4, ["yxs_qiangyun"], []],
	yxs_lianpo: ["male", "GXS_chen", 4, ["yxs_fujing"], []],
	yxs_luban: ["male", "GXS_min", 3, ["yxs_guifu", "yxs_shengong"], []],
	yxs_chengyaojin: ["male", "GXS_chen", 4, ["yxs_sanbanfu"], []],
	yxs_jingke: ["male", "GXS_min", 3, ["yxs_cike", "yxs_juesha"], []],
	yxs_panan: ["male", "GXS_min", 4, ["yxs_zirong", "yxs_daowang"], []],
	yxs_xiaoqiao: ["female", "GXS_min", 3, ["yxs_guose", "yxs_tianxiang"], []],
	yxs_lvzhi: ["female", "GXS_jun", 4, ["yxs_xumou", "yxs_zhensha"], []],
	yxs_lizicheng: ["male", "GXS_jun", 4, ["yxs_lumang", "yxs_yongchuang"], []],
	
	      //英雄杀【白虎之章】
		
	yxs_liuche: ["male", "GXS_jun", 3, ["yxs_weiqiang", "yxs_ruide"], []],
	yxs_kangxi: ["male", "GXS_jun", 4, ["yxs_xuefan", "yxs_mingcha"], []],
	yxs_liyu: ["male", "GXS_jun", 3, ["yxs_chaotuo", "yxs_houzhu"], []],
	yxs_linchong: ["male", "GXS_min", 4, ["yxs_baotou"], []],
	yxs_zhangfei: ["male", "GXS_chen", 4, ["yxs_doushen"], []],
	yxs_sunwu: ["male", "GXS_chen", 3, ["yxs_kanpo", "yxs_bingsheng"], []],
	yxs_mozi: ["male", "GXS_chen", 3, ["yxs_feigong", "yxs_jianai"], []],
	yxs_yangyuhuan: ["female", "GXS_chen", 3, ["yxs_xiuhua", "yxs_fengyan"], []],
	yxs_diaochan: ["female", "GXS_min", 3, ["yxs_lijian", "yxs_biyue"], []],
	yxs_libai: ["male", "GXS_min", 3, ["yxs_miaobi", "yxs_zhexian"], []],
	
	    //英雄杀【朱雀之章】
	    
	yxs_yangguang: ["male", "GXS_jun", 3, ["yxs_yaoyi", "yxs_jujian", "yxs_shiqin"], []],
	yxs_zhaoyong: ["male", "GXS_jun", 3, ["yxs_hufu", "yxs_hanbei"], []],
	yxs_wangzhaojun: ["female", "GXS_min", 3, ["yxs_heqin", "yxs_luoyan"], []],
	yxs_muguiying: ["female", "GXS_min", 4, ["yxs_yinglie", "yxs_jiaozhen", "yxs_guashuai"], []],
	yxs_muguiyingchen: ["female", "GXS_chen", 4, ["yxs_pozhen", "yxs_ciyin"], ["unseen"]],
	yxs_tangbohu: ["male", "GXS_min", 3, ["yxs_luobi", "yxs_fengliu"], []],
	yxs_luocheng: ["male", "GXS_chen", 4, ["yxs_hanqiang", "yxs_piaoqi"], []],
	yxs_bole: ["male", "GXS_min", 3, ["yxs_huiyan", "yxs_xiangma"], []],
	yxs_guiguzi: ["male", "GXS_min", 3, ["yxs_zongheng", "yxs_yinju", "yxs_qianmou"], []],
	yxs_baiqi: ["male", "GXS_chen", 4, ["yxs_rentu"], []],
	yxs_sunquan: ["male", "GXS_jun", 4, ["yxs_duizhi", "yxs_zhiheng"], []],
	
	
	    //英雄杀【玄武之章】
	    
	yxs_jifa: ["male", "GXS_jun", 4, ["yxs_taofa"], []],
	yxs_qihuangong: ["male", "GXS_jun", 4, ["yxs_zhiba"], []],
	yxs_wenjiang: ["female", "GXS_chen", 3, ["yxs_zhenglue", "yxs_beide"], []],
	yxs_xuanzang: ["male", "GXS_min", 3, ["yxs_jiasha", "yxs_pudu"], []],
	yxs_baozheng: ["male", "GXS_chen", 3, ["yxs_pingyuan", "yxs_shenduan"], []],
	yxs_kongzi: ["male", "GXS_min", 3, ["yxs_shouli", "yxs_chongru"], []],
	yxs_liqingzhao: ["female", "GXS_min", 3, ["yxs_yuci", "yxs_shangli"], []],
	yxs_liguang: ["male", "GXS_chen", 4, ["yxs_shanshe", "yxs_feijiang"], []],
	yxs_dongfangshuo: ["male", "GXS_chen", 3, ["yxs_cifu", "yxs_zhisheng"], []],
	yxs_liubei: ["male", "GXS_jun", 3, ["yxs_rende", "yxs_jieyi"], []],
	
	     //英雄杀【斗魂篇】//
	     
		    yxshunsunquan:['male','GXS_hun',4,['yxsjn_zhongmou','yxsjn_lianyin',"yxszw_hunsunquan"],[]],
            yxshunxiaoqiao:['female','GXS_hun',3,['yxsjn_chujia','yxsjn_zhijie',"yxszw_hunxiaoqiao"],[]],
            yxshunyangyuhuan:['female','GXS_hun',3,['yxsjn_yuxian','yxsjn_nichang',"yxszw_hunyangyuhuan"],[]],
            yxshunzhangfei:['male','GXS_hun',4,['yxsjn_tiaoxin','yxsjn_nuhe','yxszw_hunzhangfei'],[]],
            yxshunsunwu:['male','GXS_hun',3,['yxsjn_guidao','yxsjn_zhijun','yxsjn_swxiongcai',"yxszw_hunsunwu"],[]],
            yxshuncaocao:['male','GXS_hun',4,['yxsjn_zhulu','yxsjn_xieling','yxszw_huncaocao'],[]],
            yxshunguiguzi:['male','GXS_hun',3,['yxsjn_baihe','yxsjn_yinyang','yxsjn_xiushen',"yxszw_hunguiguzi"],[]],
            yxshundirenjie:['male','GXS_hun',3,['yxsjn_hunshenduan','yxsjn_zhaoxue','yxsjn_jianneng','yxszw_hundirenjie'],[]],
            yxshunliubang:['male','GXS_hun',4,['yxsjn_renwang','yxsjn_shiwei','yxszw_hunliubang'],[]],
            yxshunmozi:['male','GXS_hun',3,['yxsjn_jieyong','yxsjn_shangtong','yxsjn_feiming','yxszw_hunmozi'],[]],
            yxshunluocheng:['male','GXS_hun',4,['yxsjn_yinqiang','yxsjn_huima','yxsjn_shaobao','yxszw_hunluocheng'],[]],
			yxshunxiangyu:['male','GXS_hun',4,['yxsjn_hongmen','yxsjn_guixiong','yxsjn_pofu',"yxszw_hunxiangyu"],[]],
		    yxshundiaochan:['female','GXS_hun',3,['yxsjn_fengyi','yxsjn_wange','yxsjn_kuixin',"yxszw_hundiaochan"],[]],
            yxshunlinchong:['male','GXS_hun',4,['yxsjn_zhongwu','yxsjn_xiedao',"yxszw_hunlinchong"],[]],
	
	        //英雄杀【世界篇】
	        
	GXS_aijiyanhou: ["female", "GXS_jun", 3, ["GXS_seyou", "GXS_sheshi"], []],
	GXS_zhende: ["female", "GXS_chen", 3, ["GXS_retongfu", "GXS_shengnv"], []],
	GXS_zhitianxinchang: ["male", "GXS_chen", 4, ["GXS_dybuwu", "GXS_dyyewang"], []],
	GXS_fuermosi: ["male", "GXS_min", 3, ["GXS_yanyi", "GXS_jiean"], []],
	GXS_mingcheng: ["female", "GXS_chen", 3, ["GXS_tiewan", "GXS_chajue"], []],
	GXS_napolun: ["male", "GXS_jun", 4, ["GXS_tongling", "GXS_fanpu"], []],
	GXS_kaisa: ["male", "GXS_jun", 4, ["GXS_ducai"], []],
	GXS_sbdks: ["male", "GXS_min", 4, ["GXS_dyjiasuo", "GXS_dyzaofan"], []],
	yxs_nandinggeer: ["female", "GXS_min", 3, ["yxs_huli", "yxs_yixin", "yxs_xianqu"], []],
	GXS_chenluobinhan: ["male", "GXS_chen", 4, ["GXS_sheshu", "GXS_duobi"], ["unseen"]],
	GXS_luobinhan: ["male", "GXS_min", 4, ["GXS_xiadao", "GXS_lzhangyi", "GXS_lingdao"], []],
	
	yxs_zzdirenjie: ["male", "GXS_chen", 3, ["yxsjn_shentan", "yxsjn_jujian"], []],
	yxs_zzhangsanfeng: ["male", "GXS_min", 4, ["yxsjn_budao", "yxsjn_taiji"], []],
	
	
	         //英雄传奇
	      
	        yxstaipinggongzhu:["female","GXS_chen",3,["yxsjn_xiudao","yxsjn_zhenguo",'yxszw_taipinggongzhu'], []],
		    yxszhaoyun:["male","GXS_chen",4,["yxsjn_tujin_old","yxsjn_longdan_old",'yxszw_zhaoyun'], []],
			yxswusangui: ['male', 'GXS_jun', 4, ['yxsjn_touji','yxszw_wusangui'], []],
			yxsyuwenhuaji: ['male', 'GXS_chen', 3, ['yxsjn_cuanquan','yxsjn_longluo','yxszw_yuwenhuaji'], []],
			yxsxiaotaihou: ['female', 'GXS_jun', 4, ['yxsjn_qinzheng', 'yxsjn_juma','yxszw_xiaotaihou'], []],
			yxslanlingwang: ['male', 'GXS_chen', 4, ['yxsjn_guimian', 'yxsjn_yuxue','yxszw_lanlingwang'], []],
			yxszhurong: ['female', 'GXS_chen', 4, ['yxsjn_huoshen','yxszw_zhurong'], []],
			yxsmenghuo: ['male', 'GXS_jun', 4, ['yxsjn_mhzongheng', 'yxsjn_nanman','yxszw_menghuo'], []],
			yxsshangzhou: ['male', 'GXS_jun', 3, ['yxsjn_wudao', 'yxsjn_zhongpan','yxszw_shangzhou'], []],
			yxsdaji: ['female', 'GXS_chen', 3, ['yxsjn_shixin', 'yxsjn_meiguo','yxszw_daji'], []],
			yxsliji: ['female', 'GXS_chen', 3, ['yxsjn_dihui', 'yxsjn_mimou','yxszw_liji'], []],
			yxsgaoqiu: ['male', 'GXS_chen', 4, ['yxsjn_duji', 'yxsjn_zhuanquan','yxszw_gaoqiu'], []],
			yxsxiaozhuang: ['female', 'GXS_jun', 3, ['yxsjn_youshui', 'yxsjn_tianming','yxszw_xiaozhuang'], []],
			yxsaobai: ['male', 'GXS_chen', 4, ['yxsjn_weiwo', 'yxsjn_duzun','yxszw_aobai'], []],
			yxsmoxi: ['female', 'GXS_chen', 3, ['yxsjn_liebo', 'yxsjn_yaoji','yxszw_moxi'], []],
			yxsxiajie: ['male', 'GXS_jun', 4, ['yxsjn_jiabeng', 'yxsjn_shenli','yxszw_xiajie'], []],
			yxsweizhongxian: ['male', 'GXS_chen', 3, ['yxsjn_zhuxin', 'yxsjn_lianhuan','yxszw_weizhongxian'], []],
			GXS_dymiyue: ['female', 'GXS_chen', 3, ['GXS_dyyoumie', 'GXS_dyzhangzheng'], []],
			yxsnvwa: ['female', 'GXS_jun', 4, ['yxsjn_zaoren', 'yxsjn_wahuang', 'yxsjn_shenyou','yxszw_nvwa'], []],
			yxsnianshou: ['male', 'GXS_min', 4, ['yxsjn_shiren', 'yxsjn_bianpao','yxszw_nianshou'], []],
			yxswenjiang: ['female', 'GXS_chen', 3, ['yxsjn_zhenglve', 'yxsjn_beide','yxszw_wenjiang'], []],
			yxs_qinglong: ['male', 'shen', 6, ['chuanqi_longnu'], []],
			yxs_baihu: ['male', 'shen', "3/3/3", ['chuanqi_huying'], []],
			yxs_zhuque: ['female', 'shen', 6, ['ychuanqi_fengyan'], []],
			yxs_xuanwu: ['male', 'shen', "3/3/3", ['ychuanqi_xuanming'], []],
			
			
			//英雄杀小程序
			
			'GXS_goujian': ["male", "GXS_jun", 3, ["GXS_yinren", "GXS_tuqiang"], []],
            yxs_shennong: ["male", "GXS_jun", 4, ["yxs_bianyao", "yxs_huode"], []],
            yxs_wxxiaoshimei: ["female", "GXS_min", 3, ["yxs_qingdian", "yxs_zhounian"], []],
            yxs_gaoshi: ["male", "GXS_chen", 3, ["yxs_zhengshu", "yxs_taicen"], []],
            yxs_wangwei: ["male", "GXS_chen", 3, ["yxs_siyi", "yxs_leichen"], []],
            'GXS_yangyanzhao': ['male', 'GXS_chen', 4, ['GXS_tianlang', 'GXS_yinqiang'], []],
            'GXS_vxdirenjie': ['male', 'GXS_chen', 4, ['GXS_jujian', 'GXS_shentan'], []],
            'GXS_quyuan': ['male', 'GXS_chen', 3, ['GXS_shangguo', 'GXS_beifu'], []],
            'GXS_weiqing': ['male', 'GXS_chen', 4, ['GXS_huguo', 'GXS_qiantui'], []],
            'GXS_vxzhangliang': ['male', 'GXS_chen', 3, ['GXS_mouci', 'GXS_xuzhi'], []],
            'GXS_luobinwang': ['male', 'GXS_chen', 3, ['GXS_yongwu', 'GXS_xiwen'], []],
            'GXS_simaxiangru': ['male', 'GXS_min', 3, ['GXS_qiuhuang', 'GXS_jianlie'], []],
            'GXS_vxlibai': ['male', 'GXS_min', 3, ['GXS_jiuxian', 'GXS_yaoyue'], []],
            'GXS_dufu': ['male', 'GXS_min', 3, ['GXS_shisheng', 'GXS_beimin'], []],
            'GXS_tantaiming': ['male', 'GXS_chen', 4, ['GXS_aojian', 'GXS_xinmo'], []],
            'GXS_renhuanzhi': ['male', 'GXS_min', 4, ['GXS_xiadan', 'GXS_tianyi'], []],
            'GXS_vxmurong': ['female', 'GXS_jun', 4, ['GXS_vxdiehun'], []],
            'GXS_yuantiangang': ['male', 'GXS_chen', 3, ['GXS_xiangshu', 'GXS_quji'], []],
            "GXS_vxliuche": ["male", "GXS_jun", 4, ["GXS_xiongcai", "GXS_zhengfa"], []],
             "GXS_vxzhaoyong": ["male", "GXS_jun", 4, ["GXS_hufu", "GXS_hanbei"], []],
             "GXS_yuwenhuaji": ["male", "GXS_chen", 4, ["GXS_cuanni", "GXS_jiandi"], []],
             "GXS_zhangliao": ["male", "GXS_chen", 3, ["GXS_liaodi", "GXS_lianxi"], []],
             "GXS_vxsunwu": ["male", "GXS_chen", 4, ["GXS_vxbingsheng", "GXS_qiji"], []],
             "yxs_wxxishi": ["male", "GXS_min", 3, ["yxs_wxmeihuo", "yxs_wxchengyu"], []],
             "GXS_vxbole": ["male", "GXS_min", 4, ["GXS_shicai", "GXS_xiangma"], []],
             "GXS_guanyu": ["male", "GXS_chen", 4, ["GXS_wusheng", "GXS_danqi", "GXS_budao"], []],
             "GXS_vxlvbu": ["male", "GXS_jun", 4, ["GXS_wushuang", "GXS_fangtian", "GXS_shenji"], []],
             "GXS_vxbaiqi": ["male", "GXS_chen", 4, ["GXS_jianmie", "GXS_zhuiji"], []],
             "GXS_vxyangguang": ["male", "GXS_jun", 3, ['GXS_ygjujian', "GXS_yaoyi"], []],
             "GXS_jiangshang": ["male", "GXS_chen", 3, ["GXS_dudiao", "GXS_taolve"], []],
             "GXS_vxlanlingwang": ["male", "GXS_jun", 3, ["GXS_pojun", "GXS_zhubei", "GXS_yushuai"], []],
             "GXS_vxsunquan": ["male", "GXS_jun", 4, ["GXS_zhiheng", "GXS_beixi"], []],
             "GXS_xiaohe": ["male", "GXS_chen", 3, ["GXS_yuefa", "GXS_yunliang"], []],
             "GXS_vxzhaoyun": ["male", "GXS_chen", 3, ["GXS_guyong", "GXS_huzhu"], []],
             "GXS_vxlinchong": ["male", "GXS_min", 4, ["GXS_baotou"], []],
             "GXS_lizicheng": ["male", "GXS_jun", 4, ["GXS_yongchuang", "GXS_lumang"], []],
             "GXS_liguang": ["male", "GXS_chen", 4, ["GXS_feijiang", "GXS_shanshe"], []],
             "GXS_dayu": ["male", "GXS_jun", 4, ["GXS_zhuding", "GXS_zhishui"], []],
             "GXS_vxkongzi": ["male", "GXS_min", 3, ["GXS_chongru", "GXS_shouli"], []],
             "yxs_wxyanying": ["male", "GXS_chen", 3, ["yxs_shanjian", "yxs_shichu"], []],
             "GXS_mengtian": ["male", "GXS_chen", 3, ["GXS_zhengzhao", "GXS_haoling"], []],
             "yxs_wxlidingguo": ["male", "GXS_chen", 4, ["yxs_shewei", "yxs_zuyuan"], []],
             "yxs_wxgaoyingxiang": ["male", "GXS_jun", 4, ["yxs_haoju"], []],
             'GXS_liqingzhao': ['female', 'GXS_min', 3, ['GXS_yuci', 'GXS_shangli'], []],
             'GXS_vxlvzhi': ['female', 'GXS_jun', 4, ['GXS_vxxumou', 'GXS_vxzhensha'], []],
             'GXS_daji': ['female', 'GXS_chen', 3, ['GXS_vxshixin', 'GXS_vxmeiguo'], []],
             'GXS_vxwenjiang': ['female', 'GXS_chen', 3, ['GXS_zhenglve', 'GXS_beide'], []],
             'GXS_vxzhurong': ['female', 'GXS_chen', 3, ['GXS_huoshen', 'GXS_manhou'], []],
             'GXS_vxwangzhaojun': ['female', 'GXS_chen', 3, ['GXS_luoyan', 'GXS_heqin'], []],
             'GXS_vxxiaotaihou': ['female', 'GXS_jun', 4, ['GXS_juma', 'GXS_qinzheng'], []],
             'GXS_yangyuhuan': ['female', 'GXS_chen', 3, ['GXS_xiuhua', 'GXS_fengyan'], []],
             'GXS_vxhuamulan': ['female', 'GXS_chen', 3, ['GXS_remili', 'GXS_reyizhuang'], []],
             'GXS_vxmuguiying': ['female', 'GXS_chen', 3, ['GXS_jiaozhen', 'GXS_yinglie'], []],
             'GXS_zhuowenjun': ['female', 'GXS_min', 3, ['GXS_qinxin', 'GXS_xiangshou'], []],
             'GXS_shangguanwaner': ['female', 'GXS_chen', 3, ['GXS_nvxiang', 'GXS_qicai'], []],
             'GXS_zhangsunhuanghou': ['female', 'GXS_chen', 3, ['GXS_jiandie', 'GXS_xianzhu'], []],
             'GXS_vxwuzetian': ['female', 'GXS_jun', 3, ['GXS_nvhuang', 'GXS_qiandu'], []],
             'GXS_weizifu': ['female', 'GXS_chen', 4, ['GXS_zhenlie', 'GXS_jiade'], []],
             'GXS_moxi': ['female', 'GXS_chen', 3, ['GXS_liebo', 'GXS_yaoji'], []],
             'GXS_miyue': ['female', 'GXS_chen', 3, ['GXS_youmie', 'GXS_zhangzheng'], []],
             "GXS_vxdiaochan": ["female", "GXS_min", 3, ["GXS_vxlijian", "GXS_vxbiyue"], []],
             "GXS_liji": ["female", "GXS_chen", 4, ["GXS_dihui", "GXS_mimou"], []],
             'GXS_vxlikui': ['male', 'GXS_min', 4, ['GXS_fuchou', 'GXS_vxgangyi'], []],
             'GXS_xiangyu': ['male', 'GXS_jun', 4, ['GXS_bawang', 'GXS_pofu'], []],
             'GXS_jifa': ['male', 'GXS_jun', 4, ['GXS_taofa', 'GXS_zhubao'], []],
             'GXS_huoqubing': ['male', 'GXS_chen', 3, ['GXS_tiandu', 'GXS_wangshen'], []],
             'GXS_vxhanxin': ['male', 'GXS_chen', 3, ['GXS_bingxian', 'GXS_gongxin'], []],
             'GXS_vxguiguzi': ['male', 'GXS_chen', 3, ['GXS_zongheng', 'GXS_yinju'], []],
             'GXS_qihuangong': ['male', 'GXS_jun', 4, ['GXS_zhiba', 'GXS_bazhu'], []],
             'GXS_baozheng': ['male', 'GXS_chen', 3, ['GXS_pingyuan', 'GXS_shenduan'], []],
             'GXS_jingke': ['male', 'GXS_min', 4, ['GXS_juesha', 'GXS_cike'], []],
             'GXS_liubowen': ['male', 'GXS_chen', 3, ['GXS_zhanbu', 'GXS_guiyin'], []],
             'GXS_lishimin': ['male', 'GXS_jun', 4, ['GXS_kongju', 'GXS_shenjun'], []],
             'GXS_yingzheng': ['male', 'GXS_jun', 4, ['GXS_jiquan'], []],
             'GXS_tiemuzhen': ['male', 'GXS_jun', 4, ['GXS_vxqianglve', 'vxqishe'], []],
             'GXS_vxmenghuo': ['male', 'GXS_jun', 4, ['GXS_qizong', 'GXS_manwang'], []],
             'GXS_vxmozi': ['male', 'GXS_min', 3, ['GXS_feigong', 'GXS_jianai'], []],
             'GXS_vxzhangfei': ['male', 'GXS_chen', 4, ['GXS_shenyong', 'GXS_podi'], []],
             'GXS_vxluocheng': ['male', 'GXS_chen', 4, ['GXS_biaoqi', 'GXS_hanqiang'], []],
             'GXS_luzhishen': ['male', 'GXS_min', 4, ['GXS_kuangchan', 'GXS_dili'], []],
             'GXS_vxkangxi': ['male', 'GXS_jun', 3, ['GXS_mingcha', 'GXS_xuefan'], []],
             'GXS_xuxiake': ['male', 'GXS_chen', 4, ['GXS_chuyou', 'GXS_suyuan'], []],
             'GXS_vxchengyaojin': ['male', 'GXS_chen', 4, ['GXS_qixi', 'GXS_kuangfu'], []],
             'GXS_shangzhou': ['male', 'GXS_jun', 4, ['GXS_zhongpan', 'GXS_wudao'], []],
             'GXS_wusong': ['male', 'GXS_min', 4, ['GXS_zuijiu', 'GXS_xingzhe'], []],
             'GXS_zhaokuangyin': ['male', 'GXS_jun', 4, ['GXS_shiquan', 'GXS_lixian'], []],
             'GXS_vxpanan': ['male', 'GXS_min', 4, ['GXS_qingmu', 'GXS_daowang'], []],
             'GXS_zhouyu': ['male', 'GXS_chen', 3, ['GXS_liance', 'GXS_nishi'], []],
             'GXS_vxlianpochar': ['male', 'GXS_chen', 5, ['GXS_lianpo', 'GXS_fujing'], []],
             'GXS_simayi': ['male', 'GXS_chen', 3, ['GXS_langgu', 'GXS_zhuolve'], []],
             'GXS_fanli': ['male', 'GXS_min', 3, ['GXS_quancai', 'GXS_shiyong'], []],
             'GXS_rebianque': ['male', 'GXS_min', 3, ['GXS_rehuichun', 'GXS_reliaoshang', 'GXS_yide'], []],
             'GXS_vxxiaoqiao': ['female', 'GXS_min', 3, ['GXS_vxtianxiang', 'GXS_guose'], []],
             yxs_wxliubei: ['male', 'GXS_jun', 4, ['yxs_wxjieyi', 'yxs_wxrende'], []],
             'GXS_vxmachao': ['male', 'GXS_chen', 4, ['GXS_qingji', 'GXS_xiaoji'], []],
             'GXS_yuenv': ['female', 'GXS_min', 4, ['GXS_jiandao', 'GXS_shoujian', 'GXS_jianji'], []],
             'GXS_xunzi': ['male', 'GXS_min', 3, ['GXS_quyong', 'GXS_quanxue'], []],
             'GXS_zhangyi': ['male', 'GXS_chen', 3, ['GXS_vxyoushui', 'GXS_lianheng'], []],
             'GXS_lvbuwei': ['male', 'GXS_chen', 3, ['GXS_juqi', 'GXS_zongquan'], []],
             'GXS_wangjian': ['male', 'GXS_chen', 4, ['GXS_hengsao', 'GXS_qingshang'], []],
             'GXS_linxiangru': ['male', 'GXS_chen', 3, ['GXS_guiqu', 'GXS_jianghe'], []],
             "GXS_suqin": ["male", "GXS_chen", 3, ["GXS_hezonga", "GXS_wangji"], []],
             'GXS_fanzeng': ['male', 'GXS_min', 3, ['GXS_qimou', 'GXS_shefu'], []],
             yxs_baijuyi: ["male", "GXS_chen", 3, ["yxs_shiwang", "yxs_jianji"], []],
             yxs_sushi: ["male", "GXS_chen", 3, ["yxs_liuzhe", "yxs_laotao"], []],
             yxs_xinqiji: ["male", "GXS_chen", 3, ["yxs_yiduan", "yxs_fuxian"], []],
             'GXS_vxchange': ['female', 'GXS_chen', 3, ['GXS_yuexian', 'GXS_vxbenyue'], []],
             'GXS_vxzhubajie': ['male', 'GXS_chen', 3, ['GXS_vxtianpeng', 'GXS_dunan'], []],
             'GXS_vxxiaozhuang': ['female', 'GXS_chen', 3, ['GXS_fuzheng', 'GXS_zhaosheng'], []],
             "GXS_vxcaiwenji": ['female', 'GXS_min', 3, ['GXS_qiangzhi', "GXS_guihan"], []],
             'GXS_vxtangbohu': ['male', 'GXS_min', 3, ['GXS_vxluobi', 'GXS_vxfengliu'], []],
             'GXS_vxwusangui': ['male', 'GXS_chen', 3, ['GXS_moufan', 'GXS_fanwang'], []],
             'GXS_mengchang': ['male', 'GXS_chen', 3, ['GXS_nashi', 'GXS_chiyuan'], []],
             'GXS_niezheng': ['male', 'GXS_min', 3, ['GXS_nimang', 'GXS_kuangxi'], []],
             'GXS_maosui': ['male', 'GXS_chen', 3, ['GXS_zijian', 'GXS_tuoying'], []],
             'GXS_zhuzhishan': ['male', 'GXS_min', 3, ['GXS_caoshu', 'GXS_linmo'], []],
             'GXS_lianghongyu': ['female', 'GXS_chen', 3, ['GXS_zhigu', 'GXS_qingzui'], []],
             'GXS_vxtaipinggongzhu': ['female', 'GXS_chen', 4, ['GXS_yuzhu', 'GXS_rangquan'], []],
             'GXS_guanzhong': ['male', 'GXS_chen', 3, ['GXS_kuanghe', 'GXS_zunwang'], []],
             'GXS_fusu': ['male', 'GXS_jun', 3, ['GXS_zhijian', 'GXS_ruxue'], []],
             'GXS_zhudi': ['male', 'GXS_jun', 4, ['GXS_jingnan'], []],
             'GXS_shenwansan': ['male', 'GXS_min', 4, ['GXS_jubao', 'GXS_sancai', 'GXS_mihuo'], []],
             'GXS_wangyangming': ['male', 'GXS_chen', 4, ['GXS_gewu', 'GXS_zhixing'], []],
             'GXS_vxqinliangyu': ['female', 'GXS_chen', 3, ['GXS_yinghui', 'GXS_pingpan'], []],
             "GXS_shesaihua": ["female", "GXS_chen", 4, ["GXS_zhaoqin", "GXS_guashuai"], []],
             "GXS_xiaoshimei": ["female", "GXS_min", 3, ["GXS_guwu", "GXS_qingyingsm"], []],
             "GXS_hairui": ["male", "GXS_chen", 3, ["GXS_zhiqing", "GXS_sutan"], []],
             "GXS_pusongling": ["male", "GXS_min", 3, ["GXS_liaozhai", "GXS_huxian"], []],
             "GXS_wangxizhi": ["male", "GXS_min", 3, ["GXS_rumu", "GXS_shusheng"], []],
             "GXS_gaojianli": ["male", "GXS_min", 3, ["GXS_zhuji", "GXS_lige"], []],
             "GXS_weizheng": ["male", "GXS_chen", 4, ["GXS_jingjian"], []],
             "GXS_zhebie": ["male", "GXS_chen", 4, ["GXS_beishe", "GXS_huixi"], []],
             "GXS_nieyinniang": ["female", "GXS_min", 3, ["GXS_yinni", "GXS_yingxi"], []],
             "GXS_vxhuangdi": ["male", "GXS_jun", 4, ["GXS_wenzu", "GXS_neijing", "GXS_longzheng"], []],
             "GXS_zhuangzhou": ["male", "GXS_min", 3, ["GXS_mengdie", "GXS_xiaoyao"], []],
             "GXS_songci": ["male", "GXS_chen", 4, ["GXS_yangu", "GXS_xiyuan"], []],
             "GXS_gehong": ["male", "GXS_min", 3, ["GXS_liandan", "GXS_yangsheng"], []],
             "GXS_hanshizhong": ["male", "GXS_chen", 4, ["GXS_hengjiang", "GXS_xiejia"], []],
             "GXS_chairong": ["male", "GXS_jun", 4, ["GXS_shitu", "GXS_shenwu"], []],
             "GXS_chengying": ["male", "GXS_min", 3, ["GXS_ligu", "GXS_mouni"], []],
             "yxs_gongsunchujiu": ["male", "GXS_min", 3, ["yxs_xianyi", "yxsjn_gsmouni"], []],
             'GXS_guoziyi': ['male', 'GXS_chen', 4, ['GXS_wenwu', 'GXS_qingguo'], []],
             "GXS_hanfeizi": ["male", "GXS_min", 3, ["GXS_junfa", "yxs_zhudao"], []],
             "GXS_huangchao": ["male", "GXS_jun", 4, ["GXS_fuju"], []],
             "GXS_pingyang": ["female", "GXS_chen", 3, ["GXS_xianfei", "GXS_heqi"], []],
             "GXS_tianji": ["male", "GXS_chen", 3, ["GXS_saima", "GXS_weijiu"], []],
             "GXS_zhaokuo": ["male", "GXS_chen", 4, ["GXS_tanbing", "GXS_tuwei"], []],
             "GXS_zuchongzhi": ["male", "GXS_min", 3, ["GXS_qiuyuan", "GXS_jingsuan"], []],
             "GXS_wanganshi": ["male", "GXS_chen", 3, ["GXS_xinxue", "GXS_qingmiao"], []],
             "GXS_geshuhan": ["male", "GXS_chen", 4, ["GXS_yuguan", "GXS_maojin"], []],
             "GXS_fuxi": ["male", "GXS_jun", 3, ["GXS_bagua", "GXS_zaowu"], []],
             "GXS_zhangzhongjing": ["male", "GXS_min", 3, ["GXS_yujizzj", "GXS_qihan"], []],
             "GXS_wuyong": ["male", "GXS_min", 3, ["GXS_shensuan", "ztjx_tianji"], []],
             "GXS_zuti": ["male", "GXS_chen", 4, ["GXS_jiji", "GXS_fuji", "GXS_zhijiu"], []],
             'GXS_zhouchu': ['male', 'GXS_chen', 4, ['GXS_chuhai', 'GXS_huiguo'], []],
             'GXS_zhangjuzheng': ['male', 'GXS_chen', 3, ['GXS_zhenfang', 'GXS_vxbianfa'], []],
             'GXS_vxhouyi': ['male', 'GXS_chen', 4, ['GXS_vxsheri', 'GXS_jiejian'], []],
             'GXS_yuxuanji': ['female', 'GXS_min', 3, ['GXS_feiqing', 'GXS_zheliu'], []],
	         'GXS_vxlixian': ['male', 'GXS_chen', 4, ['GXS_vxweiya', 'GXS_vxzhenfu'], []],
	         'GXS_vxliugongquan': ['male', 'GXS_chen', 3, ['GXS_vxbizheng', 'xcxyxs_mogu'], []],
	         GXS_vxzouji: ["male", "GXS_chen", 4, ["GXS_vxfengjian"], []],
	         yxs_caogui: ['male', 'GXS_chen', 3, ['yxs_vxlunzhan', 'yxs_vxyuanmou'], []],
	         yxs_lichunfeng: ['male', 'GXS_chen', 4, ['ymingque', 'yytuibei'], []],
	         "GXS_shenkuo": ["male", "GXS_min", 3, ["GXS_boqia", "GXS_bitan"], []],
	         yxs_hongfunv: ["female", "GXS_min", 3, ["jd_hongfu", 'jd_zishu'], []],
			 yxs_vlijing: ["male", "GXS_chen", 4, ["jd_junshen", 'jd_bingshi'], []],
			 yxs_wuqi: ["male", "GXS_chen", 4, ["jd_bingfa", "jd_bingru"], []],
			 yxs_lusu: ["male", "GXS_chen", 3, ["yxs_dimeng", "yxs_geju"], []],
			 yxs_huangzhong: ["male", "GXS_chen", 4, ["yxs_liegong", "yxs_fuli"], []],
             jd_zhuyoujian: ['male', 'GXS_jun', 4, ['jd_qinzheng', 'jd_fudian'], []],
             yxs_zhangxianzhong: ['male', 'GXS_jun', 4, ['jd_jixi', 'jd_xianmie'], []],
             yxs_wxlanlingwang: ['male', 'GXS_chen', 4, ['yxs_wxpojun', 'yxs_wxzhubei', 'yxs_wxyushuai'], []],
             ysunshangxiang: ["female", "GXS_chen", 3, ["yxs_xiaoji", "yxs_jieyin"], []],
             yyxs_yangsu: ['male', 'GXS_chen', 4, ['yyyifu', "yyquanqi"], []],
             yxs_jiaxu: ["male", "GXS_chen", 3, ["xcxyxs_weimu", "ztjx_juegui"], []],
             "yxs_jiangwei": ["male", "GXS_chen", 4, ["yyweifu", "yyjiufa"], []],
             'GXS_vxdianwei': ['male', 'GXS_chen', 4, ['GXS_zhonghu', 'GXS_kuangzhan'], []],
             'yxs_vxqijiguang': ['male', 'GXS_chen', 4, ['xcxyxs_jixiao', 'yxs_vxpingbo'], []],
             'GXS_xzhangqian': ['male', 'GXS_chen', 3, ['GXS_chusai', 'GXS_tongshang'], []],
             yxs_vxxunyu: ['male', 'GXS_chen', 3, ['yxs_quhu', 'yxs_wangzuo'], []],
             yxs_maowenlong: ['male', 'GXS_chen', 3, ['jd_vxxuyi', 'jd_maogong'], []],
             GXS_xlimu: ['male', 'GXS_chen', 4, ['GXS_lianque', 'GXS_polu'], []],
             GXS_xlishizhen: ['male', 'GXS_min', 3, ['GXS_baicao', 'GXS_yaosheng'], []],
             yxs_yanzhaowang: ['male', 'GXS_jun', 4, ['jd_jintai', 'jd_shigu'], []],
             yxs_yueyi: ["male", "GXS_chen", 4, ["yxs_cuilian"], []],
             yxs_vxhuangyueying: ['female', 'GXS_min', 3, ['xcxyxs_huixin', 'xcxyxs_zhifu'], []],
             yxs_vxyuanshoucheng: ['male', 'GXS_min', 3, ['xcxyxs_miaosuan', 'xcxyxs_tianxiang'], []],
             yxs_zhangheng: ['male', 'GXS_chen', 3, ['ydidong', 'yhuntian'], []],
             yxs_wangmang: ['male', 'GXS_jun', 4, ['yxs_cuanhan'], []],
             yxs_jieyougongzhu: ['female', 'GXS_chen', 3, ['yxs_hefan', 'yxs_guining'], []],
             yxs_fengliao: ['female', 'GXS_chen', 3, ['yxs_shuohe', 'yxs_zhaofu'], []],
             yxs_xiangliang: ['male', 'GXS_chen', 4, ['yxs_bule'], []],
             yxs_douying: ['male', 'GXS_chen', 4, ['yxs_pingluan'], []],
             yxs_changhui: ["male", "GXS_chen", 4, ["yxs_jiebing", "yxs_chijie"], []],
             yxs_dongzhongshu: ["male", "GXS_chen", 3, ["yxs_bachu", "yxs_zunru"], []],
             yxs_zhengchenggong: ["male", "GXS_chen", 4, ["yxs_fudao", "yxs_haixian"], []],
             
             
             //英雄杀手游
             
             "yxs_xiaohehan": ["male", "GXS_chen", 3, ["yxs_zhuixian", "yxs_chengbai"], []],
             yxs_liugongquan: ['male', 'GXS_chen', 3, ['xcxyxs_bizheng'], []],
             'GXS_zhubajie': ['male', 'GXS_min', 3, ['GXS_tianpeng', 'GXS_jingtan'], []],
             'GXS_change': ['female', 'GXS_chen', 3, ['ztjx_benyue', 'ylingyao'], []],
             "GXS_dycaiwenji": ['female', 'GXS_min', 3, ['GXS_dyhujia', "GXS_chenqing"], []],
             "GXS_dyzhangyi": ["male", "GXS_chen", 3, ["GXS_shezhan", "GXS_dylianheng"], []],
             'GXS_jqzhangliang': ['male', 'GXS_chen', 3, ['GXS_jqzlweiwo', 'GXS_jqjimou'], []],
             yxs_wudaozi: ['male', 'GXS_chen', 3, ["yhuasheng"], []],
			 yxs_xweizheng: ["male", "GXS_chen", 3, ["yzhijian", 'ykuangzheng'], []],
			 yxs_xlixian: ['male', 'GXS_chen', 3, ['yjiedu'], []],
             yxs_ymachao: ['male', 'GXS_chen', 3, ['yxuehen', "yzhuihun"], []],
			 yxs_simayi: ['male', 'GXS_jun', 4, ['langgu', 'taolue'], []],
			 yxs_xunyu: ["male", "GXS_chen", 3, ["yzhuoxian", "yquhu"], []],
			 yxs_mahuanghou: ["female", "GXS_chen", 3, ["GXS_quanjie", "GXS_shien"], []],
			 yxs_houyi: ['male', 'GXS_min', 3, ["yxs_shenjian", "ysheri"], []],
			 yxs_zhebie: ['male', 'GXS_chen', 4, ["yqishe", "yhuixi"], []],
			 yxs_zhouyu: ['male', 'GXS_chen', 4, ["yfenjin", "yjianshu"], []],
			 GXS_huoguang: ['male', 'GXS_chen', 3, ['GXS_quanxi', 'GXS_quechong'], []],
			 yxs_huoqubing: ['male', 'GXS_chen', 4, ['ybenlei', 'yguanyong'], []],
			 "yxs_weizifu": ["female", "GXS_chen", 3, ["GXS_wugu", "GXS_huojie"], []],
			 yxs_chenajiao: ['female', 'GXS_chen', 3, ["yjinwu", "ychangmen"], []],
			 yxs_fuxi: ['male', 'GXS_jun', 3, ['ybagua', 'ychuangwu'], []],
			 yxs_huangdi: ['male', 'GXS_jun', 4, ["ylongzheng", "ywenzu"], []],
			 yxs_xuhuang: ['male', 'GXS_chen', 4, ["yxs_jieliang", "yxs_shizi"], []],
			 yxs_shangguan: ["female", "GXS_chen", 3, ["yhongmei", "yqicuo"], []],
			 yxs_huangyueying: ["female", "GXS_min", 3, ["yhuixin", "yzhidu"], []],
			 yxs_sunshangxiang: ['female', 'GXS_min', 4, ['ysxiaoji'], []],
			 "yxs_weiqing": ["male", "GXS_chen", 4, ["yxs_shouming",], []],
			 yxs_qiuchuji: ['male', 'GXS_min', 4, ["yzhisha"], []],
			 yxs_xiaoshimei: ['female', 'GXS_min', 4, ['yqingdian', 'yshinian'], []],
			 yxs_xguoziyi: ['male', 'GXS_chen', 4, ["yduorui", "yxs_cangfeng"], []],
			 yxs_dufu: ['male', 'GXS_chen', 3, ["yxs_haoyi", "yxs_jianren"], []],
			 yxs_lichunfengtang: ['male', 'GXS_chen', 4, ["ytianji", "yymingque"], []],
			 yxs_dianwei: ['male', 'GXS_chen', 4, ['ysizhan'], []],
			 yxs_zhangliao: ['male', 'GXS_chen', 4, ['yliangjiang'], []],
			 yxs_dongfangshuosy: ['male', 'GXS_chen', 3, ['ycifu', 'ztjx_zhisheng'], []],
			 yxs_miyue: ['female', 'GXS_jun', 3, ['yyoumie', 'yzhangquan'], []],
			 yxs_xtaipinggongzhu: ['female', 'GXS_jun', 3, ["yanqi", "yluantang"], []],
			 yxs_zhangzhongjinghan: ['male', 'GXS_min', 3, ['yxs_zhangjishi', 'yxs_zhangquhan'], []],
			 GXS_xuanzang: ['male', 'GXS_min', 3, ['ztjx_pudu', 'GXS_jiasha'], []],
			 yxs_xshenwansan: ["male", "GXS_min", 3, ["yhuiheng", "yduiyi"], []],
			 yxs_lvbu: ['male', 'GXS_chen', 4, ['yzhanshen', 'ztjx_xiaoyong'], []],
			 yxs_yuantiangang: ['male', 'GXS_min', 3, ['GXS_tuibei', 'GXS_yandao'], []],
			 yxs_zhougong: ['male', 'GXS_jun', 3, ["yxs_jiemeng", "yxs_yuansheng"], []],
			 yxs_wxwangmang: ['male', 'GXS_jun', 4, ["yxs_gaizhi", "yxs_fuming"], []],
			 yxs_liuyusong: ['male', 'GXS_jun', 4, ["yxs_zefengliu", "yxs_jishiliu"], []],
			 yxs_yuenv: ['female', 'GXS_min', 3, ["yyuenvlijian", "ylunjian"], []],
			 yxs_bswangmang: ['male', 'GXS_jun', 5, ["ynusha++", "ysinue++"], []],
			 yxs_bsdongzhuo: ['male', 'GXS_chen', 5, ["yshiquan++", "ybaonu++"], []],
			 yxs_bsanlushan: ['male', 'GXS_jun', 5, ["ymangsha++", "ytanlan++"], []],
			 yxs_zhangqianhan: ['male', 'GXS_chen', 4, ["yxs_zaokong"], []],
			 yxs_changhuihan: ['male', 'GXS_chen', 4, ['yxs_hanwei', "yxs_zhiyi"], []],
			 yxs_jieyouhan: ['female', 'GXS_chen', 3, ['yxs_zhuangbian', 'yxs_zehui'], []],
			 yxs_cqkongrong: ['male', 'GXS_min', 3, ['yrangli', "yshentong"], []],
			
             
	
	
};

for (let i in character) {
	if (character[i][4]) {
		character[i][4].push(`ext:华夏风云/image/character/${i}.jpg`);
		character[i][4].push(`die:ext:华夏风云/audio/die/${i}.mp3`);
	} else {
		if (!character[i].trashBin) {
			character[i].trashBin = [`ext:华夏风云/image/character/${i}.jpg`];
		} else {
			character[i].trashBin.push(`ext:华夏风云/image/character/${i}.jpg`);
		}
		if (!character[i].dieAudios) {
			character[i].dieAudios = [`ext:华夏风云/audio/die/${i}.mp3`];
		}
	}
}

export default character;
