const characters = {
	jlsgsoul_caocao: ["male", "shen", 3, ["jlsg_guixin", "jlsg_feiying"], ["wei"]],
	jlsgsoul_sunquan: ["male", "shen", 5, ["jlsg_huju"], ["wu"]],
	jlsgsoul_jiaxu: ["male", "shen", 3, ["jlsg_yanmie", "jlsg_shunshi"], ["wei"]],
	jlsgsoul_liubei: ["male", "shen", 4, ["jlsg_junwang", "jlsg_jizhao"], ["shu"]],
	jlsgsoul_zhugeliang: ["male", "shen", 3, ["jlsg_qixing", "jlsg_kuangfeng", "jlsg_dawu"], ["shu", "name:诸葛|亮"]],
	jlsgsoul_sp_zhugeliang: ["male", "shen", 7, ["jlsg_yaozhi", "jlsg_xingyun"], ["shu", "name:诸葛|亮"]],
	jlsgsoul_simayi: ["male", "shen", 3, ["jlsg_jilve", "jlsg_tongtian"], ["wei", "name:司马|懿"]],
	jlsgsoul_sp_simayi: ["male", "shen", 3, ["jlsg_yingshi", "jlsg_langxi", "jlsg_shenyin"], ["wei"]],
	jlsgsoul_luxun: ["male", "shen", 3, ["jlsg_jieyan", "jlsg_fenying"], ["wu"]],
	jlsgsoul_lvbu: ["male", "shen", 5, ["jlsg_kuangbao", "jlsg_wumou", "jlsg_wuqian", "jlsg_shenfen"], ["qun"]],
	jlsgsoul_sp_lvbu: ["male", "shen", 2, ["jlsg_luocha", "jlsg_shajue", "jlsg_guiqu"], ["qun", "fan"]],
	jlsgsoul_guanyu: ["male", "shen", 5, ["jlsg_wushen", "jlsg_suohun"], ["shu"]],
	jlsgsoul_zhaoyun: ["male", "shen", 4, ["jlsg_juejing", "jlsg_longhun"], ["shu"]],
	jlsgsoul_zhangliao: ["male", "shen", 4, ["jlsg_nizhan", "jlsg_cuifeng", "jlsg_weizhen"], ["wei"]],
	jlsgsoul_sp_zhangliao: ["male", "shen", 4, ["jlsg_fengying", "jlsg_zhiti"], ["wei"]],
	jlsgsoul_huangyueying: ["female", "shen", 3, ["jlsg_zhiming", "jlsg_suyin"], ["shu"]],
	jlsgsoul_sp_huangyueying: ["female", "shen", 3, ["jlsg_tiangong", "jlsg_linglong"], ["shu"]],
	jlsgsoul_zhangjiao: ["male", "shen", 3, ["jlsg_dianjie", "jlsg_shendao", "jlsg_leihun"], ["qun", "fan"]],
	jlsgsoul_sp_zhangjiao: ["male", "shen", 3, ["jlsg_yinyang_s", "jlsg_dingming"], ["qun", "fan"]],
	jlsgsoul_lvmeng: ["male", "shen", 3, ["jlsg_shelie", "jlsg_gongxin"], ["wu"]],
	jlsgsoul_guojia: ["male", "shen", 3, ["jlsg_tianqi", "jlsg_tianji"], ["wei"]],
	jlsgsoul_diaochan: ["female", "shen", 3, ["jlsg_tianzi", "jlsg_meixin"], ["qun", "name:null|null"]],
	jlsgsoul_sp_diaochan: ["female", "shen", 1, ["jlsg_lihun", "jlsg_jueshi"], ["qun", "name:null|null"]],
	jlsgsoul_zhangfei: ["male", "shen", 4, ["jlsg_shayi", "jlsg_zhenhun"], ["shu"]],
	jlsgsoul_simahui: ["male", "shen", 3, ["jlsg_zhitian", "jlsg_yinshi"], ["qun", "name:司马|徽"]],
	jlsgsoul_sunshangxiang: ["female", "shen", 3, ["jlsg_xianzhu", "jlsg_liangyuan"], ["shu"]],
	jlsgsoul_ganning: ["male", "shen", 4, ["jlsg_lvezhen", "jlsg_youlong"], ["wu"]],
	jlsgsoul_sp_ganning: ["male", "shen", 4, ["jlsg_jieying", "jlsg_jinlong"], ["wu"]],
	jlsgsoul_xiahoudun: ["male", "shen", 5, ["jlsg_danjing", "jlsg_zhonghun"], ["wei", "name:夏侯|惇"]],
	jlsgsoul_dianwei: ["male", "shen", 5, ["jlsg_zhiji"], ["wei"]],
	jlsgsoul_huatuo: ["male", "shen", 3, ["jlsg_yuanhua", "jlsg_guiyuan", "jlsg_chongsheng"], ["qun"]],
	jlsgsoul_zhouyu: ["male", "shen", 4, ["jlsg_qinyin", "jlsg_yeyan"], ["wu"]],
	jlsgsoul_machao: ["male", "shen", 4, ["jlsg_qianqi", "jlsg_juechen"], ["shu"]],
	jlsgsoul_zhenji: ["female", "shen", 3, ["jlsg_shenfu"], ["wei"]],
	jlsgsoul_huanggai: ["male", "shen", 6, ["jlsg_lianti", "jlsg_yanlie"], ["wu"]],
	jlsgsoul_xuzhu: ["male", "shen", 5, ["jlsg_huchi", "jlsg_xiejia"], ["wei"]],
	jlsgsoul_daqiao: ["female", "shen", 3, ["jlsg_wangyue", "jlsg_luoyan"], ["wu", "name:桥|null"]],
	jlsgsoul_huangzhong: ["male", "shen", 4, ["jlsg_liegong"], ["shu"]],
	jlsgsoul_xiaoqiao: ["female", "shen", 3, ["jlsg_xingwu", "jlsg_chenyu"], ["wu", "name:桥|null"]],
	jlsgsoul_caoren: ["male", "shen", 8, ["jlsg_bamen", "jlsg_gucheng"], ["wei"]],
	jlsgsoul_caopi: ["male", "shen", 3, ["jlsg_chuyuan", "jlsg_dengji"], ["wei"]],
	jlsgsoul_pangtong: ["male", "shen", 3, ["jlsg_qifeng", "jlsg_lunce"], ["shu", "name:庞|统"]],
	jlsgsoul_sp_zhaoyun: ["male", "shen", 1, ["jlsg_qianyuan", "jlsg_hualong"], ["shu", "name:赵|云"]],
	jlsgsoul_sp_sunshangxiang: ["female", "shen", 3, ["jlsg_zhuxing", "jlsg_lingze"], ["wu", "name:孙|null"]],
	jlsgsoul_caiwenji: ["female", "shen", 3, ["jlsg_hanshuang", "jlsg_liluan"], ["qun", "name:蔡|琰"]],
	jlsgsoul_sp_guanyu: ["male", "shen", 4, ["jlsg_zhanyue", "jlsg_fengtian"], ["shu", "name:关|羽"]],
	jlsgsoul_zhoutai: ["male", "shen", 10, ["jlsg_zhanhun"], ["wu", "name:周|泰"]],
	jlsgsoul_sp_zhenji: ["female", "shen", 7, ["jlsg_qixian"], ["wei", "name:甄|null"]],
	jlsgsoul_dongzhuo: ["male", "shen", 5, ["jlsg_taotie", "jlsg_yaoling"], ["qun"]],
	jlsgsoul_sp_zhouyu: ["male", "shen", 4, ["jlsg_qugu", "jlsg_suhui"], ["wu", "name:null|null"]],
	jlsgsoul_zhurong: ["female", "shen", 5, ["jlsg_yanfeng", "jlsg_shenji"], ["qun"]],
	jlsgsoul_sp_daqiao: ["female", "shen", 2, ["jlsg_dieyun", "jlsg_juexian"], ["wu", "name:桥|null"]],
	jlsgsoul_sunce: ["male", "shen", 4, ["jlsg_pinghe", "jlsg_fuhai"], ["wu"]],
};

export default characters;
