import { get } from "noname";

const translates = {
    _nysgsFury_buff: "强化",
    nysgsFury_use: "强化",
    nysgs_destroy: "摧毁",
    nysgs_hidden: "隐匿",
    nysgs_change: "换将",
    nysgs_xuanyun: "眩晕",
    nysgs_xuanyun_info: "你无法使用或打手牌（除【闪】外）。",

    nysgs_icon_point: "拆卸石",
    nysgs_icon_point_info: "拆卸",
    nysgs_fs_tianchen: "天嗔石",
    nysgs_fs_tianchen_info: "怒气上限+1（限镶嵌3个）",
    nysgs_fs_tiannu: "天怒石",
    nysgs_fs_tiannu_info: "初始怒气+1（限镶嵌3个）",
    nysgs_fs_tianyan: "天焰石",
    nysgs_fs_tianyan_info: "体力和体力上限+1（限镶嵌1个）",
    
    nysgs_zf_xushidaifa: "蓄势待发",
    nysgs_zf_xushidaifa_info: "结束阶段，你获得一个额外的摸牌阶段，若你本回合造成伤害小于4点，则你有概率获得一个额外的出牌阶段。",
    nysgs_zf_anzhongtuxi: "暗中突袭",
    nysgs_zf_anzhongtuxi_info: "其他角色的准备阶段，你获得1点怒气，然后你有概率可以随机弃置其2张牌并减少其1点怒气。",
    nysgs_zf_pozhencuijian: "破阵摧坚",
    nysgs_zf_pozhencuijian_info: "当你使用单体非延时锦囊牌指定目标时，你可令此牌效果+2且无法被响应，然后此牌结算结束后，你有概率<noname-poptip poptip = rule_nysgs_cuihui></noname-poptip>其一半手牌（每回合限1次）。",

    nysgs_zf_leitingnuhou: "雷霆怒吼",
    nysgs_zf_leitingnuhou_info: "准备阶段，你可以令一名其他角色弃置其区域内的2张装备牌（优先装备区）然后你有概率令其获得<noname-poptip poptip = nysgs_skill_podan></noname-poptip>直至你换将或回合结束。",
    nysgs_zf_qinlueruhuo: "侵略如火",
    nysgs_zf_qinlueruhuo_info: "每名角色的准备阶段，你摸1张牌。准备阶段，你有概率随机获得以下技能之一直至本回合结束：<noname-poptip poptip = nysgs_jie_xunyu_skill></noname-poptip>、<noname-poptip poptip = nysgs_jie_zhangxingcai_skill></noname-poptip>、<noname-poptip poptip = nysgs_jie_sunquan_skill></noname-poptip>、<noname-poptip poptip = nysgs_jie_diaochan_skill></noname-poptip>。",
    nysgs_zf_budongrushan: "不动如山",
    nysgs_zf_budongrushan_info: "每名角色的结束阶段，你摸1张牌。游戏开始时与结束阶段，你有概率随机获得以下技能之一直至本回合结束：<noname-poptip poptip = nysgs_jie_guojia_skill></noname-poptip>、<noname-poptip poptip = nysgs_jie_liushan_skill></noname-poptip>、<noname-poptip poptip = nysgs_jie_wuguotai_skill></noname-poptip>、<noname-poptip poptip = nysgs_jie_zhangjiao_skill></noname-poptip>。",

    nysgs_zf_feiyangbahu: "飞扬跋扈",
    nysgs_zf_feiyangbahu_info: "判定阶段开始时，若你的判定区有牌，随机将其中1张置入弃牌堆。出牌阶段开始时，你有概率摸2张牌，并且你本阶段出杀次数+1。",
    nysgs_zf_qijirufeng: "其疾如风",
    nysgs_zf_qijirufeng_info: "每名角色的准备阶段，你摸1张牌。准备阶段，你有概率随机获得以下技能之一直至本回合结束：<noname-poptip poptip = nysgs_jie_xunyou_skill></noname-poptip>、<noname-poptip poptip = nysgs_jie_pangtong_skill></noname-poptip>、<noname-poptip poptip = nysgs_jie_ganning_skill></noname-poptip>、<noname-poptip poptip = nysgs_jie_caifuren_skill></noname-poptip>。",
    nysgs_zf_qixurulin: "其徐如林",
    nysgs_zf_qixurulin_info: "每名角色的结束阶段，你摸1张牌。游戏开始时与结束阶段，你有概率随机获得以下技能之一直至本回合结束：<noname-poptip poptip = nysgs_jie_yuejin_skill></noname-poptip>、<noname-poptip poptip = nysgs_jie_xushuSkill></noname-poptip>、<noname-poptip poptip = nysgs_jie_luxun_skill></noname-poptip>、<noname-poptip poptip = nysgs_jie_gongsunzan_skill></noname-poptip>。",

    nysgs_zf_gexuqipao: "割须弃袍",
    nysgs_zf_gexuqipao_info: "你于回合外进入濒死状态时，摸3张牌，然后你有概率可以弃置1张红桃手牌，令本回合其他角色使用黑色伤害牌对你无效（每轮限1次）。",
    nysgs_zf_dandadudou: "单打独斗",
    nysgs_zf_dandadudou_info: "回合开始时，你摸2张牌，然后若场上存活角色数不大于2，你有概率令所有角色本回合造成或/受到伤害+1。",
    nysgs_zf_cuichengbazhai: "摧城拔寨",
    nysgs_zf_cuichengbazhai_info: "当你使用【杀】指定目标时，可以令此牌伤害+1且无法被响应，然后你有概率<noname-poptip poptip = rule_nysgs_cuihui></noname-poptip>其等同于此【杀】伤害值2倍的手牌（每个回合对每名角色限1次）。",

    nysgs_zf_longzhenghudou: "龙争虎斗",
    nysgs_zf_longzhenghudou_info: "你拼点时亮出的装备牌点数视为K，然后拼点结算后，你有概率令其本回合无法使用或打出黑色牌且受到伤害后无法获得怒气。",
    nysgs_zf_yanxingjunfa: "严刑峻法",
    nysgs_zf_yanxingjunfa_info: "你令其他角色进入濒死状态时，你获得1点怒气，然后你有概率可以令其选择一项：1.翻面；2.失去1点怒气且下次受到伤害+1。",
    nysgs_zf_libingmoma: "厉兵秣马",
    nysgs_zf_libingmoma_info: "每轮开始时，你从牌堆或弃牌堆中随机获得X张装备牌，然后你有概率令本轮其他角色计算与你的距离+X（X为场上存活角色数-1）。",

    nysgs_zf_lvedigongcheng: "掠地攻城",
    nysgs_zf_lvedigongcheng_info: "准备阶段，你可以对一名其他角色造成1-3点随机伤害，然后你有概率令其随机交给你X张手牌，其每少交1张，便受到你造成的1点伤害（X为你的攻击范围+1）。",
    nysgs_zf_bainiaochaofeng: "百鸟朝凤",
    nysgs_zf_bainiaochaofeng_info: "出牌阶段开始时，你可以视为强化使用1张非延时锦囊牌，此牌结算后，你有概率令所有其他角色交给你1张牌名相同的手牌，否则其流失2点体力。",
    nysgs_zf_yihuajiemu: "移花接木",
    nysgs_zf_yihuajiemu_info: "其他角色的出牌阶段开始时，你摸1张牌，然后你有概率可以展示至多5张手牌并随机弃置其等量的手牌。若如此做，其获得你展示的牌，你摸2张牌。",

    nysgs_zf_yetandiying: "夜探敌营",
    nysgs_zf_yetandiying_info: "其他角色的准备阶段，你可以观看其手牌并获得其中1张，然后你有概率令其本回合对你造成大于1点的伤害时，数值-1。",
    nysgs_zf_bixujishi: "避虚击实",
    nysgs_zf_bixujishi_info: "你体力上限变化时，摸3张牌，然后你有概率获得以下效果直至你回合结束：增加，你造成伤害+1；减少，你受到其他角色造成的流失体力-1。",
    nysgs_zf_gubenguiyuan: "固本归元",
    nysgs_zf_gubenguiyuan_info: "你受到伤害后，你摸4张牌，然后你有一定概率令你本回合造成伤害或回复体力时，数值+1（每个回合限1次）。",

    nysgs_zf_zhengzhengrishang: "蒸蒸日上",
    nysgs_zf_zhengzhengrishang_info: "准备阶段，你摸X张牌，然后你有概率令你本回合使用红色牌无次数限制，使用黑色牌无距离限制（X初始为1，每轮结束时+1）。",
    nysgs_zf_tongqiangtiebi: "铜墙铁壁",
    nysgs_zf_tongqiangtiebi_info: "每个回合开始时，你获得1点护甲。当你流失体力时，若你的护甲值大于体力上限，你有概率可以失去1点护甲，然后防止之。",
    nysgs_zf_sheguoyouzui: "赦过宥罪",
    nysgs_zf_sheguoyouzui_info: "其他角色的准备阶段，你可以令其交给你2张手牌，然后若其处于异常状态，你有概率可以复原其武将牌。",

    nysgs_zf_yixinghuandou: "移星换斗",
    nysgs_zf_yixinghuandou_info: "回合开始时，你可以令两名有手牌的角色随机交换至多7张手牌，然后你有概率令双方交换技能符石。",
    nysgs_zf_jiuhanzhanyong: "酒酣战勇",
    nysgs_zf_jiuhanzhanyong_info: "出牌阶段开始时，你可以视为使用1张无次数限制的强化【酒】，然后你有概率从牌堆或弃牌堆中获得牌名各不相同的伤害牌各1张。",
    nysgs_zf_shehunduopo: "摄魂夺魄",
    nysgs_zf_shehunduopo_info: "当你获得其他角色的手牌后，你可以获得其1点怒气，然后你有概率令其封禁，直至你换将或回合结束（每回合限1次）。",

    nysgs_zf_zhulianbihe: "珠联璧合",
    nysgs_zf_zhulianbihe_info: "当你使用一张与你使用的上一张牌点数相等的转化牌时，你从牌堆或弃牌堆中随机获得1张点数+1的牌，然后若本次使用的牌为伤害牌，则你有概率令此牌不可被响应。",
    nysgs_zf_shirupozhu: "势如破竹",
    nysgs_zf_shirupozhu_info: "你使用群体锦囊牌造成伤害时，令本次伤害视为火焰伤害，然后若此牌为强化使用，则你有概率<noname-poptip poptip = rule_nysgs_cuihui></noname-poptip>目标等同于此牌伤害值的手牌并获得1点怒气。",
    nysgs_zf_huayanqiaoyu: "花言巧语",
    nysgs_zf_huayanqiaoyu_info: "你交给其他角色牌后，可以令你与其各回复1点体力，然后若本次交出的牌数大于3张，则你有概率令其<noname-poptip poptip = rule_nysgs_xuanyun></noname-poptip>直至你换将或回合结束（每个回合对每名角色限1次）。",

    nysgs_zf_fengxuemantian: "风雪漫天",
    nysgs_zf_fengxuemantian_info: "你对其他角色造成水属性伤害时，令其失去1点怒气。若其已受伤，你有概率摸1张牌，然后你使用的下张虚拟基本牌（除【闪】外）效果+1且无次数合距离限制。",
};
export default translates;
