const characters = {
	jlsgsy_lvbu: ["male", "shen", 8, ["jlsgsy_wushuang", "mashu", "jlsgsy_baonulvbu"], ["qun", "boss", "bossallowed"]],
	jlsgsy_lvbubaonu: ["male", "shen", 4, ["jlsgsy_wushuang", "mashu", "jlsgsy_xiuluo", "jlsgsy_shenwei", "jlsgsy_shenji"], ["qun", "hiddenboss", "bossallowed"]],
	jlsgsy_dongzhuo: ["male", "shen", 8, ["jlsgsy_zongyu", "jlsgsy_lingnue", "jlsgsy_baozheng", "jlsgsy_baonudongzhuo"], ["qun", "boss", "bossallowed"]],
	jlsgsy_dongzhuobaonu: ["male", "shen", 4, ["jlsgsy_zongyu", "jlsgsy_lingnue", "jlsgsy_baozheng", "jlsgsy_nishi", "jlsgsy_hengxing"], ["qun", "hiddenboss", "bossallowed"]],
	jlsgsy_zhangjiao: ["male", "shen", 8, ["jlsgsy_bujiao", "jlsgsy_taiping", "jlsgsy_baonuzhangjiao"], ["qun", "boss", "bossallowed"]],
	jlsgsy_zhangjiaobaonu: ["male", "shen", 4, ["jlsgsy_bujiao", "jlsgsy_taiping", "jlsgsy_yaohuo", "jlsgsy_sanzhi"], ["qun", "hiddenboss", "bossallowed"]],
	jlsgsy_zhangrang: ["male", "shen", 7, ["jlsgsy_chanxian", "jlsgsy_baonuzhangrang"], ["qun", "boss", "bossallowed"]],
	jlsgsy_zhangrangbaonu: ["male", "shen", 4, ["jlsgsy_chanxian", "jlsgsy_luanzheng", "jlsgsy_canlue"], ["qun", "hiddenboss", "bossallowed"]],
	jlsgsy_weiyan: ["male", "shen", 8, ["jlsgsy_shiao", "jlsgsy_baonuweiyan"], ["shu", "boss", "bossallowed"]],
	jlsgsy_weiyanbaonu: ["male", "shen", 4, ["jlsgsy_shiao", "jlsgsy_fangu", "jlsgsy_kuangxi"], ["shu", "hiddenboss", "bossallowed"]],
	jlsgsy_sunhao: ["male", "shen", 8, ["jlsgsy_mingzheng", "jlsgsy_baonusunhao"], ["wu", "boss", "bossallowed"]],
	jlsgsy_sunhaobaonu: ["male", "shen", 4, ["jlsgsy_shisha", "jlsgsy_huangyin", "jlsgsy_zuijiu", "jlsgsy_guiming"], ["wu", "hiddenboss", "bossallowed"]],
	jlsgsy_caifuren: ["female", "shen", 7, ["jlsgsy_dihui", "jlsgsy_baonucaifuren"], ["qun", "boss", "bossallowed", "name:蔡|null"]],
	jlsgsy_caifurenbaonu: ["female", "shen", 4, ["jlsgsy_dihui", "jlsgsy_luansi", "jlsgsy_huoxin"], ["qun", "hiddenboss", "bossallowed", "name:蔡|null"]],
	jlsgsy_simayi: ["male", "shen", 7, ["jlsgsy_bolue", "jlsgsy_baonusimayi"], ["jin", "boss", "bossallowed", "name:司马|懿"], "jin"],
	jlsgsy_simayibaonu: ["male", "shen", 4, ["jlsgsy_bolue", "jlsgsy_renji", "jlsgsy_biantian", "jlsgsy_tianyou"], ["jin", "hiddenboss", "bossallowed", "name:司马|懿"], "jin"],
	jlsgsy_diaochan: ["female", "shen", 7, ["jlsgsy_meihuo", "jlsgsy_baonudiaochan"], ["qun", "boss", "bossallowed", "name:null|null"]],
	jlsgsy_diaochanbaonu: ["female", "shen", 4, ["jlsgsy_meihuo", "jlsgsy_yaoyan", "jlsgsy_miluan"], ["qun", "hiddenboss", "bossallowed", "name:null|null"]],
	jlsgsy_yuanshao: ["male", "shen", 8, ["jlsgsy_mojian", "jlsgsy_baonuyuanshao"], ["qun", "boss", "bossallowed"]],
	jlsgsy_yuanshaobaonu: ["male", "shen", 4, ["jlsgsy_mojian", "jlsgsy_zhuzai", "jlsgsy_duoji"], ["qun", "hiddenboss", "bossallowed"]],
	jlsgsy_sunluban: ["female", "shen", 7, ["jlsgsy_quanqing", "jlsgsy_baonusunluban"], ["wu", "boss", "bossallowed"]],
	jlsgsy_sunlubanbaonu: ["female", "shen", 4, ["jlsgsy_quanqing", "jlsgsy_raomeng", "jlsgsy_yongjie"], ["wu", "hiddenboss", "bossallowed"]],
	jlsgsy_caocao: ["male", "shen", 8, ["jlsgsy_weiwu", "jlsgsy_baonucaocao"], ["wei", "boss", "bossallowed"]],
	jlsgsy_caocaobaonu: ["male", "shen", 4, ["jlsgsy_weiwu", "jlsgsy_duzun", "jlsgsy_longbian"], ["wei", "hiddenboss", "bossallowed"]],
	jlsgsy_zoushi: ["female", "shen", 7, ["jlsgsy_huoshi", "jlsgsy_baonuzoushi"], ["qun", "boss", "bossallowed"]],
	jlsgsy_zoushibaonu: ["female", "shen", 3, ["jlsgsy_huoshi", "jlsgsy_yinzi", "jlsgsy_mowu"], ["qun", "hiddenboss", "bossallowed"]],
	jlsgsy_menghuo: ["male", "shen", 8, ["jlsgsy_qiushou", "jlsgsy_baonumenghuo"], ["shu", "boss", "bossallowed"]],
	jlsgsy_menghuobaonu: ["male", "shen", 3, ["jlsgsy_qiushou", "jlsgsy_moshou"], ["shu", "hiddenboss", "bossallowed"]],
	jlsgsy_zhangchunhua: ["female", "shen", 7, ["jlsgsy_baonuzhangchunhua", "jlsgsy_diaoling"], ["wei", "boss", "bossallowed"]],
	jlsgsy_zhangchunhuabaonu: ["female", "shen", 3, ["jlsgsy_diaoling", "jlsgsy_ejue", "jlsgsy_jianmie"], ["wei", "hiddenboss", "bossallowed"]],
	jlsgsy_liru: ["male", "shen", 8, ["jlsgsy_baonuliru", "jlsgsy_moce"], ["qun", "boss", "bossallowed"]],
	jlsgsy_lirubaonu: ["male", "shen", 3, ["jlsgsy_moce", "jlsgsy_fenjie", "jlsgsy_jinmie"], ["qun", "hiddenboss", "bossallowed"]],
	jlsgsy_yuanshu: ["male", "shen", 8, ["jlsgsy_baonuyuanshu", "jlsgsy_wangzun"], ["qun", "boss", "bossallowed"]],
	jlsgsy_yuanshubaonu: ["male", "shen", 3, ["jlsgsy_wangzun", "jlsgsy_jiantian", "jlsgsy_zhonggu"], ["qun", "hiddenboss", "bossallowed"]],
	jlsgsy_hetaihou: ["female", "shen", 8, ["jlsgsy_baonuhetaihou", "jlsgsy_shixin"], ["qun", "boss", "bossallowed"]],
	jlsgsy_hetaihoubaonu: ["female", "shen", 3, ["jlsgsy_shixin", "jlsgsy_xueyan", "jlsgsy_juesi"], ["qun", "hiddenboss", "bossallowed"]],
	jlsgsy_jiaxu: ["male", "shen", 8, ["jlsgsy_baonujiaxu", "jlsgsy_huiying"], ["qun", "boss", "bossallowed"]],
	jlsgsy_jiaxubaonu: ["male", "shen", 3, ["jlsgsy_huiying", "jlsgsy_lianpo", "jlsgsy_zhongzao"], ["qun", "hiddenboss", "bossallowed"]],
	jlsgsy_liushan: ["male", "shen", 8, ["jlsgsy_baonuliushan", "jlsgsy_duoquan"], ["shu", "boss", "bossallowed"]],
	jlsgsy_liushanbaonu: ["male", "shen", 3, ["jlsgsy_duoquan", "jlsgsy_lanle", "jlsgsy_wangduan"], ["shu", "hiddenboss", "bossallowed"]],
};

export default characters;
