import { lib } from "noname";

const characters = {
    mjs_old_luji: {
        sex: "male",
        hp: 4,
        group: "xijin",
        skills: ["mjsoldyuanqingqimi", "mjsoldlucairuhai", "mjsoldhuatingheli"],
        trashBin: ["rare"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_new_yanghu: {
        sex: "male",
        hp: 6,
        group: "xijin",
        skills: ["mjsnewqingqiuhuandai", "mjsnewdeguansihai", "mjsqianmouyuanji"],
        trashBin: ["legend"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_old_majun: {
        sex: "male",
        hp: 4,
        group: "wei",
        skills: ["mjsshuizhuanbaixi", "mjsoldlonggujiliu", "mjsqiaosijueshi"],
        trashBin: ["rare"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_old_jiaxu: {
        sex: "male",
        hp: 4,
        group: "donghan",
        skills: ["mjsoldsuanwuyice", "mjswenheluanwu", "mjsdushi"],
        trashBin: ["epic"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_old_weijie: {
        sex: "male",
        hp: 3,
        group: "xijin",
        skills: ["mjsoldfengshenxiuyi", "mjszhuyuzaice", "mjssimengchengji"],
        trashBin: ["junk"],
        maxHandcardBase: 6,
        dieAudios: [],
    },
    mjs_old_huoguang: {
        sex: "male",
        hp: 4,
        group: "xihan",
        skills: ["mjsxingjuyouchang", "mjsoldmangcizaibei", "mjsshanzhuanfeili"],
        trashBin: ["junk"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_old_yanghu: {
        sex: "male",
        hp: 6,
        group: "xijin",
        skills: ["mjsoldqingqiuhuandai", "mjsolddeguansihai", "mjsoldqianmouyuanji"],
        trashBin: ["legend"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_old_lvmeng: {
        sex: "male",
        hp: 6,
        group: "wu",
        skills: ["mjsoldshujunkeji", "mjsoldduzhifenxue", "mjsbaiyidujiang"],
        trashBin: ["epic"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_new_zhaoweihou: {
        sex: "female",
        hp: 4,
        group: "zhao",
        skills: ["mjsnewzhiziweibing", "mjswuminheyoujun"],
        trashBin: ["epic"],
        dieAudios: [],
        maxHandcardBase: 5,
    },
    mjs_old_xusheng: {
        sex: "male",
        hp: 6,
        group: "wu",
        skills: ["mjsruxupojun", "mjsoldbailiyicheng"],
        trashBin: ["junk"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_old_jiangwei: {
        sex: "male",
        hp: 6,
        group: "shu",
        skills: ["mjstianshuiqiliner", "mjsjiufazhongyuan", "mjsoldyijihaisanxian"],
        trashBin: ["rare"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_old_luzhonglian: {
        sex: "male",
        hp: 4,
        group: "qi",
        skills: ["mjsoldyibudiqin", "mjsyijiandingliao", "mjszhumingshuojin"],
        trashBin: ["rare"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_old_lifuren: {
        sex: "female",
        hp: 4,
        group: "xihan",
        skills: ["mjsoldqingguoqingcheng", "mjsshanshanlaichi"],
        trashBin: ["junk"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_old_zhuowenjun: {
        sex: "female",
        hp: 4,
        group: "xihan",
        skills: ["mjsoldyebenxiangru", "mjsdanglumaijiu", "mjsbaitouyin"],
        trashBin: ["rare"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_old_simaxiangru: {
        sex: "male",
        hp: 4,
        group: "xihan",
        skills: ["mjsoldfengqiuhuang", "mjszizhedubi", "mjsquanbaifengyi"],
        trashBin: ["rare"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_old_baqing: {
        sex: "female",
        hp: 4,
        group: "daqin",
        skills: ["mjslikangwancheng", "mjsolddanshanvwang", "mjshuaiqingtai"],
        trashBin: ["rare"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_old_wangyi: {
        sex: "female",
        hp: 4,
        group: "wei",
        skills: ["mjsoldzhongzhenganglie", "mjssheziquanyi"],
        trashBin: ["rare"],
        maxHandcardBase: 4,
        dieAudios: [],
        img: "extension/名将杀/image/character/full/mjs_old_wangyi.jpg",
    },
    mjs_old_houying: {
        sex: "male",
        hp: 4,
        group: "wèi",
        skills: ["mjsxiushenjiexing", "mjsoldshijingyinzhe", "mjsyishenmingzhi"],
        trashBin: ["junk"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_old_pangtong: {
        sex: "male",
        hp: 4,
        group: "shu",
        skills: ["mjstiesuolianzhou", "mjsyuhuochongsheng"],
        trashBin: ["legend"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_old_zhanghan: {
        sex: "male",
        hp: 6,
        group: "daqin",
        skills: ["mjsoldshetushoubing", "mjsxianmei"],
        trashBin: ["junk"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_old_junwanghou: {
        sex: "female",
        hp: 4,
        group: "qi",
        skills: ["mjshuiyanshilang", "mjsoldshiqinjinshen", "mjsoldqiaojieyuhuan"],
        trashBin: ["rare"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_old_zhaoji: {
        sex: "female",
        hp: 4,
        group: "daqin",
        skills: ["mjsoldjuehaoshanwu", "mjsoldyinguiganquan"],
        trashBin: ["epic"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_old_fazheng: {
        hp: 4,
        group: "shu",
        skills: ["mjsoldqihuacesuan", "mjsoldyazibibao"],
        trashBin: ["rare"],
        maxHandcardBase: 5,
        dieAudios: [],
        img: "extension/名将杀/image/character/full/mjs_old_fazheng.jpg",
    },
    mjs_old_caopi: {
        sex: "male",
        hp: 5,
        group: "wei",
        skills: ["mjssichengweiwu", "mjsoldyangexingyin", "mjsshanrangshoufeng"],
        trashBin: ["legend"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_old_weizifu: {
        sex: "female",
        hp: 4,
        group: "xihan",
        skills: ["mjsoldpingyanouzhe", "mjsjiafuderuosi"],
        trashBin: ["epic"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_old_zhengxiu: {
        sex: "female",
        hp: 4,
        group: "chu",
        skills: ["mjsyanxiugongchan", "mjsoldyinduquanshi"],
        trashBin: ["rare"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_old_zhangjiao: {
        sex: "male",
        hp: 5,
        group: "huangjin",
        skills: ["mjstaipingyaoshu", "mjsoldtaipingdao"],
        trashBin: ["legend"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_old_suqin: {
        sex: "male",
        hp: 4,
        group: "zhao",
        skills: ["mjsoldhezong", "mjsliuguoxiangyin", "mjscigu"],
        trashBin: ["epic"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_old_lianpo: {
        sex: "male",
        hp: 6,
        group: "zhao",
        skills: ["mjsoldfujingqingzui", "mjsshangnengfanfou"],
        trashBin: ["legend"],
        dieAudios: [],
        maxHandcardBase: 3,
    },
    mjs_old_ximenbao: {
        sex: "male",
        hp: 5,
        group: "wèi",
        skills: ["mjsyinzhangshierqu", "mjsoldhouminboku", "mjsrubaohebo"],
        trashBin: ["junk"],
        maxHandcardBase: 4,
        dieAudios: [],
        names: "西门|豹",
    },
    mjs_old_lisi: {
        sex: "male",
        hp: 4,
        group: "daqin",
        skills: ["mjsoldfanshumingfa", "mjsjianzhizhuke"],
        trashBin: ["epic"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_old_yanzhaowang: {
        sex: "male",
        hp: 5,
        group: "yan",
        skills: ["mjsxiuzhujintai", "mjsoldqiangbingfaqi"],
        trashBin: ["legend"],
        dieAudios: [],
        maxHandcardBase: 4,
    },
    mjs_old_zhaoweihou: {
        sex: "female",
        hp: 4,
        group: "zhao",
        skills: ["mjsoldzhiziweibing", "mjswuminheyoujun"],
        trashBin: ["epic"],
        dieAudios: [],
        maxHandcardBase: 5,
    },
    mjs_old_zhugeliang: {
        sex: "male",
        hp: 4,
        group: "shu",
        skills: ["mjsqimendunjia", "mjsoldjinnangmiaoji"],
        trashBin: ["legend"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_old_chenping: {
        sex: "male",
        hp: 4,
        group: "xihan",
        skills: ["mjsoldliuchuqiji", "mjsguaxiweimen"],
        trashBin: ["rare"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_old_zhangyi: {
        sex: "male",
        hp: 4,
        group: "daqin",
        skills: ["mjslianheng", "mjszhongkoushuojin", "mjsoldzhezhu"],
        trashBin: ["epic"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_old_shenbuhai: {
        sex: "male",
        hp: 4,
        group: "han",
        skills: ["mjsyishuyuguo", "mjschangyuwushi", "mjsoldjuncaoqibing"],
        trashBin: ["epic"],
        dieAudios: [],
        maxHandcardBase: 5,
    },
    mjs_old_ziying: {
        sex: "male",
        hp: 5,
        group: "daqin",
        skills: ["mjsoldmodaiqinwang", "mjsoldtuimiaozhujian"],
        trashBin: ["rare"],
        maxHandcardBase: 4,
        dieAudios: [],
        names: "嬴|子婴",
    },
    mjs_old_sunce: {
        sex: "male",
        hp: 6,
        group: "wu",
        skills: ["mjshujuyingyang", "mjsoldxiaobawang"],
        trashBin: ["epic"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_old_yueyi: {
        sex: "male",
        hp: 6,
        group: "yan",
        skills: ["mjsoldgujunlianke", "mjsfeikeshunmin", "mjsoldbaohuiwangshu"],
        trashBin: ["legend"],
        dieAudios: [],
        maxHandcardBase: 3,
    },
    /*mjs_old_pingyuanjun: {
        sex: "male",
        hp: 4,
        group: "zhao",
        skills: ["mjsoldzhanxiaolixin", "mjsoldlilingzhihun"],
        trashBin: ["legend"],
        dieAudios: [],
        maxHandcardBase: 5,
        names: "赵|胜",
    },*/
    mjs_old_chunshenjun: {
        sex: "male",
        hp: 4,
        group: "chu",
        skills: ["mjsoldyihuajiemu", "mjswuwangzhizai"],
        trashBin: ["epic"],
        maxHandcardBase: 5,
        dieAudios: [],
        names: "黄|歇",
    },
    mjs_old_zhoubo: {
        sex: "male",
        hp: 6,
        group: "xihan",
        skills: ["mjsxiaozouwange", "mjsoldxuepingzhulv"],
        trashBin: ["rare"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_old_caiwenji: {
        sex: "female",
        hp: 4,
        group: "donghan",
        skills: ["mjshujiashibapai", "mjsoldliluanduanchang"],
        trashBin: ["epic"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_old_mengyi: {
        sex: "male",
        hp: 6,
        group: "daqin",
        skills: ["mjsoldneimoufazhi", "mjsoldzhongxin"],
        trashBin: ["junk"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_old_mengtian: {
        sex: "male",
        hp: 6,
        group: "daqin",
        skills: ["mjsoldzhuchenshoufan", "mjsoldzhongxin"],
        trashBin: ["junk"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_old_lvzhi: {
        sex: "female",
        hp: 4,
        group: "xihan",
        skills: ["mjsoldlinchaochengzhi", "mjszhulvweiwang"],
        trashBin: ["legend"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_old_xuchu: {
        sex: "male",
        hp: 6,
        group: "wei",
        skills: ["mjsoldhuchi", "mjsxiejiahanzhan"],
        trashBin: ["junk"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_old_fanzeng: {
        sex: "male",
        hp: 4,
        group: "xichu",
        skills: ["mjsoldwangqinbichu", "mjshongmenyan"],
        trashBin: ["epic"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_old_xiaohe: {
        sex: "male",
        hp: 4,
        group: "xihan",
        skills: ["mjsoldchengye", "mjsoldbaiye"],
        trashBin: ["legend"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_old_zhangliang: {
        sex: "male",
        hp: 4,
        group: "xihan",
        skills: ["mjsbolangzhuiqin", "mjsoldyunchouweiwo", "mjsoldyiqiaoshoushu"],
        trashBin: ["legend"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_old_longqie: {
        sex: "male",
        hp: 6,
        group: "xichu",
        skills: ["mjszhongyongshiwu", "mjsoldanyingzhulei"],
        trashBin: ["rare"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_old_yuanshao: {
        sex: "male",
        hp: 5,
        group: "donghan",
        skills: ["mjssishisangong", "mjsoldbaiwanxiongbing", "mjsfujinfengliu"],
        trashBin: ["rare"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_old_huangzhong: {
        sex: "male",
        hp: 6,
        group: "shu",
        skills: ["mjsoldbaodaoweilao", "mjsoldbaibuchuanyang", "mjsoldjiaobingzhiji"],
        trashBin: ["junk"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_new_caocao: {
        sex: "male",
        hp: 5,
        group: "wei",
        skills: ["mjstianbufuwo", "mjsxietianyiling", "mjsnewtianxiaguixin"],
        trashBin: ["legend"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_new_sunquan: {
        sex: "male",
        hp: 5,
        group: "wu",
        skills: ["mjschengmashehu", "mjsnewquanxuelishi"],
        trashBin: ["legend"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_new_liubei: {
        sex: "male",
        hp: 5,
        group: "shu",
        skills: ["mjsoldyidefuren", "mjsnewsangumaolu", "mjsnewxiemindujiang"],
        trashBin: ["legend"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_old_caocao: {
        sex: "male",
        hp: 5,
        group: "wei",
        skills: ["mjsoldluanshijianxiong", "mjsoldtianshi"],
        trashBin: ["legend"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_old_sunquan: {
        sex: "male",
        hp: 5,
        group: "wu",
        skills: ["mjschengmashehu", "mjsolddili"],
        trashBin: ["legend"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_old_liubei: {
        sex: "male",
        hp: 5,
        group: "shu",
        skills: ["mjsoldyidefuren", "mjsoldrenhe"],
        trashBin: ["legend"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
};

for (let i in characters) {
    const name = "mjs_" + i.slice("mjs_old_".length);
    //lib.translate[i + "_prefix"] = "旧";
    characters[i].trashBin.push(`ext:名将杀/image/character/${lib.config.extension_名将杀_outcrop}/${name}.jpg`);
    characters[i].dieAudios.push(name);
    if (lib.characterReplace) {
        if (!lib.characterReplace[name]) {
            lib.characterReplace[name] = [name, i];
        } else {
            lib.characterReplace[name].push(i);
        }
    }
}

const characters2 = {
    mjs_zhaogao: {
        sex: "male",
        hp: 21,
        group: "daqin",
        skills: ["mjsjianchendangdao", "mjszhiluweima", "mjsshaqiuzhibian"],
        trashBin: ["epic"],
        maxHandcardBase: 7,
        dieAudios: [],
    },
    mjs_shichangshi: {
        sex: "male",
        hp: 12,
        group: "donghan",
        skills: ["mjszhuoluanhainei"],
        trashBin: ["epic"],
        maxHandcardBase: 12,
        dieAudios: [],
    },
    mjs_naochi: {
        sex: "male",
        hp: 21,
        group: "qi",
        skills: ["mjschoujinxuanliang", "mjstiandisanwen", "mjslietufenzang"],
        trashBin: ["epic"],
        maxHandcardBase: 7,
        dieAudios: [],
    },
    mjs_jiangchong: {
        sex: "male",
        hp: 36,
        group: "xihan",
        skills: ["mjswuguzhihuo", "mjsxiuyichijie", "mjskufaxianyu"],
        trashBin: ["epic"],
        maxHandcardBase: 6,
        dieAudios: [],
    },
};

for (let i in characters2) {
    characters2[i].isAiForbidden = true;
    characters2[i].trashBin.push(`ext:名将杀/image/character/full/${i}.jpg`);
}
Object.assign(characters, characters2);

const characters3 = {
    mjs_simayu: {
        sex: "male",
        hp: 4,
        group: "xijin",
        skills: ["mjsxuezhaoluanchen", "mjsminhuantianxia"],
        trashBin: ["rare"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_simazhong: {
        sex: "male",
        hp: 4,
        group: "xijin",
        skills: ["mjshebushiroumi"],
        trashBin: ["rare"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_jiananfeng: {
        sex: "female",
        hp: 4,
        group: "xijin",
        skills: ["mjsjiaozhaotuzong", "mjshuoxincangdu", "mjsduhouluanjin"],
        trashBin: ["rare"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_simaliang: {
        sex: "male",
        hp: 4,
        group: "xijin",
        skills: ["mjsluanqi", "mjssanshi"],
        trashBin: ["rare"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_simawei: {
        sex: "male",
        hp: 4,
        group: "xijin",
        skills: ["mjslianzhu"],
        trashBin: ["rare"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_simalun: {
        sex: "male",
        hp: 4,
        group: "xijin",
        skills: ["mjschilingxiangjie", "mjsfeihouxiejun"],
        trashBin: ["rare"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_simajiong: {
        sex: "male",
        hp: 4,
        group: "xijin",
        skills: ["mjschangyitaozei", "mjsyixitianxia", "mjszhuanshanzhiwei"],
        trashBin: ["rare"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_simayong: {
        sex: "male",
        hp: 4,
        group: "xijin",
        skills: ["mjstongzongjizhi", "mjslianshiyibing"],
        trashBin: ["rare"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_simaying: {
        sex: "male",
        hp: 4,
        group: "xijin",
        skills: ["mjszhenranchaogang", "mjsdukuiqianjun"],
        trashBin: ["rare"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_simayixijin: {
        sex: "male",
        hp: 4,
        group: "xijin",
        skills: ["mjssanwanggongmou", "mjschanghelizhu", "mjsjinyongmolu"],
        trashBin: ["rare"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_simayue: {
        sex: "male",
        hp: 4,
        group: "xijin",
        skills: ["mjszhuwangzhongyan", "mjsquanshisihai"],
        trashBin: ["rare"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    
    mjs_nianshou: {
        sex: "male",
        hp: 300,
        group: "devil",
        skills: ["mjslieyanshixin", "mjssenluowanxiang", "mjskanglongchengsha", "mjsyiqishuangshen"],
        trashBin: ["legend"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
};

for (let i in characters3) {
    characters3[i].isHiddenBoss = true;
    characters3[i].trashBin.push(`ext:名将杀/image/character/full/${i}.jpg`);
}
Object.assign(characters, characters3);

const characters4 = {
    mjs_npc_bianxi: {
        sex: "male",
        hp: 8,
        group: "wei",
        skills: ["mjsnpcfengying", "mjsnpcmaifu", "mjsnpctaopao"],
        trashBin: ["junk"],
        maxHandcardBase: 2,
        dieAudios: [],
        isAiForbidden: true,
    },
    mjs_npc_caiyang: {
        sex: "male",
        hp: 4,
        group: "wei",
        skills: ["mjsnpczhuisha", "mjsnpcshengjiu"],
        trashBin: ["junk"],
        maxHandcardBase: 5,
        isAiForbidden: true,
    },
    mjs_npc_qinqi: {
        sex: "male",
        hp: 6,
        group: "wei",
        skills: ["mjsnpcbiyanchou", "mjsnpcwuming"],
        trashBin: ["junk"],
        maxHandcardBase: 3,
        dieAudios: [],
        isAiForbidden: true,
    },
    mjs_npc_kongxiu: {
        sex: "male",
        hp: 8,
        group: "wei",
        skills: ["mjsnpcpancha", "mjsnpcyiji"],
        trashBin: ["junk"],
        maxHandcardBase: 3,
        dieAudios: [],
        isAiForbidden: true,
    },
    mjs_npc_mengtan: {
        sex: "male",
        hp: 8,
        group: "wei",
        skills: ["mjsnpcyoudi", "mjsnpcmanma"],
        trashBin: ["junk"],
        maxHandcardBase: 3,
        dieAudios: [],
        isAiForbidden: true,
    },
    mjs_npc_hanfu: {
        sex: "male",
        hp: 8,
        group: "wei",
        skills: ["mjsnpclengjian", "mjsnpcjizou"],
        trashBin: ["junk"],
        maxHandcardBase: 3,
        dieAudios: [],
        isAiForbidden: true,
    },
    mjs_npc_wangzhi: {
        sex: "male",
        hp: 4,
        group: "wei",
        skills: ["mjsnpczonghuo", "mjsnpcchuni"],
        trashBin: ["junk"],
        maxHandcardBase: 5,
        dieAudios: [],
        isAiForbidden: true,
    },
};

for (let i in characters4) {
    characters4[i].isHiddenBoss = true;
    characters4[i].trashBin.push(`ext:名将杀/image/character/full/${i}.jpg`);
}
Object.assign(characters, characters4);

const characters5 = {
    mjs_shanzeitoumu: {
        sex: "male",
        hp: 4,
        group: "qun",
        skills: [],
        trashBin: ["junk"],
        maxHandcardBase: 3,
        dieAudios: [],
        isAiForbidden: true,
    },
    mjs_shanzeiduizhang: {
        sex: "male",
        hp: 4,
        group: "qun",
        skills: [],
        trashBin: ["junk"],
        maxHandcardBase: 1,
        dieAudios: [],
        isAiForbidden: true,
    },
    mjs_shanzeijiayi: {
        sex: "male",
        hp: 4,
        group: "qun",
        skills: [],
        trashBin: ["junk"],
        maxHandcardBase: 1,
        dieAudios: [],
        isAiForbidden: true,
    },
    mjs_shanzeibingding: {
        sex: "male",
        hp: 4,
        group: "qun",
        skills: [],
        trashBin: ["junk"],
        maxHandcardBase: 1,
        dieAudios: [],
        isAiForbidden: true,
    },
};
for (let i in characters5) {
    characters5[i].isHiddenBoss = true;
    characters5[i].trashBin.push(`ext:名将杀/image/character/full/${i}.jpg`);
}
Object.assign(characters, characters5);

const characters44 = {
    mjs_tap_laobing: {
        sex: "male",
        hp: 4,
        group: "qun",
        skills: [],
        trashBin: ["rare"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_tap_guangzhichen: {
        sex: "male",
        hp: 4,
        group: "qun",
        skills: ["mjscaigaobadou", "mjsqibuqiai"],
        trashBin: ["rare"],
        maxHandcardBase: 5,
    },
    mjs_tap_xiaolongbao: {
        sex: "female",
        hp: 4,
        group: "qun",
        skills: [],
        trashBin: ["rare"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
};

for (let i in characters44) {
    characters44[i].isHiddenBoss = true;
    characters44[i].trashBin.push(`ext:名将杀/image/character/full/${i}.jpg`);
}
Object.assign(characters, characters44);

export default characters;
