// Generated by scripts/migrate-shousha-native.mjs
export const shoushaManifest = {
  "format": "noname-ui-workshop",
  "version": 1,
  "id": "builtin-shousha-standard",
  "name": "手杀标准UI",
  "author": "原界面及各 UI 模块作者；PXLNGU整合",
  "description": "手杀标准UI：完整启动动画、登录与大厅场景、全屏选将、换将换牌、对局控件、皮肤、标记及结算。九个界面模块封装为独立套装，不展示内部扩展；联机房间沿用项目实现。",
  "components": {
    "home": {
      "name": "手杀标准 · 登录与大厅",
      "runtime": "shousha",
      "settings": {},
      "assets": {},
      "style": {}
    },
    "modes": {
      "name": "手杀标准 · 模式选择",
      "runtime": "shousha",
      "settings": {},
      "assets": {},
      "style": {}
    },
    "arena": {
      "name": "手杀标准 · 对局布局",
      "runtime": "shousha",
      "settings": {
        "theme": "simple",
        "layout": "mobile",
        "phonelayout": true,
        "image_background": "default",
        "image_background_random": false
      },
      "assets": {},
      "style": {}
    },
    "cards": {
      "name": "手杀标准 · 卡牌正面",
      "runtime": "shousha",
      "settings": {
        "card_style": "default"
      },
      "assets": {},
      "style": {}
    },
    "cardback": {
      "name": "手杀标准 · 卡牌背面",
      "runtime": "shousha",
      "settings": {
        "cardback_style": "default"
      },
      "assets": {},
      "style": {}
    },
    "buttons": {
      "name": "手杀标准 · 操作与技能按钮",
      "runtime": "shousha",
      "settings": {
        "control_style": "default"
      },
      "assets": {},
      "style": {}
    },
    "menus": {
      "name": "手杀标准 · 菜单与弹窗",
      "runtime": "shousha",
      "settings": {
        "menu_style": "default"
      },
      "assets": {},
      "style": {}
    },
    "players": {
      "name": "手杀标准 · 武将框与选将",
      "runtime": "shousha",
      "settings": {
        "player_style": "default",
        "border_style": "auto",
        "presentation_style": "shousha"
      },
      "assets": {},
      "style": {}
    },
    "hp": {
      "name": "手杀标准 · 体力",
      "runtime": "shousha",
      "settings": {
        "hp_style": "glass"
      },
      "assets": {},
      "style": {}
    },
    "lines": {
      "name": "手杀标准 · 指示线",
      "runtime": "shousha",
      "settings": {
        "zhishixian": "default"
      },
      "assets": {},
      "style": {}
    },
    "fonts": {
      "name": "手杀标准 · 字体",
      "runtime": "shousha",
      "settings": {},
      "assets": {},
      "style": {}
    }
  }
};
