const characters = {
	jlsgsr_zhangliao: ["male", "wei", 4, ["jlsg_wuwei", "jlsg_yansha"], []],
	jlsgsr_xiahoudun: ["male", "wei", 4, ["jlsg_zhonghou", "jlsg_ganglie"], ["name:夏侯|惇"]],
	jlsgsr_zhenji: ["female", "wei", 3, ["jlsg_liuyun", "jlsg_lingbo", "jlsg_qingcheng"], ["name:甄|null"]],
	jlsgsr_xuzhu: ["male", "wei", 4, ["jlsg_aozhan", "jlsg_huxiao"], []],
	jlsgsr_simayi: ["male", "wei", 3, ["jlsg_guicai", "jlsg_langgu", "jlsg_zhuizun"], ["name:司马|懿"]],
	jlsgsr_guojia: ["male", "wei", 3, ["jlsg_tianshang", "jlsg_yiji", "jlsg_huiqu"], []],
	jlsgsr_caocao: ["male", "wei", 4, ["jlsg_zhaoxiang", "jlsg_zhishi", "jlsg_jianxiong"], ["zhu"]],
	jlsgsr_zhaoyun: ["male", "shu", 4, ["jlsg_jiuzhu", "jlsg_tuwei"], []],
	jlsgsr_zhangfei: ["male", "shu", 4, ["jlsg_xujin", "jlsg_paoxiao"], []],
	jlsgsr_machao: ["male", "shu", 4, ["jlsg_benxi", "jlsg_yaozhan"], []],
	jlsgsr_guanyu: ["male", "shu", 4, ["jlsg_wenjiu", "jlsg_shuixi"], []],
	jlsgsr_zhugeliang: ["male", "shu", 3, ["jlsg_sanfen", "jlsg_guanxing", "jlsg_weiwo"], ["name:诸葛|亮"]],
	jlsgsr_huangyueying: ["female", "shu", 3, ["jlsg_shouji", "jlsg_hemou", "jlsg_qicai"], ["name:黄|null"]],
	jlsgsr_liubei: ["male", "shu", 4, ["jlsg_rende", "jlsg_chouxi", "jlsg_yongbing"], ["zhu"]],
	jlsgsr_sunshangxiang: ["female", "wu", 3, ["jlsg_yinmeng", "jlsg_xiwu", "jlsg_juelie"], ["name:孙|null"]],
	jlsgsr_daqiao: ["female", "wu", 3, ["jlsg_fangxin", "jlsg_xiyu", "jlsg_wanrou"], ["name:桥|null"]],
	jlsgsr_huanggai: ["male", "wu", 4, ["jlsg_zhouyan", "jlsg_zhaxiang"], []],
	jlsgsr_lvmeng: ["male", "wu", 4, ["jlsg_shixue", "jlsg_guoshi"], []],
	jlsgsr_zhouyu: ["male", "wu", 3, ["jlsg_yingcai", "jlsg_weibao", "jlsg_choulve"], []],
	jlsgsr_ganning: ["male", "wu", 4, ["jlsg_jiexi", "jlsg_youxia"], []],
	jlsgsr_luxun: ["male", "wu", 3, ["jlsg_dailao", "jlsg_youdi", "jlsg_ruya"], []],
	jlsgsr_sunquan: ["male", "wu", 4, ["jlsg_quanheng", "jlsg_xionglve", "jlsg_fuzheng"], ["zhu"]],
	jlsgsr_lvbu: ["male", "qun", 4, ["jlsg_jiwu", "jlsg_sheji"], []],
	jlsgsr_huatuo: ["male", "qun", 3, ["jlsg_xingyi", "jlsg_guagu", "jlsg_wuqin"], []],
	jlsgsr_diaochan: ["female", "qun", 3, ["jlsg_lijian", "jlsg_manwu", "jlsg_baiyue"], ["name:null|null"]],
	//万万没想到还能出新将
	jlsgsr_xiaoqiao: ["female", "wu", 3, ["jlsg_piaoling", "jlsg_miluo", "jlsg_jueyan"], ["name:桥|null"]],
};

export default characters;
