const characters = {
	jlsgsk_madai: ["male", "shu", 4, ["jlsg_qianxi", "mashu"], []],
	jlsgsk_caohua: ["female", "wei", 3, ["jlsg_caiyi", "jlsg_guili"], ["name:曹|null"]],
	jlsgsk_simashi: ["male", "wei", 4, ["jlsg_quanlue"], ["name:司马|师"]],
	jlsgsk_xianglang: ["male", "shu", 3, ["jlsg_cangshu", "jlsg_kanwu"], []],
	jlsgsk_luji: ["male", "wu", 3, ["jlsg_huaiju", "jlsg_huntian"], []],
	jlsgsk_bianfuren: ["female", "wei", 3, ["jlsg_huage", "jlsg_muyi"], ["name:卞|null"]],
	jlsgsk_heqi: ["male", "wu", 4, ["jlsg_diezhang"], []],
	jlsgsk_mateng: ["male", "qun", 4, ["mashu", "jlsg_xiongyi"], []],
	jlsgsk_tianfeng: ["male", "qun", 3, ["jlsg_sijian", "jlsg_gangzhi"], []],
	jlsgsk_feiyi: ["male", "shu", 3, ["jlsg_yanxi", "jlsg_zhige"], []],
	jlsgsk_jiangqin: ["male", "wu", 4, ["jlsg_shangyi", "jlsg_wangsi"], []],
	jlsgsk_dongyun: ["male", "shu", 3, ["jlsg_bibu", "jlsg_kuangzheng"], []],
	jlsgsk_dongxi: ["male", "wu", 4, ["jlsg_duanlan"], []],
	jlsgsk_quancong: ["male", "wu", 4, ["jlsg_yaoming"], []],
	jlsgsk_yujin: ["male", "wei", 4, ["jlsg_zhengyi"], []],
	jlsgsk_panfeng: ["male", "qun", 4, ["jlsg_kuangfu"], []],
	jlsgsk_dengzhi: ["male", "shu", 3, ["jlsg_hemeng", "jlsg_sujian"], []],
	jlsgsk_xuyou: ["male", "wei", 3, ["jlsg_yexi", "jlsg_kuangyan"], []],
	jlsgsk_zhangbu: ["male", "wu", 3, ["jlsg_chaochen", "jlsg_quanzheng"], []],
	jlsgsk_miheng: ["male", "qun", 3, ["jlsg_shejian", "jlsg_kuangao"], []],
	jlsgsk_zumao: ["male", "wu", 4, ["jlsg_yinbing"], []],
	jlsgsk_huaxiong: ["male", "qun", 5, ["jlsg_fenwei", "jlsg_shiyong"], []],
	jlsgsk_sunce: ["male", "wu", 4, ["jlsg_angyang", "jlsg_weifeng", "jlsg_xieli"], []],
	jlsgsk_caoren: ["male", "wei", 4, ["jlsg_jushou"], []],
	jlsgsk_gongsunzan: ["male", "qun", 4, ["jlsg_yicong", "jlsg_muma"], ["name:公孙|瓒"]],
	jlsgsk_sunqian: ["male", "shu", 3, ["jlsg_suiji", "jlsg_fengyi"], []],
	jlsgsk_maliang: ["male", "shu", 3, ["jlsg_yalv", "jlsg_xiemu"], []],
	jlsgsk_buzhi: ["male", "wu", 3, ["jlsg_zhejie", "jlsg_fengya"], []],
	jlsgsk_wangping: ["male", "shu", 4, ["jlsg_yijian", "jlsg_feijun"], []],
	jlsgsk_huangyueying: ["female", "shu", 3, ["jlsg_muniu", "jlsg_liuma"], ["name:黄|null"]],
	jlsgsk_dongzhuo: ["male", "qun", 6, ["jlsg_baozheng", "jlsg_lingnu"], []],
	jlsgsk_chendao: ["male", "shu", 4, ["jlsg_zhongyong"], []],
	jlsgsk_dingfeng: ["male", "wu", 4, ["jlsg_bozhan", "jlsg_qingxi"], []],
	jlsgsk_zhuran: ["male", "wu", 4, ["jlsg_danshou", "jlsg_yonglie"], []],
	jlsgsk_lukang: ["male", "wu", 4, ["jlsg_hengshi", "jlsg_zhijiao"], []],
	jlsgsk_lvlingqi: ["female", "qun", 5, ["jlsg_jiwux"], ["name:吕|null"]],
	jlsgsk_zhoucang: ["male", "shu", 4, ["jlsg_daoshi"], []],
	jlsgsk_kongrong: ["male", "qun", 3, ["jlsg_lirang", "jlsg_xianshi"], []],
	jlsgsk_caochong: ["male", "wei", 3, ["jlsg_chengxiang", "jlsg_renxin"], ["unseen"]],
	jlsgsk_zhanglu: ["male", "qun", 3, ["jlsg_midao", "jlsg_yishe", "jlsg_pudu"], []],
	jlsgsk_guanlu: ["male", "wei", 3, ["jlsg_zongqing", "jlsg_bugua"], []],
	jlsgsk_simazhao: ["male", "wei", 3, ["jlsg_zhaoxin", "jlsg_zhihe"], ["name:司马|昭"]],
	jlsgsk_yangxiu: ["male", "wei", 3, ["jlsg_caijie", "jlsg_jilei"], []],
	jlsgsk_liyan: ["male", "shu", 4, ["jlsg_yanliang"], []],
	jlsgsk_jiping: ["male", "qun", 3, ["jlsg_duzhi", "jlsg_lieyi"], []],
	jlsgsk_sunhao: ["male", "wu", 4, ["jlsg_baoli"], []],
	jlsgsk_zhugejin: ["male", "wu", 3, ["jlsg_huanbing", "jlsg_hongyuan"], ["name:诸葛|瑾"]],
	jlsgsk_zhangxiu: ["male", "qun", 4, ["jlsg_huaqiang", "jlsg_chaohuang"], []],
	jlsgsk_sunluyu: ["female", "wu", 3, ["jlsg_huilian", "jlsg_wenliang"], ["name:孙|鲁育"]],
	jlsgsk_luzhi: ["male", "qun", 3, ["jlsg_jinglun", "jlsg_ruzong"], []],
	jlsgsk_yuji: ["male", "qun", 3, ["jlsg_guhuo", "jlsg_fulu"], []],
	jlsgsk_mifuren: ["female", "shu", 3, ["jlsg_guixiu", "jlsg_cunsi"], ["name:糜|null"]],
	jlsgsk_zhangning: ["female", "qun", 3, ["jlsg_leiji", "jlsg_shanxi"], ["name:张|null"]],
	jlsgsk_guonvwang: ["female", "wei", 3, ["jlsg_gongshen", "jlsg_jianyue"], ["name:郭|null"]],
	jlsgsk_chengyu: ["male", "wei", 3, ["jlsg_pengri", "jlsg_danmou"], []],
	jlsgsk_zhangren: ["male", "qun", 4, ["jlsg_fushe"], []],
	jlsgsk_mizhu: ["male", "shu", 3, ["jlsg_ziguo", "jlsg_shangdao"], []],
	jlsgsk_zangba: ["male", "wei", 4, ["jlsg_hengjiang"], []],
	jlsgsk_hejin: ["male", "qun", 4, ["jlsg_zhuanshan"], []],
	jlsgsk_wangyi: ["female", "wei", 3, ["jlsg_zhenlie", "jlsg_miji"], []],
	jlsgsk_zuoci: ["male", "qun", 3, ["jlsg_qianhuan"], []],
	jlsgsk_guanyu: ["male", "wei", 4, ["jlsg_wusheng", "jlsg_danqi"], []],
	jlsgsk_machao: ["male", "qun", 4, ["jlsg_zhuiji", "jlsg_xionglie"], []],
	jlsgsk_caiwenji: ["female", "wei", 3, ["jlsg_chenqing", "jlsg_mozhi"], ["name:蔡|琰"]],
	jlsgsk_zhangbao: ["male", "qun", 3, ["jlsg_zhoufu", "jlsg_yingbing"], []],
	jlsgsk_guanxing: ["male", "shu", 4, ["jlsg_yongji", "jlsg_wuzhi"], []],
	jlsgsk_kuaiyue: ["male", "qun", 3, ["jlsg_yidu", "jlsg_zhubao"], []],
	jlsgsk_zhoutai: ["male", "wu", 4, ["jlsg_buqu", "jlsg_fenji"], []],
	jlsgsk_zoushi: ["female", "qun", 3, ["jlsg_jiaomei", "jlsg_huoshui"], ["name:邹|null"]],
	jlsgsk_yanliang: ["male", "qun", 4, ["jlsg_hubu"], []],
	jlsgsk_zhugeguo: ["female", "shu", 3, ["jlsg_yuhua", "jlsg_dengxian"], ["name:诸葛|null"]],
	jlsgsk_xizhicai: ["male", "wei", 3, ["jlsg_tiance", "jlsg_jiexin"], []],
	jlsgsk_guansuo: ["male", "shu", 4, ["jlsg_zhengnan", "jlsg_tongxin"], []],
	jlsgsk_baosanniang: ["female", "shu", 3, ["jlsg_jianwu", "jlsg_zhennan", "jlsg_tongxin"], ["name:鲍|null"]],
	jlsgsk_dongbai: ["female", "qun", 3, ["jlsg_shemi", "jlsg_jiaohui"], ["name:董|null"]],
	jlsgsk_xushi: ["female", "wu", 3, ["jlsg_wengua", "jlsg_fuzhu"], ["name:徐|null"]],
	jlsgsk_zhoufei: ["female", "wu", 3, ["jlsg_yinyuan", "jlsg_konghou"], ["name:周|null"]],
	jlsgsk_wuyi: ["male", "shu", 4, ["jlsg_zhidi"], []],
	jlsgsk_zhangliang: ["male", "qun", 4, ["jlsg_jijun", "jlsg_fangtong"], []],
	jlsgsk_panshu: ["female", "wu", 3, ["jlsg_jinzhi", "jlsg_yuyou"], []],
	jlsgsk_caorui: ["male", "wei", 3, ["jlsg_huituo", "jlsg_xingshuai"], []],
	jlsgsk_liuchen: ["male", "shu", 4, ["jlsg_zhanjue"], []],
	jlsgsk_sunxiu: ["male", "wu", 3, ["jlsg_yanzhu", "jlsg_xingxue"], []],
	jlsgsk_zhangrang: ["male", "qun", 3, ["jlsg_taoluan"], []],
	jlsgsk_xiahoushi: ["female", "shu", 3, ["jlsg_shiqiao", "jlsg_yingge"], ["name:夏侯|null"]],
	jlsgsk_sundeng: ["male", "wu", 3, ["jlsg_kuangbi"], []],
	jlsgsk_caoxiu: ["male", "wei", 4, ["jlsg_taoxi"], []],
	jlsgsk_caojie: ["female", "qun", 3, ["jlsg_huaibi", "jlsg_zhixi"], []],
	jlsgsk_xinxianying: ["female", "wei", 3, ["jlsg_caijian", "jlsg_zhishix"], ["name:辛|null"]],
	jlsgsk_zhuzhi: ["male", "wu", 4, ["jlsg_anguo"], []],
	jlsgsk_wanglang: ["male", "wei", 3, ["jlsg_quanxiang", "jlsg_gushe", "jlsg_jici"], []],
	jlsgsk_wuxian: ["female", "shu", 3, ["jlsg_hechun", "jlsg_daiyan"], ["name:吴|null"]],
	jlsgsk_jushou: ["male", "qun", 3, ["jlsg_jianying", "jlsg_shibei"], []],
	jlsgsk_sunliang: ["male", "wu", 3, ["jlsg_kuizhu", "jlsg_chezheng"], []],
	jlsgsk_wenyang: ["male", "wei", 7, ["jlsg_jueyong", "jlsg_choujue"], []],
	jlsgsk_yanyan: ["male", "shu", 4, ["jlsg_juzhan"], []],
	jlsgsk_zhugezhan: ["male", "shu", 4, ["jlsg_zuilun", "jlsg_fuzhi"], ["name:诸葛|瞻"]],
	jlsgsk_panzhang: ["male", "wu", 4, ["jlsg_jiejun"], []],
	jlsgsk_sunru: ["female", "wu", 3, ["jlsg_xiecui", "jlsg_youxu"], ["name:孙|null"]],
	jlsgsk_liuyan: ["male", "qun", 3, ["jlsg_zhulu", "jlsg_limu"], []],
	jlsgsk_gongsunyuan: ["male", "qun", 4, ["jlsg_huaiyi"], ["name:公孙|渊"]],
	jlsgsk_guohuanghou: ["female", "wei", 3, ["jlsg_jiaozhao", "jlsg_danxin"], ["name:郭|null"]],
	jlsgsk_zhaoxiang: ["female", "shu", 4, ["jlsg_fanghun", "jlsg_fuhan"], ["name:赵|null"]],
	jlsgsk_chenqun: ["male", "wei", 3, ["jlsg_pindi", "jlsg_faen"], []],
	jlsgsk_lvfan: ["male", "wu", 3, ["jlsg_diaodu", "jlsg_diancai"], []],
	jlsgsk_hetaihou: ["female", "qun", 3, ["jlsg_zhendu", "jlsg_qiluan"], ["name:何|null"]],
	jlsgsk_zhangyi: ["male", "shu", 4, ["jlsg_wurong"], []],
	jlsgsk_caochun: ["male", "wei", 4, ["jlsg_shanjia"], []],
	jlsgsk_shamoke: ["male", "shu", 4, ["jlsg_jili"], ["name:null|null"]],
	jlsgsk_lingcao: ["male", "wu", 4, ["jlsg_dujin"], []],
	jlsgsk_zhaoyan: ["female", "wu", 3, ["jlsg_sanjue"], ["name:赵|null"]],
	jlsgsk_beimihu: ["female", "qun", 3, ["jlsg_canshi", "jlsg_xianji"], ["name:卑弥|呼"]],
	jlsgsk_wutugu: ["male", "qun", 6, ["jlsg_hanyong"], ["name:null|null"]],
	jlsgsk_caoying: ["female", "wei", 4, ["jlsg_lingruo", "jlsg_fujian"], ["name:曹|null"]],
	jlsgsk_mayunlu: ["female", "shu", 4, ["mashu", "jlsg_fengyin", "jlsg_rongzhuang"], ["name:马|null"]],
	jlsgsk_zhongyao: ["male", "wei", 3, ["jlsg_huomo", "jlsg_dingguan"], []],
	jlsgsk_nanhualaoxian: ["male", "qun", 3, ["jlsg_xianshou", "jlsg_chengfeng"], ["name:庄|周"]],
	jlsgsk_jiangwei: ["male", "wei", 5, ["jlsg_kunfen", "jlsg_caiyu"], []],
	jlsgsk_huanghao: ["male", "shu", 3, ["jlsg_qinqing", "jlsg_huisheng"], []],
	jlsgsk_huaman: ["female", "shu", 3, ["jlsg_manyi", "jlsg_souying"], ["name:花|null"]],
	jlsgsk_pangtong: ["male", "wu", 3, ["jlsg_guolun", "jlsg_songsang"], []],
	jlsgsk_lvdai: ["male", "wu", 4, ["jlsg_qinguo"], []],
	jlsgsk_wanniangongzhu: ["female", "qun", 3, ["jlsg_zhenge", "jlsg_xinghan"], ["name:刘|null"]],
	jlsgsk_wangyuanji: ["female", "qun", 3, ["jlsg_qianchong", "jlsg_shangjian"], ["name:王|元姬"]],
	jlsgsk_zhangchangpu: ["female", "wei", 3, ["jlsg_yanjiao", "jlsg_xingshen"], ["name:张|null"]],
	jlsgsk_qinmi: ["male", "shu", 3, ["jlsg_jianzheng", "jlsg_tianbian"], []],
	jlsgsk_xingdaorong: ["male", "qun", 5, ["jlsg_xuhe"], []],
	jlsgsk_zhouyi: ["female", "wu", 4, ["jlsg_zhukou", "jlsg_duannian"], ["name:周|null"]],
	jlsgsk_guohuai: ["male", "wei", 4, ["jlsg_jingce"], []],
	jlsgsk_huangchengyan: ["male", "qun", 3, ["jlsg_guanxu", "jlsg_yashi"], ["name:黄|承彦"]],
	jlsgsk_lvkai: ["male", "shu", 3, ["jlsg_tunan", "jlsg_bijing"], []],
	jlsgsk_zhugedan: ["male", "wei", 5, ["jlsg_gongao", "jlsg_juyi", "jlsg_weizhong"], ["name:诸葛|诞"]],
	jlsgsk_yangwan: ["female", "shu", 3, ["jlsg_youyan", "jlsg_zhuihuan"], ["name:杨|null"]],
	jlsgsk_cenhun: ["male", "wu", 3, ["jlsg_jishe", "jlsg_lianhuo"], []],
	jlsgsk_gexuan: ["male", "wu", 3, ["jlsg_lianhua", "jlsg_zhafu"], []],
	jlsgsk_yanghuiyu: ["female", "qun", 3, ["jlsg_ciwei", "jlsg_caiyuan"], []],
	jlsgsk_tadun: ["male", "qun", 6, ["jlsg_luanzhan"], ["name:null|null"]],
	jlsgsk_caojinyu: ["female", "wei", 3, ["jlsg_yuqi", "jlsg_shanshen"], ["name:曹|null"]],
	jlsgsk_haozhao: ["male", "wei", 4, ["jlsg_zhengu"], []],
	jlsgsk_puyuan: ["male", "shu", 4, ["jlsg_tianjiang", "jlsg_zhuren"], []],
	jlsgsk_chenshi: ["male", "shu", 4, ["jlsg_qingbei"], []],
	jlsgsk_tenggongzhu: ["female", "wu", 3, ["jlsg_chongxing", "jlsg_liunian"], ["name:孙|null"]],
	jlsgsk_taishici: ["male", "qun", 4, ["jlsg_jixu"], ["name:太史|慈"]],
	jlsgsk_yanjun: ["male", "wu", 3, ["jlsg_guanchao", "jlsg_xunxian"], []],
	jlsgsk_duyu: ["male", "wei", 4, ["jlsg_sanchen", "jlsg_pozhu"], []],
	//jlsgsk_lingju: ["female", "qun", 3, ["jlsg_jieyuan", "jlsg_fenxin"], []],
	jlsgsk_hujinding: ["female", "shu", 3, ["jlsg_qingyuan", "jlsg_chongshen"], ["name:胡|null"]],
	jlsgsk_shixie: ["male", "qun", 3, ["jlsg_biluan", "jlsg_lixia"], []],
	jlsgsk_liuzan: ["male", "wu", 4, ["jlsg_fenyin"], []],
	jlsgsk_simalang: ["male", "wei", 3, ["jlsg_junbing", "jlsg_quji"], ["name:司马|朗"]],
	jlsgsk_zhangqiying: ["female", "qun", 3, ["jlsg_falu", "jlsg_zhenyi", "jlsg_dianhua"], ["name:张|null"]],
	jlsgsk_qiaozhou: ["male", "shu", 3, ["jlsg_shiming", "jlsg_xingbu"], ["name:谯|周"]],
};

export default characters;
