const translate = {
	nysgs_fudichouxin: "釜底抽薪",
	nysgs_fudichouxin_info: "出牌阶段，对一名其他角色使用，其失去1点怒气。",
	nysgs_nufachongguan: "怒发冲冠",
	nysgs_nufachongguan_info: "出牌阶段，对一名角色使用，其获得1点怒气。",
	nysgs_shuiyanqijun: "水淹七军",
	nysgs_shuiyanqijun_info: "出牌阶段，对所有其他角色使用，每名角色须弃置其装备区的所有牌，否则对其造成的1点水属性伤害。",
	nysgs_fengzuidao: "凤嘴刀",
	nysgs_fengzuidao_info: "你使用【杀】时，可以弃置2张手牌，令此【杀】伤害+1且视为火属性伤害。",
	nysgs_fengzuidao_skill: "凤嘴刀",
	nysgs_fengzuidao_skill_info: "你使用【杀】时，可以弃置2张手牌，令此【杀】伤害+1且视为火属性伤害。",
	nysgs_stratagem_fengzuidao: "凤嘴刀",
	nysgs_stratagem_fengzuidao_info: "你造成的属性伤害+1。",
	nysgs_longyaqiang: "龙牙枪",
	nysgs_longyaqiang_info: "你使用【杀】对其他角色造成伤害后，其不获得怒气。",
	nysgs_longyaqiang_skill: "龙牙枪",
	nysgs_longyaqiang_skill_info: "你使用【杀】对其他角色造成伤害后，其不获得怒气。",
	nysgs_stratagem_longyaqiang: "龙牙枪",
	nysgs_stratagem_longyaqiang_info: "你造成伤害后获得1点怒气。",
	nysgs_bazhepifeng: "霸者披风",
	nysgs_bazhepifeng_info: "你受到其他角色造成的体力流失时，防止之。结束阶段，若你已受伤，则你回复1点体力。",
	nysgs_bazhepifeng_skill: "霸者披风",
	nysgs_bazhepifeng_skill_info: "你受到其他角色造成的体力流失时，防止之。结束阶段，若你已受伤，则你回复1点体力。",
	nysgs_stratagem_bazhepifeng: "霸者披风",
	nysgs_stratagem_bazhepifeng_info: "你不能成为其他角色使用单体非延时锦囊牌的目标。",
	nysgs_longlinjia: "龙鳞甲",
	nysgs_longlinjia_info: "你使用【杀】对其他角色造成伤害后，其不获得怒气。",
	nysgs_longlinjia_skill: "龙鳞甲",
	nysgs_longlinjia_skill_info: "你使用【杀】对其他角色造成伤害后，其不获得怒气。",
	nysgs_stratagem_longlinjia: "龙鳞甲",
	nysgs_stratagem_longlinjia_info: "你使用黑色【杀】指定目标后，其流失1点体力。",
	nysgs_stratagem_qilin: "麒麟弓",
	nysgs_stratagem_qilin_info: "你使用【杀】可以额外指定1个目标。",
	nysgs_stratagem_qinggang: "青釭剑",
	nysgs_stratagem_qinggang_info: "你对有护甲的角色造成的伤害翻倍。",
	nysgs_stratagem_zhangba: "丈八蛇矛",
	nysgs_stratagem_zhangba_info: "你攻击范围内的其他角色濒死时不能使用【酒】。",
	nysgs_stratagem_zhuge: "诸葛连弩",
	nysgs_stratagem_zhuge_info: "你强化使用【杀】伤害+1。",
	nysgs_stratagem_bagua: "八卦阵",
	nysgs_stratagem_bagua_info: "你使用伤害类锦囊牌无法被【无懈可击】响应且伤害+1。",
	nysgs_stratagem_baiyin: "白银狮子",
	nysgs_stratagem_baiyin_info: "当你失去【白银狮子】后，封禁其他角色，直至你换将或回合结束。",
};

export default translate;
