import {swTool} from "../../main/swTool.js";

const ea = swTool.audioSrc;
export default {
	//Q群风云传
	swq_aoliao: {
		sex: "male",
		group: 'shu',
		hp: 1,
		maxHp: 3,
		skills: ['swq_zhitian', 'swq_jincui', 'swq_qideng'],
		img: "image/character/sb_sp_zhugeliang.jpg",
		dieAudios: ["sb_sp_zhugeliang"],
	},
	swq_lugushou: {
		sex: "female",
		group: 'key',
		hp: 3,
		skills: ['swq_duannian', 'swq_jifeng', 'swq_juejing'],
		img: "swq_lugushou.jpg",
		dieAudios: ["sb_zhenji"],
	},
	swq_xindong: {
		sex: "female",
		group: 'key',
		hp: 4,
		isZhugong: true,
		skills: ['swq_qingnian', 'swq_lunqi', 'swq_xinci'],
		img: "swq_xindong.jpg",
		dieAudios: ["tenggongzhu"],
	},
	swq_sunyuning: {
		sex: "male",
		group: 'key',
		hp: 4,
		skills: ['swq_wudu', 'swq_yuyin'],
		img: "swq_sunyuning.jpg",
		dieAudios: ["key_saya"],
	},
	swq_florian: {
		sex: "female",
		group: 'wu',
		hp: 4,
		skills: ['swq_yinbing', 'swq_lingcan'],
		img: "swq_florian.jpg",
		dieAudios: [""],
	},
	swq_shouwang: {
		sex: "female",
		group: "key",
		hp: 4,
		isZhugong: true,
		skills: ["swq_zhongyuan", "swq_xinsui"],
		img: "swq_shouwang.jpg",
		dieAudios: [`${ea}swq_shouwang/swq_shouwang.mp3`],
	},
	swq_tianshangke: {
		sex: "male",
		group: "qun",
		hp: 3,
		clans: ["天上"],
		skills: ["swq_gushou", "swq_buce", "swq_xiaobing"],
		img: "swq_tianshangke.jpg",
	},
	swq_suier: {
		sex: "female",
		group: "shen",
		hp: 4,
		skills: ["swq_wanxiang", "swq_wendao", "swq_dingxu"],
		img: "swq_suier.jpg",
		dieAudios: [`${ea}swq_suier/swq_suier.mp3`],
	},
	swq_xietaobao: {
		sex: "female",
		group: "key",
		hp: 3,
		maxHp: 3,
		skills: ["swq_xiangfu", "swq_zhishou"],
		img: "swq_xietaobao.jpg",
		dieAudios: [`${ea}swq_xietaobao/swq_xietaobao.mp3`],
	},
	swq_shuisi: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["swq_xinjie", "swq_duwo", "swq_shuigu"],
		img: "swq_shuisi.jpg",
		mp4: "swq_shuisi.mp4",
		dieAudios: [`${ea}swq_shuisi/swq_shuisi.mp3`],
	},
	swq_fenglinghuoshan: {
		sex: "male",
		group: "key",
		hp: 4,
		//maxHp: 4,
		//hujia: 1,
		isZhugong: true,
		skills: ["swq_fengling", "swq_liantian", "swq_huoshan", "swq_shiyun"],
		img: "swq_fenglinghuoshan.jpg",
		dieAudios: [`${ea}swq_fenglinghuoshan/swq_fenglinghuoshan.mp3`],
	},
	swq_xuanchang: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["swq_suibo", "swq_zhuliu", "swq_gongjin"],
		img: "swq_xuanchang.jpg",
		dieAudios: [`${ea}swq_xuanchang/swq_xuanchang.mp3`],
	},
	//Q群风云传-鹿天帝包
	swlu_lugushou: {
		sex: "female",
		group: 'key',
		hp: 3,
		maxHp: 4,
		skills: ['swlu_mengyan', "swlu_xiaqi"],
		img: "swlu_lugushou.jpg",
		dieAudios: [`${ea}swlu_lugushou/swlu_lugushou.mp3`],
	},
	swlu_sunyuning: {
		sex: "male",
		group: 'key',
		hp: 3,
		maxHp: 4,
		skills: ["swlu_yuqian", "swlu_lvshu", "swlu_xucheng"],
		img: "swlu_sunyuning.jpg",
		dieAudios: [`${ea}swlu_sunyuning/swlu_sunyuning.mp3`],
	},
	swlu_xindong: {
		sex: "female",
		group: "key",
		hp: 3,
		maxHp: 4,
		isZhugong: true,
		skills: ["swlu_kuiqing", "swlu_kongxian", "swlu_xinqi"],
		img: "swlu_xindong.jpg",
		dieAudios: ["tenggongzhu"],
	},
	//鹿帝天上客
	swlu_tianshangke: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 4,
		skills: ["swlu_qiujian", "swlu_bishen"],
		//img: "swlu_tianshangke.jpg",
		//dieAudios: [`${ea}swlu_tianshangke/swlu_tianshangke.mp3`],
	},
	swlu_shuisi: {
		sex: "female",
		group: "key",
		hp: 3,
		maxHp: 4,
		skills: ["swlu_pianyu", "swlu_juejie", "swlu_shuiyu"],
		img: "swlu_shuisi.jpg",
		dieAudios: [`${ea}swq_shuisi/swq_shuisi.mp3`],
	},
	// Q群风云传-玫瑰血色包
	swx_lugushou: {
		sex: "female",
		group: "sw_blood",
		hp: 4,
		skills: ["swx_xuezu", "swx_mieyi", "swx_jihun"],
		img: "swx_lugushou.jpg",
		dieAudios: [`${ea}swx_lugushou/swx_lugushou.mp3`],
	},
	swx_tianshangke: {
		sex: "male",
		group: "sw_blood",
		hp: 4,
		clans: ["天上"],
		skills: ["swx_xuezu2", "swx_mengmu", "swx_xiake"],
		img: "swx_tianshangke.jpg",
	},
	swx_wudouwawa: {
		sex: "none",
		group: "sw_blood",
		hp: 1,
		maxHp: 1,
		skills: ["swx_jihun_doll_lock"],
		isUnseen: true,
	},
	swx_shuisi: {
		sex: "female",
		group: "sw_blood",
		hp: 4,
		skills: ["swx_xuezu3", "swx_sijie", "swx_shuizhi"],
		img: "swx_shuisi.jpg",
		dieAudios: [`${ea}swq_shuisi/swq_shuisi.mp3`],
	},
	// swx_fenglinghuoshan: {
	// 	sex: "male",
	// 	group: "sw_blood",
	// 	hp: 4,
	// 	maxHp: 5,
	// 	hujia: 1,
	// 	skills: ["swx_fenglinghuoshan_xuezu", "swx_fenglinghuoshan_b", "swx_fenglinghuoshan_c"],
	// 	img: "swx_fenglinghuoshan.jpg",
	// 	dieAudios: [`${ea}swq_fenglinghuoshan/swq_fenglinghuoshan.mp3`],
	// },
	//异构奇英录
	swyg_jushou: {
		sex: 'male',
		group: 'qun',
		hp: 3,
		skills: ['swyg_jianying', 'swyg_quanlue', 'swyg_shibei'],
		img: "swyg_jushou.jpg",
		dieAudios: ["re_jushou"],
	},
	swyg_guojia: {
		sex: 'male',
		group: 'wei',
		hp: 3,
		skills: ['swyg_shisheng', 'swyg_shibai'],
		img: "image/character/ps1059_guojia.jpg",
		dieAudios: ["shen_guojia"],
	},
	swyg_xunyu: {
		sex: 'male',
		group: 'wei',
		hp: 3,
		skills: ['swyg_zaifu', 'swyg_dingce'],
		img: "swyg_xunyu.jpg",
		dieAudios: ["shen_xunyu"],
	},
	swyg_caojinyu: {
		sex: 'female',
		group: 'wei',
		hp: 3,
		skills: ['swyg_yuqi', 'swyg_shanshen', 'swyg_xianjing'],
		img: "swyg_caojinyu.jpg",
		dieAudios: ["caojinyu"],
	},
	swyg_hanxiandi: {
		sex: 'male',
		group: 'qun',
		hp: 3,
		skills: ['swyg_modi', 'swyg_zhaoling', 'swyg_fuhan', 'swyg_handi'],
		img: "swyg_hanxiandi.jpg",
		dieAudios: ["dc_sb_liuxie"],
	},
	swyg_xiaoqiao: {
		sex: 'female',
		group: 'wu',
		hp: 3,
		skills: ['swyg_tianxiang', 'swyg_hongyan'],
		img: "swyg_xiaoqiao.jpg",
		dieAudios: ["sb_xiaoqiao"],
	},
	swyg_sunluyu: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["swyg_meibu", "swyg_mumu"],
		img: "swyg_sunluyu.jpg",
		dieAudios: ["sunluyu"],
	},
	swyg_liubei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["swyg_huairen", "swyg_gongji"],
		img: "swyg_liubei.jpg",
		dieAudios: ["re_liubei"],
		isZhugong: true,
	},
	swyg_zhangwen: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["swyg_zhaotao", "swyg_lvwang"],
		img: "swyg_zhangwen.jpg",
		dieAudios: [`${ea}swyg_zhangwen/swyg_zhangwen.mp3`],
	},
	// 二游同人创
	swe_nanali: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["swe_quanbing", "swe_zhongji"],
		img: "swe_nanali.jpg",
		dieAudios: [`${ea}swe_nanali/swe_nanali.mp3`],
	},
	swe_katixiya: {
		sex: 'female',
		group: 'wei',
		hp: 4,
		skills: ['swe_fengdu', 'swe_yijian', "swe_qiyuan"],
		img: "swe_katixiya.jpg",
		dieAudios: [`${ea}katixiya/katixiya.mp3`],
	},
	swe_fuludelisi: {
		sex: 'female',
		group: 'wei',
		hp: 4,
		skills: ['swe_jueyi'],
		isUnseen: true,
		img: "swe_fuludelisi.jpg",
		dieAudios: [`${ea}katixiya/fuludelisi.mp3`],
	},
	swe_Dfeiaoleituo: {
		sex: 'male',
		group: 'devil',
		hp: 2,
		skills: ['swe_epicseven'],
		isUnseen: true,
		//img: "swe_fuludelisi.jpg",
		//dieAudios: [`${ea}katixiya/fuludelisi.mp3`],
	},
	swe_yidemeita: {
		sex: "female",
		group: "wei",
		hp: 3,
		maxHp: 3,
		skills: ["swe_tianjian", "swe_tianqi"],
		img: "swe_yidemeita.jpg",
		dieAudios: [`${ea}swe_yidemeita/swe_yidemeita.mp3`],
	},
	//丛雨
	swe_congyu: {
		sex: "female",
		group: "shen",
		hp: 2,
		maxHp: 2,
		skills: ["swe_renling", "swe_wangyue"],
		img: "swe_congyu.jpg",
		dieAudios: [`${ea}swe_congyu/swe_congyu.mp3`],
	},
	// 和泉妃爱
	swe_hequanfeiai: {
		sex: "female",
		group: "key",
		hp: 3,
		maxHp: 3,
		skills: ["swe_chijia", "swe_chenxiang"],
		img: "swe_hequanfeiai.jpg",
		dieAudios: [`${ea}swe_hequanfeiai/swe_hequanfeiai.mp3`],
	},
	// 神山识
	swe_shenshanshi: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["swe_zhuogui", "swe_guiji"],
		img: "swe_shenshanshi.jpg",
		dieAudios: [`${ea}swe_shenshanshi/swe_shenshanshi.mp3`],
	},
	// 鸣濑白羽
	swe_minglaibaiyu: {
		sex: "female",
		group: "key",
		hp: 3,
		maxHp: 3,
		skills: ["swe_yuzhao", "swe_chunbai", "swe_kaoyu", "swe_guying"],
		img: "swe_minglaibaiyu.jpg",
		dieAudios: [`${ea}swe_minglaibaiyu/swe_minglaibaiyu.mp3`],
	},
	// 睡死
	// swe_shuisi: {
	// 	sex: "male",
	// 	group: "shen",
	// 	hp: 3,
	// 	maxHp: 3,
	// 	skills: ["swe_fenke", "swe_dunyi", "swe_siming"],
	// 	img: "swe_shuisi.jpg",
	// 	dieAudios: [`${ea}swe_shuisi/swe_shuisi.mp3`],
	// },
	// 符玄
	swe_fuxuan: {
		sex: "female",
		group: "key",
		hp: 4,
		skills: ["swe_pitai", "swe_qiongguan"],
		img: "swe_fuxuan.jpg",
		mp4: "swe_fuxuan.mp4",
		dieAudios: [`${ea}swe_fuxuan/swe_fuxuan.mp3`],
	},
	// 小春
	swe_xiaochun: {
		sex: "female",
		group: "key",
		hp: 4,
		skills: ["swe_maodian", "swe_maopao"],
		img: "swe_xiaochun.jpg",
		mp4: "swe_xiaochun.mp4",
		dieAudios: [""],
	},
	// 碧野栖鸾包
	swby_lugushou: {
		sex: "female",
		group: "key",
		hp: 3,
		//maxHp: 4,
		skills: ["swby_fangcao", "swby_qiluan"],
		img: "swby_lugushou.jpg",
		dieAudios: [`${ea}swyc_lugushou/swyc_lugushou.mp3`],
	},
	swby_shouwang: {
		sex: "female",
		group: "key",
		hp: 4,
		skills: ["swby_zhezhi", "swby_hongwang", "swby_chunsheng", "swby_qiluan"],
		img: "swby_shouwang.jpg",
		dieAudios: [`${ea}swq_shouwang/swq_shouwang.mp3`],
	},
	// 假日月潮包
	swyc_lugushou: {
		sex: "female",
		group: "key",
		hp: 2,
		maxHp: 3,
		skills: ["swyc_zhuiyun", "swyc_chaoyuan", "swyc_huaquan"],
		img: "swyc_lugushou.jpg",
		dieAudios: [`${ea}swyc_lugushou/swyc_lugushou.mp3`],
	},
	swyc_os: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["swyc_yongguan", "swyc_zhanxin", "swyc_jiurang", "swyc_shapai"],
		img: "swyc_os.jpg",
		dieAudios: [`${ea}swyc_os/swyc_os.mp3`],
	},
	// 剑挽造化篇
	swjw_lugushou: {
		sex: "female",
		group: 'key',
		hp: 4,
		skills: ["swjw_jianche", "swjw_feihua", "swjw_binzang"],
		img: "swjw_lugushou.jpg",
		mp4: "swjw_lugushou.mp4",
	},
	//剑挽天上客
	swjw_tianshangke: {
		sex: "male",
		group: "qun",
		hp: 4,
		clans: ["天上"],
		skills: ["swjw_yangbing", "swjw_xuren", "swjw_zhufeng"],
		img: "swjw_tianshangke.jpg",
		dieAudios: [`${ea}swjw_tianshangke/swjw_tianshangke.mp3`],
	},
	// 约会大作战
	// swyz_yuanyizhezhi: {
	// 	sex: "female",
	// 	group: 'key',
	// 	hp: 3,
	// 	skills: ["swyz_tianyi", "swyz_shengmian", "swyz_rilun", "swyz_paoguan"],
	// 	img: "swyz_yuanyizhezhi.jpg",
	// 	dieAudios: [`${ea}swyz_yuanyizhezhi/swyz_yuanyizhezhi.mp3`],
	// },
	// swyz_bentiaoerya: {
	// 	sex: "female",
	// 	group: 'key',
	// 	hp: 3,
	// 	skills: ["swyz_xiaolan", "swyz_niegao"],
	// 	img: "swyz_bentiaoerya.jpg",
	// 	dieAudios: [`${ea}swyz_bentiaoerya/swyz_bentiaoerya.mp3`],
	// },
	swyz_shiqikuangsan: {
		sex: "female",
		group: 'key',
		hp: 3,
		skills: ["swyz_shiyu", "swyz_shiyan"],
		img: "swyz_shiqikuangsan.jpg",
		dieAudios: [`${ea}swyz_shiqikuangsan/swyz_shiqikuangsan.mp3`],
	},
	// swyz_bingyachuansisinai: {
	// 	sex: "female",
	// 	group: 'key',
	// 	hp: 3,
	// 	hujia: 1,
	// 	skills: ["swyz_hanqiao", "swyz_xueyin", "swyz_dongjie"],
	// 	img: "swyz_bingyachuansisinai.jpg",
	// 	dieAudios: [`${ea}swyz_bingyachuansisinai/swyz_bingyachuansisinai.mp3`],
	// },
	// swyz_wuheqinli: {
	// 	sex: "female",
	// 	group: 'key',
	// 	hp: 3,
	// 	skills: ["swyz_chizhuo", "swyz_chongran", "swyz_yanxi"],
	// 	img: "swyz_wuheqinli.jpg",
	// 	dieAudios: [`${ea}swyz_wuheqinli/swyz_wuheqinli.mp3`],
	// },
	// swyz_xinggongliucan: {
	// 	sex: "female",
	// 	group: 'key',
	// 	hp: 3,
	// 	maxHp: 6,
	// 	skills: ["swyz_bisuo", "swyz_xinyao", "swyz_fengjie"],
	// 	img: "swyz_xinggongliucan.jpg",
	// 	dieAudios: [`${ea}swyz_xinggongliucan/swyz_xinggongliucan.mp3`],
	// },
	// swyz_jingyeqizui: {
	// 	sex: "female",
	// 	group: 'key',
	// 	hp: 3,
	// 	skills: ["swyz_jingxiang", "swyz_fangxing"],
	// 	img: "swyz_jingyeqizui.jpg",
	// 	dieAudios: [`${ea}swyz_jingyeqizui/swyz_jingyeqizui.mp3`],
	// },
	// swyz_bawuyejushi: {
	// 	sex: "female",
	// 	group: 'key',
	// 	hp: 4,
	// 	skills: ["swyz_jufeng", "swyz_jichi", "swyz_shuangsheng2", "dualside"],
	// 	dualSideCharacter: "swyz_bawuxixian",
	// 	isAiForbidden: true,
	// 	img: "swyz_bawuyejushi.jpg",
	// 	dieAudios: [`${ea}swyz_bawuyejushi/swyz_bawuyejushi.mp3`],
	// },
	// swyz_bawuxixian: {
	// 	sex: "female",
	// 	group: 'key',
	// 	hp: 4,
	// 	skills: ["swyz_xieliao", "swyz_tianji", "swyz_shuangsheng2", "dualside"],
	// 	dualSideCharacter: "swyz_bawuyejushi",
	// 	isAiForbidden: true,
	// 	img: "swyz_bawuxixian.jpg",
	// 	dieAudios: [`${ea}swyz_bawuxixian/swyz_bawuxixian.mp3`],
	// },
	// swyz_bawushuangjiang: {
	// 	sex: "female",
	// 	group: 'key',
	// 	hp: 4,
	// 	skills: ["swyz_shuangsheng"],
	// 	img: "swyz_bawushuangjiang.jpg",
	// 	dieAudios: [`${ea}swyz_bawushuangjiang/swyz_bawushuangjiang.mp3`],
	// },
	// swyz_youxiaomeijiu: {
	// 	sex: "female",
	// 	group: 'key',
	// 	hp: 3,
	// 	skills: ["swyz_xiezou", "swyz_hexian"],
	// 	img: "swyz_youxiaomeijiu.jpg",
	// 	dieAudios: [`${ea}swyz_youxiaomeijiu/swyz_youxiaomeijiu.mp3`],
	// },
	// swyz_yedaoshenshixiang: {
	// 	sex: "female",
	// 	group: 'key',
	// 	hp: 4,
	// 	skills: ["swyz_zhongjian", "swyz_aosha"],
	// 	img: "swyz_yedaoshenshixiang.jpg",
	// 	dieAudios: [`${ea}swyz_yedaoshenshixiang/swyz_yedaoshenshixiang.mp3`],
	// },

	/*
			sw_lutiandilang: {
				sex: "male",
				group: 'key',
				hp: 3,
				maxHp: 4,
				skills: ['sw_renjie', 'sw_sanyang', 'sw_luguan', 'sw_xinhuo'],
				img: "image/character/qinlang.jpg",
			},
			sw_hepingshizhelang: {
				sex: "male",
				group: 'key',
				hp: 2,
				maxHp: 2,
				skills: ['sw_gugu', 'sw_heping', 'sw_shangzhuo'],
				trashBin: ['character:qinlang']
			},
			sw_shouwang: {
				sex: "female",
				group: 'key',
				hp: 2,
				maxHp: 4,
				hujia: 2,
				skills: ['sw_tongpin', 'sw_kelian'],
				trashBin: ['character:key_abyusa']
			},
			sw_shenshouwang: {
				sex: "female",
				group: 'shen',
				hp: 3,
				maxHp: 7,
				skills: ['sw_tonghun', 'shiki_omusubi'],
				trashBin: ['character:key_abyusa']
			},
			sw_shenqinlang: {
				sex: "male",
				group: 'shen',
				hp: 4,
				maxHp: 7,
				skills: ['sw_nanchong', 'sw_weige'],
				trashBin: ['character:qinlang']
			},
			sw_gushenlangfeite: {
				sex: "male",
				group: 'shen',
				hp: 3,
				maxHp: 3,
				skills: ['sw_shangshi', 'sw_kaipan'],
				trashBin: ['character:qinlang']
			},
			sw_shenaoliao: {
				sex: "male",
				group: 'shen',
				hp: 3,
				maxHp: 3,
				skills: ['sw_kanpo', 'sw_zhinang'],
				trashBin: ['character:sb_sp_zhugeliang']
			},



	 */

	
}
