import { lib } from "noname";

const characters = {
    nysgs_shen_zhenji: {
        sex: "female",
        group: "shen",
        hp: 6,
        skills: ["nysgs_shen_zhenji_skill", "nysgs_shen_zhenji_skill2", "nysgs_shen_zhenji_skill3"],
        trashBin: [],
        dieAudios: [],
        runestone: ["nysgs_fs_shen_zhenji"],
    },
    nysgs_zhenji: {
        sex: "female",
        group: "wei",
        hp: 7,
        skills: ["nysgs_zhenji_skill", "nysgs_zhenji_skill2", "nysgs_zhenji_skill3"],
        trashBin: [],
        dieAudios: [],
        runestone: ["nysgs_fs_zhenji"],
    },
    nysgs_caopi: {
        sex: "male",
        group: "wei",
        hp: 7,
        skills: ["nysgs_caopi_skill", "nysgs_caopi_skill2", "nysgs_caopi_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_caopi_death"],
        runestone: ["nysgs_fs_caopi"],
    },
    nysgs_xinxianying: {
        sex: "female",
        group: "wei",
        hp: 7,
        skills: ["nysgs_xinxianying_skill", "nysgs_xinxianying_skill2", "nysgs_xinxianying_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_xinxianying_death"],
        runestone: ["nysgs_fs_xinxianying"],
    },
    nysgs_xizhicai: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_xizhicai_skill", "nysgs_xizhicai_skill2", "nysgs_xizhicai_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_xizhicai_death"],
        runestone: ["nysgs_fs_xizhicai"],
    },
    nysgs_caorui: {
        sex: "male",
        group: "wei",
        hp: 7,
        skills: ["nysgs_caorui_skill", "nysgs_caorui_skill2", "nysgs_caorui_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_caorui_death"],
        runestone: ["nysgs_fs_caorui"],
    },
    nysgs_chengyu: {
        sex: "male",
        group: "wei",
        hp: 7,
        skills: ["nysgs_chengyu_skill", "nysgs_chengyu_skill2", "nysgs_chengyu_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_chengyu_death"],
        runestone: ["nysgs_fs_chengyu"],
    },
    nysgs_guozhao: {
        sex: "female",
        group: "wei",
        hp: 7,
        skills: ["nysgs_guozhao_skill", "nysgs_guozhao_skill2", "nysgs_guozhao_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_guozhao_death"],
        runestone: ["nysgs_fs_guozhao"],
    },
    nysgs_caoying: {
        sex: "female",
        group: "wei",
        hp: 6,
        skills: ["nysgs_caoying_skill", "nysgs_caoying_skill2", "nysgs_caoying_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_caoying_death"],
        runestone: ["nysgs_fs_caoying"],
    },
    nysgs_wei_wenyang: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_wei_wenyang_skill", "nysgs_wenyang_skill2", "nysgs_wei_wenyang_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_wenyang_death"],
        runestone: ["nysgs_fs_wei_wenyang"],
    },
    nysgs_bianfuren: {
        sex: "female",
        group: "wei",
        hp: 6,
        skills: ["nysgs_bianfuren_skill", "nysgs_bianfuren_skill2", "nysgs_bianfuren_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_bianfuren_death"],
        runestone: ["nysgs_fs_bianfuren"],
    },
    nysgs_caochun: {
        sex: "male",
        group: "wei",
        hp: 7,
        skills: ["nysgs_caochun_skill", "nysgs_caochun_skill2", "nysgs_caochun_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_caochun_death"],
        runestone: ["nysgs_fs_caochun"],
    },
    nysgs_yanghuiyu: {
        sex: "female",
        group: "wei",
        hp: 6,
        skills: ["nysgs_yanghuiyu_skill", "nysgs_yanghuiyu_skill2", "nysgs_yanghuiyu_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_yanghuiyu_death"],
        runestone: ["nysgs_fs_yanghuiyu"],
    },
    nysgs_wangyuanji: {
        sex: "female",
        group: "wei",
        hp: 6,
        skills: ["nysgs_wangyuanji_skill", "nysgs_wangyuanji_skill2", "nysgs_wangyuanji_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_wangyuanji_death"],
        runestone: ["nysgs_fs_wangyuanji"],
    },
    nysgs_caomao: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_caomao_skill", "nysgs_caomao_skill2", "nysgs_caomao_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_caomao_death"],
        runestone: ["nysgs_fs_caomao"],
    },
    nysgs_caizhenji: {
        sex: "female",
        group: "wei",
        hp: 6,
        skills: ["nysgs_caizhenji_skill", "nysgs_caizhenji_skill2", "nysgs_caizhenji_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_caizhenji_death"],
        runestone: ["nysgs_fs_caizhenji"],
    },
    nysgs_chenlin: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_chenlin_skill", "nysgs_chenlin_skill2", "nysgs_chenlin_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_chenlin_death"],
        runestone: ["nysgs_fs_chenlin"],
    },
    nysgs_mou_simayi: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_mou_simayi_skill", "nysgs_mou_simayi_skill2", "nysgs_mou_simayi_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_mou_simayi_death"],
        runestone: ["nysgs_fs_mou_simayi"],
    },
    nysgs_mou_caocao: {
        sex: "male",
        group: "wei",
        hp: 7,
        skills: ["nysgs_mou_caocao_skill", "nysgs_mou_caocao_skill2", "nysgs_mou_caocao_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_mou_caocao_death"],
        runestone: ["nysgs_fs_mou_caocao"],
    },
    nysgs_huan_caiwenji: {
        sex: "female",
        group: "wei",
        hp: 6,
        skills: ["nysgs_huan_caiwenji_skill", "nysgs_huan_caiwenji_skill2", "nysgs_huan_caiwenji_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_huan_caiwenji_death"],
        runestone: ["nysgs_fs_huan_caiwenji"],
    },
    nysgs_xiahoudun: {
        sex: "male",
        group: "wei",
        hp: 7,
        skills: ["nysgs_xiahoudun_skill", "nysgs_xiahoudun_skill2", "nysgs_xiahoudun_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_xiahoudun_death"],
        runestone: ["nysgs_fs_xiahoudun"],
    },
    nysgs_guojia: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_guojia_skill", "nysgs_guojia_skill2", "nysgs_guojia_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_guojia_death"],
        runestone: ["nysgs_fs_guojia"],
    },
    nysgs_simayi: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_simayi_skill", "nysgs_simayi_skill2", "nysgs_simayi_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_simayi_death"],
        runestone: ["nysgs_fs_simayi"],
    },
    nysgs_xiahouyuan: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_xiahouyuan_skill", "nysgs_xiahouyuan_skill2", "nysgs_xiahouyuan_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_xiahouyuan_death"],
        runestone: ["nysgs_fs_xiahouyuan"],
    },
    nysgs_caoren: {
        sex: "male",
        group: "wei",
        hp: 7,
        skills: ["nysgs_caoren_skill", "nysgs_caoren_skill2", "nysgs_caoren_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_caoren_death"],
        runestone: ["nysgs_fs_caoren"],
    },
    nysgs_dianwei: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_dianwei_skill", "nysgs_dianwei_skill2", "nysgs_dianwei_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_dianwei_death"],
        runestone: ["nysgs_fs_dianwei"],
    },
    nysgs_caocao: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_caocao_skill", "nysgs_caocao_skill2", "nysgs_caocao_skill3"],
        trashBin: [],
        runestone: ["nysgs_fs_caocao"],
    },
    nysgs_dengai: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_dengai_skill", "nysgs_dengai_skill2", "nysgs_dengai_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_dengai_death"],
        runestone: ["nysgs_fs_dengai"],
    },
    nysgs_zhangliao: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_zhangliao_skill", "nysgs_zhangliao_skill2", "nysgs_zhangliao_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_zhangliao_death"],
        runestone: ["nysgs_fs_zhangliao"],
    },
    nysgs_xuchu: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_xuchu_skill", "nysgs_xuchu_skill2", "nysgs_xuchu_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_xuchu_death"],
        runestone: ["nysgs_fs_xuchu"],
    },
    nysgs_zhangchunhua: {
        sex: "female",
        group: "wei",
        hp: 6,
        skills: ["nysgs_zhangchunhua_skill", "nysgs_zhangchunhua_skill2", "nysgs_zhangchunhua_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_zhangchunhua_death"],
        runestone: ["nysgs_fs_zhangchunhua"],
    },
    nysgs_caozhi: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_caozhi_skill", "nysgs_caozhi_skill2", "nysgs_caozhi_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_caozhi_death"],
        runestone: ["nysgs_fs_caozhi"],
    },
    nysgs_caochong: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_caochong_skill", "nysgs_caochong_skill2", "nysgs_caochong_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_caochong_death"],
        runestone: ["nysgs_fs_caochong"],
    },
    nysgs_caozhang: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_caozhang_skill", "nysgs_caozhang_skill2", "nysgs_caozhang_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_caozhang_death"],
        runestone: ["nysgs_fs_caozhang"],
    },
    nysgs_wangyi: {
        sex: "female",
        group: "wei",
        hp: 6,
        skills: ["nysgs_wangyi_skill", "nysgs_wangyi_skill2", "nysgs_wangyi_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_wangyi_death"],
        runestone: ["nysgs_fs_wangyi"],
    },
    nysgs_xunyu: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_xunyu_skill", "nysgs_xunyu_skill2", "nysgs_xunyu_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_xunyu_death"],
        runestone: ["nysgs_fs_xunyu"],
    },
    nysgs_xuhuang: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_xuhuang_skill", "nysgs_xuhuang_skill2", "nysgs_xuhuang_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_xuhuang_death"],
        runestone: ["nysgs_fs_xuhuang"],
    },
    nysgs_xunyou: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_xunyou_skill", "nysgs_xunyou_skill2", "nysgs_xunyou_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_xunyou_death"],
        runestone: ["nysgs_fs_xunyou"],
    },
    nysgs_yujin: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_yujin_skill", "nysgs_yujin_skill2", "nysgs_yujin_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_yujin_death"],
        runestone: ["nysgs_fs_yujin"],
    },
    nysgs_zhanghe: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_zhanghe_skill", "nysgs_zhanghe_skill2", "nysgs_zhanghe_skill3"],
        trashBin: [],
        runestone: ["nysgs_fs_zhanghe"],
    },
	nysgs_zhonghui: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_zhonghui_skill", "nysgs_zhonghui_skill2", "nysgs_zhonghui_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_zhonghui_death"],
        runestone: ["nysgs_fs_zhonghui"],
    },
    nysgs_caoang: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_caoang_skill", "nysgs_caoang_skill2", "nysgs_caoang_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_caoang_death"],
        runestone: ["nysgs_fs_caoang"],
    },
    nysgs_wangji: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_wangji_skill", "nysgs_wangji_skill2", "nysgs_wangji_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_wangji_death"],
        runestone: ["nysgs_fs_wangji"],
    },
    nysgs_chenqun: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_chenqun_skill", "nysgs_chenqun_skill2", "nysgs_chenqun_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_chenqun_death"],
        runestone: ["nysgs_fs_chenqun"],
    },
    nysgs_guanlu: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_guanlu_skill", "nysgs_guanlu_skill2", "nysgs_guanlu_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_guanlu_death"],
        runestone: ["nysgs_fs_guanlu"],
    },
    nysgs_yuejin: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_yuejin_skill", "nysgs_yuejin_skill2", "nysgs_yuejin_skill3"],
        trashBin: [],
        dieAudios: ["yuejin.mp3"],
        runestone: ["nysgs_fs_yuejin"],
    },
    nysgs_caojinyu: {
        sex: "female",
        group: "wei",
        hp: 6,
        skills: ["nysgs_caojinyu_skill", "nysgs_caojinyu_skill2", "nysgs_caojinyu_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_caojinyu_death"],
        runestone: ["nysgs_fs_caojinyu"],
    },
    nysgs_zhangchangpu: {
        sex: "female",
        group: "wei",
        hp: 6,
        skills: ["nysgs_yanjiao", "nysgs_jiaoziyoufang", "nysgs_xingshenjianli"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_zhangchangpu_death"],
        runestone: ["nysgs_fs_zhangchangpu"],
    },
    
	nysgs_zhaoyun: {
		sex: "male",
		group: "shu",
		hp: 7,
		skills: ["nysgs_zhaoyun_skill", "nysgs_zhaoyun_skill2", "nysgs_zhaoyun_skill3"],
		trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_zhaoyun_death"],
        runestone: ["nysgs_fs_zhaoyun"],
	},
	nysgs_wuyi: {
		sex: "male",
		group: "shu",
		hp: 7,
		skills: ["nysgs_wuyi_skill", "nysgs_wuyi_skill2", "nysgs_wuyi_skill3"],
		trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_wuyi_death"],
        runestone: ["nysgs_fs_wuyi"],
	},
	nysgs_mifuren: {
		sex: "female",
		group: "shu",
		hp: 7,
		skills: ["nysgs_mifuren_skill", "nysgs_mifuren_skill2", "nysgs_mifuren_skill3"],
		trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_mifuren_death"],
        runestone: ["nysgs_fs_mifuren"],
	},
	nysgs_zhugeliang: {
		sex: "male",
		group: "shu",
		hp: 7,
		skills: ["nysgs_zhugeliang_skill", "nysgs_zhugeliang_skill2", "nysgs_zhugeliang_skill3"],
		trashBin: [],
        dieAudios: ["zhugeliang"],
        runestone: ["nysgs_fs_zhugeliang"],
	},
	nysgs_dongyun: {
		sex: "male",
		group: "shu",
		hp: 7,
		skills: ["nysgs_dongyun_skill", "nysgs_dongyun_skill2", "nysgs_dongyun_skill3"],
		trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_dongyun_death"],
        runestone: ["nysgs_fs_dongyun"],
	},
	nysgs_guansuo: {
        sex: "male",
        group: "shu",
        hp: 7,
        skills: ["nysgs_guansuo_skill", "nysgs_guansuo_skill2", "nysgs_guansuo_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_guansuo_death"],
        runestone: ["nysgs_fs_guansuo"],
    },
	nysgs_baosanniang: {
        sex: "female",
        group: "shu",
        hp: 7,
        skills: ["nysgs_baosanniang_skill", "nysgs_baosanniang_skill2", "nysgs_baosanniang_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_baosanniang_death"],
        runestone: ["nysgs_fs_baosanniang"],
    },
    nysgs_xiahoushi: {
        sex: "female",
        group: "shu",
        hp: 6,
        skills: ["nysgs_xiahoushi_skill", "nysgs_xiahoushi_skill2", "nysgs_xiahoushi_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_xiahoushi_death"],
        runestone: ["nysgs_fs_xiahoushi"],
    },
    nysgs_ganfuren: {
        sex: "female",
        group: "shu",
        hp: 6,
        skills: ["nysgs_ganfuren_skill", "nysgs_ganfuren_skill2", "nysgs_ganfuren_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_ganfuren_death"],
        runestone: ["nysgs_fs_ganfuren"],
    },
    nysgs_zhaoxiang: {
        sex: "female",
        group: "shu",
        hp: 7,
        skills: ["nysgs_zhaoxiang_skill", "nysgs_zhaoxiang_skill2", "nysgs_zhaoxiang_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_zhaoxiang_death"],
        runestone: ["nysgs_fs_zhaoxiang"],
    },
    nysgs_zhugeguo: {
        sex: "female",
        group: "shu",
        hp: 7,
        skills: ["nysgs_zhugeguo_skill", "nysgs_zhugeguo_skill2", "nysgs_zhugeguo_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_zhugeguo_death"],
        runestone: ["nysgs_fs_zhugeguo"],
    },
    nysgs_huaman: {
        sex: "female",
        group: "shu",
        hp: 7,
        skills: ["nysgs_huaman_skill", "nysgs_huaman_skill2", "nysgs_huaman_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_huaman_death"],
        runestone: ["nysgs_fs_huaman"],
    },
    nysgs_zhugezhan: {
        sex: "male",
        group: "shu",
        hp: 7,
        skills: ["nysgs_zhugezhan_skill", "nysgs_zhugezhan_skill2", "nysgs_zhugezhan_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_zhugezhan_death"],
        runestone: ["nysgs_fs_zhugezhan"],
    },
    nysgs_yangwan: {
        sex: "female",
        group: "shu",
        hp: 6,
        skills: ["nysgs_yangwan_skill", "nysgs_yangwan_skill2", "nysgs_yangwan_skill3"],
        trashBin: [],
        dieAudios: [],
        runestone: ["nysgs_fs_yangwan"],
        isUnseen: true,
    },
    nysgs_wuxian: {
        sex: "female",
        group: "shu",
        hp: 7,
        skills: ["nysgs_wuxian_skill", "nysgs_wuxian_skill2", "nysgs_wuxian_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_wuxian_death"],
        runestone: ["nysgs_fs_wuxian"],
    },
    nysgs_puyuan: {
        sex: "male",
        group: "shu",
        hp: 7,
        skills: ["nysgs_puyuan_skill", "nysgs_puyuan_skill2", "nysgs_puyuan_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_puyuan_death"],
        runestone: ["nysgs_fs_puyuan"],
    },
    nysgs_mizhu: {
        sex: "male",
        group: "shu",
        hp: 8,
        skills: ["nysgs_mizhu_skill", "nysgs_mizhu_skill2", "nysgs_mizhu_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_mizhu_death"],
        runestone: ["nysgs_fs_mizhu"],
    },
    nysgs_hujinding: {
        sex: "female",
        group: "shu",
        hp: 6,
        skills: ["nysgs_hujinding_skill", "nysgs_hujinding_skill2", "nysgs_hujinding_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_hujinding_death"],
        runestone: ["nysgs_fs_hujinding"],
    },
    nysgs_malingli: {
        sex: "female",
        group: "shu",
        hp: 6,
        skills: ["nysgs_malingli_skill", "nysgs_malingli_skill2", "nysgs_malingli_skill3"],
        trashBin: [],
        dieAudios: [],
        runestone: ["nysgs_fs_malingli"],
        isUnseen: true,
    },
    nysgs_shen_huangzhong: {
        sex: "male",
        group: "shu",
        hp: 6,
        skills: ["nysgs_shen_huangzhong_skill", "nysgs_shen_huangzhong_skill2", "nysgs_shen_huangzhong_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_shen_huangzhong_death"],
        runestone: ["nysgs_fs_shen_huangzhong", "nysgs_fs_shen_huangzhong2"],
    },
    nysgs_mou_zhugeliang: {
        sex: "male",
        group: "shu",
        hp: 7,
        skills: ["nysgs_mou_zhugeliang_skill", "nysgs_mou_zhugeliang_skill2", "nysgs_mou_zhugeliang_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_mou_zhugeliang_death"],
        runestone: ["nysgs_fs_mou_zhugeliang"],
    },
    nysgs_wei_guanyu: {
        sex: "male",
        group: "shu",
        hp: 7,
        skills: ["nysgs_wei_guanyu_skill", "nysgs_wei_guanyu_skill2", "nysgs_wei_guanyu_skill3"],
        trashBin: [],
        dieAudios: ["die:wu_guanyu"],
        runestone: ["nysgs_fs_wei_guanyu"],
    },
    nysgs_huan_sunshangxiang: {
        sex: "female",
        group: "shu",
        hp: 7,
        skills: ["nysgs_huan_sunshangxiang_skill", "nysgs_huan_sunshangxiang_skill2", "nysgs_huan_sunshangxiang_skill3"],
        trashBin: [],
        dieAudios: [],
        runestone: ["nysgs_fs_huan_sunshangxiang"],
        isUnseen: true,
    },
    nysgs_liubei: {
        sex: "male",
        group: "shu",
        hp: 6,
        skills: ["nysgs_liubei_skill", "nysgs_liubei_skill2", "nysgs_liubei_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_liubei_death"],
        runestone: ["nysgs_fs_liubei"],
    },
    nysgs_guanyu: {
        sex: "male",
        group: "shu",
        hp: 7,
        skills: ["nysgs_guanyu_skill", "nysgs_guanyu_skill2", "nysgs_guanyu_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_guanyu_death"],
        runestone: ["nysgs_fs_guanyu"],
    },
    nysgs_huangyueying: {
        sex: "female",
        group: "shu",
        hp: 6,
        skills: ["nysgs_huangyueying_skill", "nysgs_huangyueying_skill2", "nysgs_huangyueying_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_huangyueying_death"],
        runestone: ["nysgs_fs_huangyueying"],
    },
    nysgs_huangzhong: {
        sex: "male",
        group: "shu",
        hp: 6,
        skills: ["nysgs_huangzhong_skill", "nysgs_huangzhong_skill2", "nysgs_huangzhong_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_huangzhong_death"],
        runestone: ["nysgs_fs_huangzhong"],
    },
    nysgs_zhangfei: {
        sex: "male",
        group: "shu",
        hp: 6,
        skills: ["nysgs_zhangfei_skill", "nysgs_zhangfei_skill2", "nysgs_zhangfei_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_zhangfei_death"],
        runestone: ["nysgs_fs_zhangfei"],
    },
    nysgs_weiyan: {
        sex: "male",
        group: "shu",
        hp: 7,
        skills: ["nysgs_weiyan_skill", "nysgs_weiyan_skill2", "nysgs_weiyan_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_weiyan_death"],
        runestone: ["nysgs_fs_weiyan"],
    },
    nysgs_liushan: {
        sex: "male",
        group: "shu",
        hp: 6,
        skills: ["nysgs_liushan_skill", "nysgs_liushan_skill2", "nysgs_liushan_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_liushan_death"],
        runestone: ["nysgs_fs_liushan"],
    },
    nysgs_zhangxingcai: {
        sex: "female",
        group: "shu",
        hp: 6,
        skills: ["nysgs_zhangxingcai_skill", "nysgs_zhangxingcai_skill2", "nysgs_zhangxingcai_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_zhangxingcai_death"],
        runestone: ["nysgs_fs_zhangxingcai"],
    },
    nysgs_pangtong: {
        sex: "male",
        group: "shu",
        hp: 6,
        skills: ["nysgs_pangtong_skill", "nysgs_pangtong_skill2", "nysgs_pangtong_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_pangtong_death"],
        runestone: ["nysgs_fs_pangtong"],
    },
    nysgs_masu: {
        sex: "male",
        group: "shu",
        hp: 6,
        skills: ["nysgs_masu_skill", "nysgs_masu_skill2", "nysgs_masu_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_masu_death"],
        runestone: ["nysgs_fs_masu"],
    },
    nysgs_xushu: {
        sex: "male",
        group: "shu",
        hp: 6,
        skills: ["nysgs_xushu_skill", "nysgs_xushu_skill2", "nysgs_xushu_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_xushu_death"],
        runestone: ["nysgs_fs_xushu"],
    },
    nysgs_liaohua: {
        sex: "male",
        group: "shu",
        hp: 7,
        skills: ["nysgs_liaohua_skill", "nysgs_liaohua_skill2", "nysgs_liaohua_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_liaohua_death"],
        runestone: ["nysgs_fs_liaohua"],
    },
    nysgs_guanping: {
        sex: "male",
        group: "shu",
        hp: 6,
        skills: ["nysgs_guanping_skill", "nysgs_guanping_skill2", "nysgs_guanping_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_guanping_death"],
        runestone: ["nysgs_fs_guanping"],
    },
    nysgs_zhouqun: {
        sex: "male",
        group: "shu",
        hp: 6,
        skills: ["nysgs_zhouqun_skill", "nysgs_zhouqun_skill2", "nysgs_zhouqun_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_zhouqun_death"],
        runestone: ["nysgs_fs_zhouqun"],
    },
    nysgs_yangyi: {
        sex: "male",
        group: "shu",
        hp: 7,
        skills: ["nysgs_yangyi_skill", "nysgs_yangyi_skill2", "nysgs_yangyi_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_yangyi_death"],
        runestone: ["nysgs_fs_yangyi"],
    },
    nysgs_sunce: {
        sex: "male",
        group: "wu",
        hp: 7,
        skills: ["nysgs_sunce_skill", "nysgs_sunce_skill2", "nysgs_sunce_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_sunce_death"],
        runestone: ["nysgs_fs_sunce"],
    },
    nysgs_bulianshi: {
        sex: "female",
        group: "wu",
        hp: 7,
        skills: ["nysgs_bulianshi_skill", "nysgs_bulianshi_skill2", "nysgs_bulianshi_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_bulianshi_death"],
        runestone: ["nysgs_fs_bulianshi"],
    },
    nysgs_taishici: {
        sex: "male",
        group: "wu",
        hp: 7,
        skills: ["nysgs_taishici_skill", "nysgs_taishici_skill2", "nysgs_taishici_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_taishici_death"],
        runestone: ["nysgs_fs_taishici"],
    },
    nysgs_sunhao: {
        sex: "male",
        group: "wu",
        hp: 7,
        skills: ["nysgs_sunhao_skill", "nysgs_sunhao_skill2", "nysgs_sunhao_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_sunhao_death"],
        runestone: ["nysgs_fs_sunhao"],
    },
    nysgs_liuzan: {
        sex: "male",
        group: "wu",
        hp: 7,
        skills: ["nysgs_liuzan_skill", "nysgs_liuzan_skill2", "nysgs_liuzan_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_liuzan_death"],
        runestone: ["nysgs_fs_liuzan"],
    },
    nysgs_luotong: {
        sex: "male",
        group: "wu",
        hp: 6,
        skills: ["nysgs_luotong_skill", "nysgs_luotong_skill2", "nysgs_luotong_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_luotong_death"],
        nysgsExclusive: ["nysgs_fs_luotong"],
    },
    nysgs_sunhanhua: {
        sex: "female",
        group: "wu",
        hp: 6,
        skills: ["nysgs_sunhanhua_skill", "nysgs_sunhanhua_skill2", "nysgs_sunhanhua_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_sunhanhua_death"],
        runestone: ["nysgs_fs_sunhanhua"],
    },
    nysgs_zhugejin: {
        sex: "male",
        group: "wu",
        hp: 7,
        skills: ["nysgs_zhugejin_skill", "nysgs_zhugejin_skill2", "nysgs_zhugejin_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_zhugejin_death"],
        runestone: ["nysgs_fs_zhugejin"],
    },
    nysgs_sunluyu: {
        sex: "female",
        group: "wu",
        hp: 7,
        skills: ["nysgs_sunluyu_skill", "nysgs_sunluyu_skill2", "nysgs_sunluyu_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_sunluyu_death"],
        runestone: ["nysgs_fs_sunluyu"],
    },
    nysgs_zhuran: {
        sex: "male",
        group: "wu",
        hp: 7,
        skills: ["nysgs_zhuran_skill", "nysgs_zhuran_skill2", "nysgs_zhuran_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_zhuran_death"],
        runestone: ["nysgs_fs_zhuran"],
    },
    nysgs_panshu: {
        sex: "female",
        group: "wu",
        hp: 6,
        skills: ["nysgs_panshu_skill", "nysgs_panshu_skill2", "nysgs_panshu_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_panshu_death"],
        runestone: ["nysgs_fs_panshu"],
    },
    nysgs_wu_wenyang: {
        sex: "male",
        group: "wu",
        hp: 7,
        skills: ["nysgs_wu_wenyang_skill", "nysgs_wenyang_skill2", "nysgs_wu_wenyang_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_wenyang_death"],
        runestone: ["nysgs_fs_wu_wenyang"],
    },
    nysgs_zhouchu: {
        sex: "male",
        group: "wu",
        hp: 6,
        skills: ["nysgs_zhouchu_skill", "nysgs_zhouchu_skill2", "nysgs_zhouchu_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_zhouchu_death"],
        runestone: ["nysgs_fs_zhouchu"],
    },
    nysgs_taohuang: {
        sex: "male",
        group: "wu",
        hp: 7,
        skills: ["nysgs_taohuang_skill", "nysgs_taohuang_skill2", "nysgs_taohuang_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_taohuang_death"],
        runestone: ["nysgs_fs_taohuang"],
    },
    nysgs_zhouyi: {
        sex: "female",
        group: "wu",
        hp: 5,
        maxHp: 7,
        skills: ["nysgs_zhouyi_skill", "nysgs_zhouyi_skill2", "nysgs_zhouyi_skill3"],
        trashBin: [],
        dieAudios: ["character:zhouyi"],
        runestone: ["nysgs_fs_zhouyi"],
    },
    nysgs_shen_sunjian: {
        sex: "male",
        group: "wu",
        hp: 1,
        maxHp: 8,
        skills: ["nysgs_shen_sunjian_skill", "nysgs_shen_sunjian_skill2", "nysgs_shen_sunjian_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_shen_sunjian_death"],
        runestone: ["nysgs_fs_shen_sunjian"],
    },
    nysgs_huan_xiaoqiao: {
        sex: "female",
        group: "wu",
        hp: 6,
        skills: ["nysgs_huan_xiaoqiao_skill", "nysgs_huan_xiaoqiao_skill2", "nysgs_huan_xiaoqiao_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_huan_xiaoqiao_death"],
        runestone: ["nysgs_fs_huan_xiaoqiao"],
        dualSideCharacter: "nysgs_huan_daqiao",
    },
    nysgs_huan_daqiao: {
        sex: "female",
        group: "wu",
        hp: 6,
        skills: ["nysgs_huan_daqiao_skill", "nysgs_huan_daqiao_skill2", "nysgs_huan_daqiao_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_huan_daqiao_death"],
        runestone: ["nysgs_fs_huan_daqiao"],
        dualSideCharacter: "nysgs_huan_xiaoqiao",
    },
    nysgs_mou_zhouyu: {
        sex: "male",
        group: "wu",
        hp: 7,
        skills: ["nysgs_mou_zhouyu_skill", "nysgs_mou_zhouyu_skill2", "nysgs_mou_zhouyu_skill3"],
        trashBin: [],
        dieAudios: ["character:dc_sb_zhouyu"],
        runestone: ["nysgs_fs_mou_zhouyu"],
    },
    nysgs_chengpu: {
        sex: "male",
        group: "wu",
        hp: 7,
        skills: ["nysgs_chengpu_skill", "nysgs_chengpu_skill2", "nysgs_chengpu_skill3"],
        trashBin: [],
        dieAudios: ["character:chengpu"],
        runestone: ["nysgs_fs_chengpu"],
    },
    nysgs_ganning: {
        sex: "male",
        group: "wu",
        hp: 7,
        skills: ["nysgs_ganning_skill", "nysgs_ganning_skill2", "nysgs_ganning_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_ganning_death"],
    },
    nysgs_luxun: {
        sex: "male",
        group: "wu",
        hp: 7,
        skills: ["nysgs_luxun_skill", "nysgs_luxun_skill2", "nysgs_luxun_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_luxun_death"],
    },
    nysgs_sunquan: {
        sex: "male",
        group: "wu",
        hp: 6,
        skills: ["nysgs_sunquan_skill", "nysgs_sunquan_skill2", "nysgs_sunquan_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_sunquan_death"],
    },
    nysgs_sunjian: {
        sex: "male",
        group: "wu",
        hp: 6,
        skills: ["nysgs_sunjian_skill", "nysgs_sunjian_skill2", "nysgs_sunjian_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_sunjian_death"],
    },
    nysgs_wuguotai: {
        sex: "female",
        group: "wu",
        hp: 6,
        skills: ["nysgs_wuguotai_skill", "nysgs_wuguotai_skill2", "nysgs_wuguotai_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_wuguotai_death"],
    },
    
    nysgs_lvbu: {
        sex: "male",
        group: "qun",
        hp: 8,
        skills: ["nysgs_lvbu_skill", "nysgs_lvbu_skill2", "nysgs_lvbu_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_lvbu_death"],
        runestone: ["nysgs_fs_lvbu"],
    },
    nysgs_caiwenji: {
        sex: "female",
        group: "qun",
        hp: 8,
        skills: ["nysgs_caiwenji_skill", "nysgs_caiwenji_skill2", "nysgs_caiwenji_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_caiwenji_death"],
        runestone: ["nysgs_fs_caiwenji"],
    },
    nysgs_jiaxu: {
        sex: "male",
        group: "qun",
        hp: 7,
        skills: ["nysgs_jiaxu_skill", "nysgs_jiaxu_skill2", "nysgs_jiaxu_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_jiaxu_death"],
        runestone: ["nysgs_fs_jiaxu"],
    },
    nysgs_yuji: {
        sex: "male",
        group: "qun",
        hp: 7,
        skills: ["nysgs_yuji_skill", "nysgs_yuji_skill2", "nysgs_yuji_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_yuji_death"],
        runestone: ["nysgs_fs_yuji"],
    },
    nysgs_liru: {
        sex: "male",
        group: "qun",
        hp: 7,
        skills: ["nysgs_liru_skill", "nysgs_liru_skill2", "nysgs_liru_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_liru_death"],
        runestone: ["nysgs_fs_liru"],
    },
    nysgs_lingju: {
        sex: "female",
        group: "qun",
        hp: 7,
        skills: ["nysgs_lingju_skill", "nysgs_lingju_skill2", "nysgs_lingju_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_lingju_death"],
        runestone: ["nysgs_fs_lingju"],
    },
    nysgs_simahui: {
        sex: "male",
        group: "qun",
        hp: 6,
        skills: ["nysgs_simahui_skill", "nysgs_simahui_skill2", "nysgs_simahui_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_simahui_death"],
        runestone: ["nysgs_fs_simahui"],
    },
    nysgs_lvlingqi: {
        sex: "female",
        group: "qun",
        hp: 7,
        skills: ["nysgs_lvlingqi_skill", "nysgs_lvlingqi_skill2", "nysgs_lvlingqi_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_lvlingqi_death"],
        runestone: ["nysgs_fs_lvlingqi"],
    },
    nysgs_nanhualaoxian: {
        sex: "male",
        group: "qun",
        hp: 6,
        skills: ["nysgs_nanhualaoxian_skill", "nysgs_nanhualaoxian_skill2", "nysgs_nanhualaoxian_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_nanhualaoxian_death"],
        runestone: ["nysgs_fs_nanhualaoxian"],
    },
    nysgs_liuyan: {
        sex: "male",
        group: "qun",
        hp: 7,
        skills: ["nysgs_liuyan_skill", "nysgs_liuyan_skill2", "nysgs_liuyan_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_liuyan_death"],
        runestone: ["nysgs_fs_liuyan"],
    },
    nysgs_zuoci: {
        sex: "male",
        group: "qun",
        hp: 7,
        skills: ["nysgs_zuoci_skill", "nysgs_zuoci_skill2", "nysgs_zuoci_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_zuoci_death"],
        runestone: ["nysgs_fs_zuoci"],
    },
    nysgs_xurong: {
        sex: "male",
        group: "qun",
        hp: 6,
        skills: ["nysgs_xurong_skill", "nysgs_xurong_skill2", "nysgs_xurong_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_xurong_death"],
        runestone: ["nysgs_fs_xurong"],
    },
    nysgs_zhangxiu: {
        sex: "male",
        group: "qun",
        hp: 6,
        skills: ["nysgs_zhangxiu_skill", "nysgs_zhangxiu_skill2", "nysgs_zhangxiu_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_zhangxiu_death"],
        runestone: ["nysgs_fs_zhangxiu"],
    },
    nysgs_zhangqiying: {
        sex: "female",
        group: "qun",
        hp: 6,
        skills: ["nysgs_zhangqiying_skill", "nysgs_zhangqiying_skill2", "nysgs_zhangqiying_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_zhangqiying_death"],
        runestone: ["nysgs_fs_zhangqiying"],
        isUnseen: true,
    },
    nysgs_pangdegong: {
        sex: "male",
        group: "qun",
        hp: 6,
        skills: ["nysgs_pangdegong_skill", "nysgs_pangdegong_skill2", "nysgs_pangdegong_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_pangdegong_death"],
        runestone: ["nysgs_fs_pangdegong"],
    },
    nysgs_dongxie: {
        sex: "female",
        group: "qun",
        hp: 6,
        skills: ["nysgs_dongxie_skill", "nysgs_dongxie_skill2", "nysgs_dongxie_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_dongxie_death"],
        runestone: ["nysgs_fs_dongxie"],
    },
    nysgs_quyi: {
        sex: "male",
        group: "qun",
        hp: 6,
        skills: ["nysgs_quyi_skill", "nysgs_quyi_skill2", "nysgs_quyi_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_quyi_death"],
        runestone: ["nysgs_fs_quyi"],
    },
    nysgs_huan_zhangchu: {
        sex: "female",
        group: "qun",
        hp: 7,
        skills: ["nysgs_huan_zhangchu_skill", "nysgs_huan_zhangchu_skill2", "nysgs_huan_zhangchu_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_huan_zhangchu_death"],
        runestone: ["nysgs_fs_huan_zhangchu"],
    },
    nysgs_wei_machao: {
        sex: "male",
        group: "qun",
        hp: 7,
        skills: ["nysgs_wei_machao_skill", "nysgs_wei_machao_skill2", "nysgs_wei_machao_skill3"],
        trashBin: [],
        dieAudios: [],
        runestone: ["nysgs_fs_wei_machao"],
        isUnseen: true,
    },
    nysgs_diaochan: {
        sex: "female",
        group: "qun",
        hp: 6,
        skills: ["nysgs_diaochan_skill", "nysgs_diaochan_skill2", "nysgs_diaochan_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_diaochan_death"],
    },
    nysgs_dongzhuo: {
        sex: "male",
        group: "qun",
        hp: 7,
        skills: ["nysgs_dongzhuo_skill", "nysgs_dongzhuo_skill2", "nysgs_dongzhuo_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_dongzhuo_death"],
    },
    nysgs_zhangjiao: {
        sex: "male",
        group: "qun",
        hp: 6,
        skills: ["nysgs_zhangjiao_skill", "nysgs_zhangjiao_skill2", "nysgs_zhangjiao_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_zhangjiao_death"],
    },
    nysgs_pangde: {
        sex: "male",
        group: "qun",
        hp: 7,
        skills: ["nysgs_pangde_skill", "nysgs_pangde_skill2", "nysgs_pangde_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_pangde_death"],
        runestone: [],
    },
    nysgs_zhurong: {
        sex: "female",
        group: "qun",
        hp: 6,
        skills: ["nysgs_zhurong_skill", "nysgs_zhurong_skill2", "nysgs_zhurong_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_zhurong_death"],
        runestone: [],
    },
    nysgs_menghuo: {
        sex: "male",
        group: "qun",
        hp: 7,
        skills: ["nysgs_menghuo_skill", "nysgs_menghuo_skill2", "nysgs_menghuo_skill3"],
        trashBin: [],
        dieAudios: [],
        runestone: [],
    },
    nysgs_yuanshao: {
        sex: "male",
        group: "qun",
        hp: 6,
        skills: ["nysgs_yuanshao_skill", "nysgs_yuanshao_skill2", "nysgs_yuanshao_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_yuanshao_death"],
    },
    nysgs_huatuo: {
        sex: "male",
        group: "qun",
        hp: 6,
        skills: ["nysgs_huatuo_skill", "nysgs_huatuo_skill2", "nysgs_huatuo_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_huatuo_death"],
    },
    nysgs_gongsunzan: {
        sex: "male",
        group: "qun",
        hp: 6,
        skills: ["nysgs_gongsunzan_skill", "nysgs_gongsunzan_skill2", "nysgs_gongsunzan_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_gongsunzan_death"],
    },
    nysgs_caifuren: {
        sex: "female",
        group: "qun",
        hp: 6,
        skills: ["nysgs_caifuren_skill", "nysgs_caifuren_skill2", "nysgs_caifuren_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_caifuren_death"],
    },
    nysgs_liuqi: {
        sex: "male",
        group: "qun",
        hp: 6,
        skills: ["nysgs_liuqi_skill", "nysgs_liuqi_skill2", "nysgs_liuqi_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_liuqi_death"],
    },
};

for (let i in characters) {
    characters[i].trashBin.push(`ext:怒焰三国/image/character/${i}.jpg`);
}

const characters2 = {
    nysgs_jie_yuanshao: {
        sex: "male",
        group: "qun",
        hp: 6,
        skills: ["nysgs_jie_yuanshao_skill", "nysgs_jie_yuanshao_skill2", "nysgs_jie_yuanshao_skill3"],
        trashBin: [],
    },
    nysgs_jie_dongzhuo: {
        sex: "male",
        group: "qun",
        hp: 7,
        skills: ["nysgs_jie_dongzhuo_skill", "nysgs_jie_dongzhuo_skill2", "nysgs_jie_dongzhuo_skill3"],
        trashBin: [],
    },
    nysgs_jie_caoren: {
        sex: "male",
        group: "wei",
        hp: 7,
        skills: ["nysgs_jie_caoren_skill", "nysgs_jie_caoren_skill2", "nysgs_jie_caoren_skill3"],
        trashBin: [],
    },
    nysgs_jie_xiahouyuan: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_jie_xiahouyuan_skill", "nysgs_jie_xiahouyuan_skill2", "nysgs_jie_xiahouyuan_skill3"],
        trashBin: [],
    },
    nysgs_jie_caocao: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_jie_caocao_skill", "nysgs_jie_caocao_skill2", "nysgs_jie_caocao_skill3"],
        trashBin: [],
    },
    nysgs_jie_dianwei: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_jie_dianwei_skill", "nysgs_jie_dianwei_skill2", "nysgs_jie_dianwei_skill3"],
        trashBin: [],
    },
    nysgs_jie_dengai: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_jie_dengai_skill", "nysgs_jie_dengai_skill2", "nysgs_jie_dengai_skill3"],
        trashBin: [],
    },
    nysgs_jie_zhangliao: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_jie_zhangliao_skill", "nysgs_jie_zhangliao_skill2", "nysgs_jie_zhangliao_skill3"],
        trashBin: [],
    },
    nysgs_jie_xuchu: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_jie_xuchu_skill", "nysgs_jie_xuchu_skill2", "nysgs_jie_xuchu_skill3"],
        trashBin: [],
    },
    nysgs_jie_simayi: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_jie_simayi_skill", "nysgs_jie_simayi_skill2", "nysgs_jie_simayi_skill3"],
        trashBin: [],
    },
    nysgs_jie_gongsunzan: {
        sex: "male",
        group: "qun",
        hp: 6,
        skills: ["nysgs_jie_gongsunzan_skill", "nysgs_jie_gongsunzan_skill2", "nysgs_jie_gongsunzan_skill3"],
        trashBin: [],
    },
    nysgs_jie_caifuren: {
        sex: "female",
        group: "qun",
        hp: 6,
        skills: ["nysgs_jie_caifuren_skill", "nysgs_jie_caifuren_skill2", "nysgs_jie_caifuren_skill3"],
        trashBin: [],
    },
     nysgs_jie_pangtong: {
        sex: "male",
        group: "shu",
        hp: 6,
        skills: ["nysgs_jie_pangtong_skill", "nysgs_jie_pangtong_skill2", "nysgs_jie_pangtong_skill3"],
        trashBin: [],
    },
    nysgs_jie_zhangjiao: {
        sex: "male",
        group: "qun",
        hp: 6,
        skills: ["nysgs_jie_zhangjiao_skill", "nysgs_jie_zhangjiao_skill2", "nysgs_jie_zhangjiao_skill3"],
        trashBin: [],
    },
    nysgs_jie_pangde: {
        sex: "male",
        group: "qun",
        hp: 7,
        skills: ["nysgs_jie_pangde_skill", "nysgs_jie_pangde_skill2", "nysgs_jie_pangde_skill3"],
        trashBin: [],
        dieAudios: [],
    },
    nysgs_jie_zhurong: {
        sex: "female",
        group: "qun",
        hp: 6,
        skills: ["nysgs_jie_zhurong_skill", "nysgs_jie_zhurong_skill2", "nysgs_jie_zhurong_skill3"],
        trashBin: [],
        dieAudios: [],
        runestone: [],
    },
    nysgs_jie_menghuo: {
        sex: "male",
        group: "qun",
        hp: 7,
        skills: ["nysgs_jie_menghuo_skill", "nysgs_jie_menghuo_skill2", "nysgs_jie_menghuo_skill3"],
        trashBin: [],
        dieAudios: [],
        runestone: [],
    },
    nysgs_jie_wuguotai: {
        sex: "female",
        group: "wu",
        hp: 6,
        skills: ["nysgs_jie_wuguotai_skill", "nysgs_jie_wuguotai_skill2", "nysgs_jie_wuguotai_skill3"],
        trashBin: [],
    },
    nysgs_jie_liushan: {
        sex: "male",
        group: "shu",
        hp: 6,
        skills: ["nysgs_jie_liushan_skill", "nysgs_jie_liushan_skill2", "nysgs_jie_liushan_skill3"],
        trashBin: [],
    },
    nysgs_jie_xushu: {
        sex: "male",
        group: "shu",
        hp: 6,
        skills: ["nysgs_jie_xushu_skill", "nysgs_jie_xushu_skill2", "nysgs_jie_xushu_skill3"],
        trashBin: [],
    },
    nysgs_jie_guanping: {
        sex: "male",
        group: "shu",
        hp: 6,
        skills: ["nysgs_jie_guanping_skill", "nysgs_jie_guanping_skill2", "nysgs_jie_guanping_skill3"],
        trashBin: [],
        runestone: [],
    },
    nysgs_jie_zhouqun: {
        sex: "male",
        group: "shu",
        hp: 6,
        skills: ["nysgs_jie_zhouqun_skill", "nysgs_jie_zhouqun_skill2", "nysgs_jie_zhouqun_skill3"],
        trashBin: [],
        runestone: [],
    },
    nysgs_jie_yangyi: {
        sex: "male",
        group: "shu",
        hp: 7,
        skills: ["nysgs_jie_yangyi_skill", "nysgs_jie_yangyi_skill2", "nysgs_jie_yangyi_skill3"],
        trashBin: [],
        runestone: [],
    },
    nysgs_jie_chenqun: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_jie_chenqun_skill", "nysgs_jie_chenqun_skill2", "nysgs_jie_chenqun_skill3"],
        trashBin: [],
    },
    nysgs_jie_guanlu: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_jie_guanlu_skill", "nysgs_jie_guanlu_skill2", "nysgs_jie_guanlu_skill3"],
        trashBin: [],
    },
    nysgs_jie_yuejin: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_jie_yuejin_skill", "nysgs_jie_yuejin_skill2", "nysgs_jie_yuejin_skill3"],
        trashBin: [],
    },
    nysgs_jie_sunquan: {
        sex: "male",
        group: "wu",
        hp: 6,
        skills: ["nysgs_jie_sunquan_skill", "nysgs_jie_sunquan_skill2", "nysgs_jie_sunquan_skill3"],
        trashBin: [],
    },
    nysgs_jie_zhangxingcai: {
        sex: "female",
        group: "shu",
        hp: 6,
        skills: ["nysgs_jie_zhangxingcai_skill", "nysgs_jie_zhangxingcai_skill2", "nysgs_jie_zhangxingcai_skill3"],
        trashBin: [],
    },
    nysgs_jie_liubei: {
        sex: "male",
        group: "shu",
        hp: 6,
        skills: ["nysgs_jie_liubei_skill", "nysgs_jie_liubei_skill2", "nysgs_jie_liubei_skill3"],
        trashBin: [],
    },
    nysgs_jie_guanyu: {
        sex: "male",
        group: "shu",
        hp: 7,
        skills: ["nysgs_jie_wusheng", "nysgs_jie_guanyu_skill2", "nysgs_jie_guanyu_skill3"],
        trashBin: [],
    },
    nysgs_jie_huangyueying: {
        sex: "female",
        group: "shu",
        hp: 6,
        skills: ["nysgs_jie_huangyueying_skill", "nysgs_jie_huangyueying_skill2", "nysgs_jie_huangyueying_skill3"],
        trashBin: [],
    },
    nysgs_jie_huangzhong: {
        sex: "male",
        group: "shu",
        hp: 6,
        skills: ["nysgs_jie_huangzhong_skill", "nysgs_jie_huangzhong_skill2", "nysgs_jie_huangzhong_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_jie_huangzhong_death"],
    },
    nysgs_jie_zhangfei: {
        sex: "male",
        group: "shu",
        hp: 6,
        skills: ["nysgs_jie_zhangfei_skill", "nysgs_jie_zhangfei_skill2", "nysgs_jie_zhangfei_skill3"],
        trashBin: [],
    },
    nysgs_jie_liaohua: {
        sex: "male",
        group: "shu",
        hp: 7,
        skills: ["nysgs_jie_dangxian", "nysgs_jie_liaohua_skill2", "nysgs_jie_liaohua_skill3"],
        trashBin: [],
    },
    nysgs_jie_zhonghui: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_jie_zhonghui_skill", "nysgs_jie_zhonghui_skill2", "nysgs_jie_zhonghui_skill3"],
        trashBin: [],
    },
    nysgs_jie_diaochan: {
        sex: "female",
        group: "qun",
        hp: 6,
        skills: ["nysgs_jie_diaochan_skill", "nysgs_jie_diaochan_skill2", "nysgs_jie_diaochan_skill3"],
        trashBin: [],
    },
    nysgs_jie_xunyou: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_jie_xunyou_skill", "nysgs_jie_xunyou_skill2", "nysgs_jie_xunyou_skill3"],
        trashBin: [],
    },
    nysgs_jie_yujin: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_jie_yujin_skill", "nysgs_jie_yujin_skill2", "nysgs_jie_yujin_skill3"],
        trashBin: [],
    },
    nysgs_jie_zhanghe: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_jie_zhanghe_skill", "nysgs_jie_zhanghe_skill2", "nysgs_jie_zhanghe_skill3"],
        trashBin: [],
    },
    nysgs_jie_caoang: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_jie_caoang_skill", "nysgs_jie_caoang_skill2", "nysgs_jie_caoang_skill3"],
        trashBin: [],
    },
    nysgs_jie_wangji: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_jie_qizhi", "nysgs_jie_wangji_skill2", "nysgs_jie_wangji_skill3"],
        trashBin: [],
    },
    nysgs_jie_caojinyu: {
        sex: "female",
        group: "wei",
        hp: 6,
        skills: ["nysgs_jie_caojinyu_skill", "nysgs_jie_caojinyu_skill2", "nysgs_jie_caojinyu_skill3"],
        trashBin: [],
    },
    nysgs_jie_zhangchangpu: {
        sex: "female",
        group: "wei",
        hp: 6,
        skills: ["nysgs_jie_yanjiao", "nysgs_jie_jiaoziyoufang", "nysgs_jie_xingshenjianli"],
        trashBin: [],
    },
    nysgs_jie_zhangchunhua: {
        sex: "female",
        group: "wei",
        hp: 6,
        skills: ["nysgs_jie_zhangchunhua_skill", "nysgs_jie_zhangchunhua_skill2", "nysgs_jie_zhangchunhua_skill3"],
        trashBin: [],
    },
    nysgs_jie_caozhi: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_jie_caozhi_skill", "nysgs_jie_caozhi_skill2", "nysgs_jie_caozhi_skill3"],
        trashBin: [],
    },
    nysgs_jie_caochong: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_jie_caochong_skill", "nysgs_jie_caochong_skill2", "nysgs_jie_caochong_skill3"],
        trashBin: [],
    },
    nysgs_jie_caozhang: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_jie_caozhang_skill", "nysgs_jie_caozhang_skill2", "nysgs_jie_caozhang_skill3"],
        trashBin: [],
    },
    nysgs_jie_wangyi: {
        sex: "female",
        group: "wei",
        hp: 6,
        skills: ["nysgs_jie_wangyi_skill", "nysgs_jie_wangyi_skill2", "nysgs_jie_wangyi_skill3"],
        trashBin: [],
    },
    nysgs_jie_xunyu: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_jie_xunyu_skill", "nysgs_jie_xunyu_skill2", "nysgs_jie_xunyu_skill3"],
        trashBin: [],
    },
    nysgs_jie_xuhuang: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_jie_xuhuang_skill", "nysgs_jie_xuhuang_skill2", "nysgs_jie_xuhuang_skill3"],
        trashBin: [],
    },
    nysgs_jie_xiahoudun: {
        sex: "male",
        group: "wei",
        hp: 6,
        skills: ["nysgs_jie_xiahoudun_skill", "nysgs_jie_xiahoudun_skill2", "nysgs_jie_xiahoudun_skill3"],
        trashBin: [],
    },
    nysgs_jie_guojia: {
        sex: "male",
        group: "wei",
        hp: 7,
        skills: ["nysgs_jie_guojia_skill", "nysgs_jie_guojia_skill2", "nysgs_jie_guojia_skill3"],
        trashBin: [],
    },
    nysgs_jie_sunjian: {
        sex: "male",
        group: "wu",
        hp: 6,
        skills: ["nysgs_jie_sunjian_skill", "nysgs_jie_sunjian_skill2", "nysgs_jie_sunjian_skill3"],
        trashBin: [],
    },
    nysgs_jie_luxun: {
        sex: "male",
        group: "wu",
        hp: 7,
        skills: ["nysgs_jie_luxun_skill", "nysgs_jie_luxun_skill2", "nysgs_jie_luxun_skill3"],
        trashBin: [],
    },
    nysgs_jie_ganning: {
        sex: "male",
        group: "wu",
        hp: 7,
        skills: ["nysgs_jie_ganning_skill", "nysgs_jie_ganning_skill2", "nysgs_jie_ganning_skill3"],
        trashBin: [],
    },
    nysgs_jie_huatuo: {
        sex: "male",
        group: "qun",
        hp: 6,
        skills: ["nysgs_jie_huatuo_skill", "nysgs_jie_huatuo_skill2", "nysgs_jie_huatuo_skill3"],
        trashBin: [],
    },
    nysgs_jie_weiyan: {
        sex: "male",
        group: "shu",
        hp: 7,
        skills: ["nysgs_jie_weiyan_skill", "nysgs_jie_weiyan_skill2", "nysgs_jie_weiyan_skill3"],
        trashBin: [],
    },
    nysgs_jie_masu: {
        sex: "male",
        group: "shu",
        hp: 7,
        skills: ["nysgs_jie_zhiman", "nysgs_jie_masu_skill2", "nysgs_jie_masu_skill3"],
        trashBin: [],
    },
    nysgs_jie_liuqi: {
        sex: "male",
        group: "qun",
        hp: 6,
        skills: ["nysgs_jie_liuqi_skill", "nysgs_jie_liuqi_skill2", "nysgs_jie_liuqi_skill3"],
        trashBin: [],
    },
};

Object.keys(characters2).forEach(key => {
    characters2[key].trashBin.push(`ext:怒焰三国/image/character/nysgs_${key.slice(10)}.jpg`);
    characters2[key].dieAudios = [`ext:怒焰三国/audio/die/nysgs_${key.slice(10)}_Death`];
    characters2[key].runestone = characters[`nysgs_${key.slice(10)}`].runestone ?? [];
    if (lib.config["extension_怒焰三国_refresh"]) {
        characters[`nysgs_${key.slice("nysgs_jie_".length)}`] = characters2[key];
    } else {
        characters[key] = characters2[key];
    }
});
if (lib.characterReplace) {
    for (let i in characters2) {
        const name = `nysgs_${i.slice(10)}`;
        if (!lib.characterReplace[name]) {
            lib.characterReplace[name] = [name, i];
        } else {
            lib.characterReplace[name].push(i);
        }
    }
}

const characters3 = {
    nysgs_qi_liubei: {
        sex: "male",
        group: "shu",
        hp: 6,
        skills: ["nysgs_qi_liubei_skill", "nysgs_qi_liubei_skill2", "nysgs_qi_liubei_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_qi_liubei_death"],
        runestone: ["nysgs_fs_qi_liubei"],
    },
    nysgs_qi_sunce: {
        sex: "male",
        group: "wu",
        hp: 1,
        maxHp: 7,
        skills: ["nysgs_qi_sunce_skill", "nysgs_qi_sunce_skill2", "nysgs_qi_sunce_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_huan_daqiao_death"],
        runestone: ["nysgs_fs_qi_sunce"],
    },
    nysgs_qi_diaochan: {
        sex: "female",
        group: "qun",
        hp: 6,
        skills: ["nysgs_qi_diaochan_skill", "nysgs_qi_diaochan_skill2", "nysgs_qi_diaochan_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_qi_diaochan_death"],
        runestone: ["nysgs_fs_qi_diaochan"],
    },
    nysgs_qi_zhangjiao: {
        sex: "male",
        group: "qun",
        hp: 6,
        skills: ["nysgs_qi_zhangjiao_skill", "nysgs_qi_zhangjiao_skill2", "nysgs_qi_zhangjiao_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_zhangjiao_death"],
        runestone: ["nysgs_fs_qi_zhangjiao"],
    },
    nysgs_qi_dongzhuo: {
        sex: "male",
        group: "qun",
        hp: 7,
        skills: ["nysgs_qi_dongzhuo_skill", "nysgs_qi_dongzhuo_skill2", "nysgs_qi_dongzhuo_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_qi_dongzhuo_death"],
        runestone: ["nysgs_fs_qi_dongzhuo"],
    },
    nysgs_qi_yuanshao: {
        sex: "male",
        group: "qun",
        hp: 6,
        skills: ["nysgs_qi_yuanshao_skill", "nysgs_qi_yuanshao_skill2", "nysgs_qi_yuanshao_skill3"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_qi_yuanshao_death"],
        runestone: ["nysgs_fs_qi_yuanshao"],
    },
};
Object.assign(characters, characters3);

Object.keys(characters3).forEach(key => {
    characters3[key].trashBin.push(`ext:怒焰三国/image/character/nysgs_${key.slice(9)}.jpg`);
});

const characters4 = {
    nysgs_shenshe_shen_huangzhong: {
        sex: "male",
        group: "shu",
        hp: 0,
        skills: ["nysgs_shen_huangzhong_skill4", "nysgs_shen_huangzhong_skill5", "nysgs_shen_huangzhong_skill6"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_shen_huangzhong_death"],
        runestone: ["nysgs_fs_shen_huangzhong"],
        img: "extension/怒焰三国/image/character/nysgs_shen_huangzhong.jpg",
        isUnseen: true,
    },
    nysgs_tianren_shen_huangzhong: {
        sex: "male",
        group: "shu",
        hp: 0,
        skills: ["nysgs_shen_huangzhong_skill7", "nysgs_shen_huangzhong_skill5", "nysgs_shen_huangzhong_skill8"],
        trashBin: [],
        dieAudios: ["ext:怒焰三国/audio/die/nysgs_shen_huangzhong_death"],
        runestone: ["nysgs_fs_shen_huangzhong2"],
        img: "extension/怒焰三国/image/character/nysgs_shen_huangzhong.jpg",
        isUnseen: true,
    },
}
Object.assign(characters, characters4);

export default characters;
