import test from 'node:test';
import assert from 'node:assert/strict';
import {spine} from '../apps/core/extension/ui/十周年局内UI/vendor/spine.js';
import {createExternalActionController} from '../apps/core/noname/skin/localDynamic/runtime/source-external-actions.js';
import {compileDecadeScene} from '../apps/core/noname/skin/localDynamic/runtime/source-scene.js';
import {compileSourceActions,sourceAction} from '../apps/core/noname/skin/localDynamic/runtime/source-actions.js';
function fixture(){const data=new spine.SkeletonData();data.animations=[new spine.Animation('first',[],1),new spine.Animation('strike',[],2)];return{state:new spine.AnimationState(new spine.AnimationStateData(data)),skeleton:new spine.Skeleton(data),visible:false};}
const action={animation:'strike',actionLayer:{playback:{speed:2}}};
test('external sprite completes on track time and restores primary once',async()=>{const l=fixture(),visibility=[],events=[];const c=createExternalActionController({load:async()=>l,setPrimaryHidden:x=>visibility.push(x)});assert.equal(await c.play(action,r=>events.push(r)),true);assert.equal(l.visible,true);l.state.update(1.01);l.state.apply(l.skeleton);assert.equal(l.visible,false);assert.deepEqual(events,['completed']);assert.deepEqual(visibility,[true,false]);l.state.clearTracks();assert.equal(events.length,1);});
test('superseding a pending load never hides the primary or plays stale result',async()=>{let resolve;const first=new Promise(r=>resolve=r),l=fixture(),visibility=[],events=[];let calls=0;const c=createExternalActionController({load:()=>++calls===1?first:Promise.resolve(l),setPrimaryHidden:x=>visibility.push(x)});const pending=c.play(action,r=>events.push(r));await c.play(action);resolve(l);assert.equal(await pending,false);assert.equal(l.visible,true);assert.deepEqual(events,['interrupted']);c.dispose();assert.equal(l.visible,false);});
test('reset/dispose during failed load suppresses stale errors and callbacks',async()=>{let reject;const p=new Promise((_,r)=>reject=r),events=[];const c=createExternalActionController({load:()=>p,setPrimaryHidden:()=>{}});const pending=c.play(action,r=>events.push(r));c.dispose();reject(Error('late network'));assert.equal(await pending,false);assert.deepEqual(events,['interrupted']);assert.equal(await c.play(action),false);});
test('failed load leaves primary visible and allows retry',async()=>{const l=fixture(),events=[],visible=[];let calls=0;const c=createExternalActionController({load:async()=>{if(!calls++)throw Error('network');return l;},setPrimaryHidden:x=>visible.push(x)});await assert.rejects(c.play(action,r=>events.push(r)),/network/);assert.deepEqual(events,['failed']);assert.deepEqual(visible,[false]);assert.equal(await c.play(action),true);});
test('unknown exact clip does not hide primary, source default uses original first clip',async()=>{const l=fixture(),visible=[];const c=createExternalActionController({load:async()=>l,setPrimaryHidden:x=>visible.push(x)});await assert.rejects(c.play({...action,animation:'STRIKE'}),/源动作不存在/);assert.equal(l.visible,false);await c.play({...action,animation:null});assert.equal(l.state.getCurrent(0).animation.name,'first');});
test('cached rig old track callbacks cannot hide a newer action; speed zero stays stationary',async()=>{const l=fixture(),events=[];const c=createExternalActionController({load:async()=>l,setPrimaryHidden:()=>{}});await c.play(action,r=>events.push(r));const old=l.state.getCurrent(0).listener;await c.play({...action,actionLayer:{playback:{speed:0}}});old.complete();assert.equal(l.visible,true);l.state.update(10);l.state.apply(l.skeleton);assert.equal(l.state.getCurrent(0).trackTime,0);assert.deepEqual(events,['interrupted']);c.stop();assert.equal(l.visible,false);});
test('protocol3 uses evidenced default first return and separate declared external sprite defaults',()=>{const s=compileDecadeScene({name:'idle',scale:.2,angle:10,gongji:{name:'effect',scale:.4,action:'strike'},shan:'dodge'},{sourceConfigHash:'fixture'});s.actionContract=compileSourceActions(s,{allowSourceDefault:true,externalModels:{gongji:{skeleton:'effect.skel',version:'3.6.38'}}});const external=sourceAction(s,'source:gongji',[]);assert.equal(external.mode,'external');assert.equal(external.actionLayer.placement.angle,0);assert.deepEqual(external.actionLayer.placement.x,[0,.5]);const dodge=sourceAction(s,'source:shan',[{name:'originalFirst'},{name:'dodge'}]);assert.equal(dodge.returnAnimation,'originalFirst');assert.equal(s.layers[0].playback.declaredAction,null);});

test('singleton source lists are exact selections and multi-choice lists remain unsupported',()=>{
 const s=compileDecadeScene({name:'actor',gongji:{action:['only']},teshu:{action:['a','b']}},{sourceConfigHash:'fixture'});
 const c=compileSourceActions(s,{allowSourceDefault:true});assert.equal(c.records[0].animation,'only');assert.equal(c.records[1].status,'unsupported');
 assert.deepEqual(s.source.gongji.action,['only']);
});
