// One policy shared by the importer and runtime. These files contain user
// overrides generated by editing a skin, not mandatory program code.
export const optionalScriptDefaults=Object.freeze({
 'original/千幻聆音/skinEdit.js': 'window.qhly_import(function(lib){lib.qhly_skinEdit ||= {};});\n',
 'original/千幻聆音/skinChange.js': 'window.qhly_import(function(lib){lib.qhly_skinChange ||= {};});\n',
 'original/皮肤切换/saveSkinParams.js': 'window.skinSwitchLoadParams=function(){window.skinSwitch.saveSkinParams ||= {};};\n',
});
export const scriptFallbacks=Object.freeze({
 'original/十周年UI/dynamicSkin.js':'original/十周年UI/dynamicSkin_default.js',
});
